(function (S, T) {
  "use strict";
  var domPack = { id: "dom_phase3_pack", name: "DOM Phase 3", version: "1", enabledByDefault: false, arcs: [{ id: "dom_arc", name: "DOM Arc", description: "UI verification", startEventId: "dom_disabled", initialStep: "start", steps: { start: {} }, completionConditions: [], failureConditions: [] }], events: [
    { id: "dom_disabled", trigger: S.Config.EVENT_TRIGGERS.DIPLOMACY_CHANGED, blocking: true, once: false, priority: 1, chance: 1, title: "Disabled UI", body: "Choice availability", conditions: [], selectors: {}, choices: [{ id: "disabled", label: "Unavailable", conditions: [{ type: "resource", resource: "gold", operator: ">", value: 99999 }], disabledReason: "Not enough resources", effects: [] }, { id: "ok", label: "Available", fallback: true, resultText: "Done", effects: [] }] },
    { id: "dom_long", trigger: S.Config.EVENT_TRIGGERS.DIPLOMACY_CHANGED, blocking: true, once: false, priority: 2, chance: 1, title: "Long Event", body: new Array(80).join("Long event text. "), conditions: [], selectors: {}, choices: [{ id: "ok", label: "Continue", fallback: true, resultText: "Done", effects: [] }] }
  ] };
  var domRegistration = S.Systems.Event.registerContentPack(domPack); if (!domRegistration.ok) throw new Error(domRegistration.errors.join(" / "));
  function opening() { var state = S.State.createInitialState({ scenarioId: "owari_short", playerFactionId: "aotsuki", difficultyId: "normal" }); S.State.current = state; var result = S.Systems.Campaign.begin(state); T.assert(result.ok, result.errors && result.errors.join(" / ")); return state; }
  function campaign() { var state = S.State.createInitialState({ scenarioId: "core_campaign", playerFactionId: "aotsuki", difficultyId: "normal" }); S.State.current = state; return state; }
  T.test("Phase 2 DOM: active eventを描画", function () { opening(); T.assert(S.UI.showActiveEvent()); var html = S.UI.el("modalContent").innerHTML; T.assert(html.indexOf("最初の一手") >= 0); T.assert(html.indexOf("正攻法") >= 0); T.assert(html.indexOf("夜襲") >= 0); T.assert(html.indexOf("強襲") >= 0); T.equal(S.UI.el("modalBackdrop").classList.contains("hidden"), false); });
  T.test("Phase 2 DOM: template値をescapeして描画", function () { var state = opening(); state.castles.kiyosu.name = "<script>alert(1)</script>"; S.UI.showActiveEvent(); var html = S.UI.el("modalContent").innerHTML; T.assert(html.indexOf("&lt;script&gt;") >= 0); T.equal(html.indexOf("<script>alert"), -1); });
  T.test("Phase 2 DOM: blocking eventは閉じられない", function () { opening(); S.UI.showActiveEvent(); T.equal(S.UI.closeModal(), false); T.equal(S.UI.el("modalBackdrop").classList.contains("hidden"), false); });
  T.test("Phase 2 DOM: resultとnext buttonを描画", function () { var state = opening(), active = state.events.engine.activeEvent, result = S.Systems.Event.resolveChoice(state, active.instanceId, "standard"); T.assert(result.ok); S.UI.showEventResult(result.stateChanges.historyEntry); var html = S.UI.el("modalContent").innerHTML; T.assert(html.indexOf("EVENT RESULT") >= 0); T.assert(html.indexOf("data-event-next") >= 0); });
  T.test("Phase 2 DOM: event historyを描画", function () { var state = opening(); S.Systems.Event.resolveChoice(state, state.events.engine.activeEvent.instanceId, "assault"); S.UI.showEventHistory(); var html = S.UI.el("modalContent").innerHTML; T.assert(html.indexOf("出来事履歴") >= 0); T.assert(html.indexOf("強襲") >= 0); });
  T.test("Phase 2 DOM: battle planner presetを既存UIへ渡す", function () { var state = opening(); S.Systems.Event.resolveChoice(state, state.events.engine.activeEvent.instanceId, "night"); T.assert(S.UI.openEventInteraction()); var html = S.UI.el("modalContent").innerHTML; T.assert(html.indexOf("value=\"soma\" selected") >= 0); T.assert(html.indexOf("value=\"night\" selected") >= 0); T.assert(html.indexOf("data-opening=\"1\"") >= 0); });
  T.test("Phase 3 DOM: disabled reason", function () { var state = campaign(); S.Systems.Event.queueEvent(state, "dom_disabled", {}); S.UI.showActiveEvent(); T.assert(S.UI.el("modalContent").innerHTML.indexOf("Not enough resources") >= 0); T.assert(S.UI.el("modalContent").innerHTML.indexOf("aria-disabled=\"true\"") >= 0); });
  T.test("Phase 3 DOM: keyboard activation", function () { var state = campaign(); S.Systems.Event.queueEvent(state, "dom_disabled", {}); var id = state.events.engine.activeEvent.instanceId, result = S.UI.activateEventChoice("Enter", id, "ok"); T.assert(result.ok); T.assert(S.UI.el("modalContent").innerHTML.indexOf("EVENT RESULT") >= 0); });
  T.test("Phase 3 DOM: double click prevention", function () { var state = campaign(); S.Systems.Event.queueEvent(state, "dom_disabled", {}); var id = state.events.engine.activeEvent.instanceId; T.assert(S.UI.resolveEventChoice(id, "ok").ok); T.equal(S.UI.resolveEventChoice(id, "ok").ok, false); T.equal(state.events.engine.history.filter(function (entry) { return entry.instanceId === id; }).length, 1); });
  T.test("Phase 3 DOM: active event restored after load", function () { var state = campaign(), key = "dom_active"; S.Systems.Event.queueEvent(state, "dom_disabled", {}); var id = state.events.engine.activeEvent.instanceId; T.assert(S.Save.save(state, key).ok); var loaded = S.Save.load(key); T.assert(loaded.ok); T.equal(S.Systems.Event.getActiveEvent(loaded.state).instanceId, id); T.assert(S.UI.showActiveEvent()); S.Save.remove(key); });
  T.test("Phase 3 DOM: long text scrolling container", function () { var state = campaign(); S.Systems.Event.queueEvent(state, "dom_long", {}); S.UI.showActiveEvent(); var html = S.UI.el("modalContent").innerHTML; T.assert(html.indexOf("event-view") >= 0); T.assert(html.length > 1000); });
  T.test("Phase 3 DOM: mobile width rendering", function () { window.innerWidth = 375; var state = campaign(); S.Systems.Event.queueEvent(state, "dom_disabled", {}); T.assert(S.UI.showActiveEvent()); T.assert(S.UI.el("modalContent").innerHTML.indexOf("event-choices") >= 0); });
  T.test("Phase 3 DOM: story arc status", function () { var state = campaign(); T.assert(S.Systems.Event.Arc.start(state, "dom_arc").ok); S.UI.showArcStatus(); var html = S.UI.el("modalContent").innerHTML; T.assert(html.indexOf("STORY ARC STATUS") >= 0); T.assert(html.indexOf("DOM Arc") >= 0); T.assert(html.indexOf("active") >= 0); });
  T.test("Phase 3 DOM: event debug snapshot", function () { var state = campaign(); S.Systems.Event.queueEvent(state, "dom_disabled", {}); var snapshot = S.UI.eventDebugSnapshot(); T.equal(snapshot.activeEvent.eventId, "dom_disabled"); T.assert(Array.isArray(snapshot.diagnostics)); });
  T.test("Phase 3 DOM: debug event inspection", function () { campaign(); S.UI.toggleDebug(true); var html = S.UI.el("debugPanel").innerHTML; T.assert(html.indexOf("EVENT ENGINE") >= 0); T.assert(html.indexOf("data-event-debug-inspection") >= 0); T.assert(html.indexOf("core_season_events") >= 0); });
  T.run();
})(window.Sengoku, window.SengokuTest);
