"use strict";
var fs = require("fs"), path = require("path"), vm = require("vm"), root = path.resolve(__dirname, "..");
global.window = global; global.addEventListener = function () {};
[
  "src/namespace.js", "src/config/constants.js", "src/config/balance.js", "src/data/factions.js", "src/data/castles.js", "src/data/castleTraits.js", "src/data/officers.js", "src/data/tactics.js", "src/data/unitTypes.js", "src/data/events.js", "src/data/contentPacks.js", "src/data/eventExtensions.js", "src/data/difficulties.js", "src/data/scenarios.js", "src/data/diplomacy.js", "src/state/schema.js", "src/state/createInitialState.js", "src/state/validateState.js", "src/state/migrateState.js", "src/systems/officerSystem.js", "src/systems/unitSystem.js", "src/systems/armySystem.js", "src/systems/relationshipSystem.js", "src/systems/loyaltySystem.js", "src/systems/rivalrySystem.js", "src/systems/eventSystem.js", "src/systems/prisonerSystem.js", "src/systems/diplomacySystem.js", "src/systems/releaseSystem.js", "src/systems/domesticSystem.js", "src/systems/victorySystem.js", "src/systems/siegeSystem.js", "src/systems/battleSystem.js", "src/systems/aiSystem.js", "src/systems/turnSystem.js"
].forEach(function (file) { vm.runInThisContext(fs.readFileSync(path.join(root, file), "utf8"), { filename: file }); });
function state() { return Sengoku.State.createInitialState({ scenarioId: "core_campaign", playerFactionId: "aotsuki", difficultyId: "normal", eventSeed: 77 }); }
function event(id, next, effects, chance, trigger) { return { id: id, trigger: trigger || Sengoku.Config.EVENT_TRIGGERS.DIPLOMACY_CHANGED, blocking: true, once: false, priority: 1, chance: chance === undefined ? 1 : chance, title: id, body: id, conditions: [], selectors: {}, choices: [{ id: "ok", label: "ok", fallback: true, resultText: "ok", nextEventId: next, effects: effects || [] }] }; }
var chain = [], i; for (i = 1; i <= 13; i += 1) chain.push(event("stress_chain_" + i, i < 13 ? "stress_chain_" + (i + 1) : null));
var tenEffects = []; for (i = 0; i < 8; i += 1) tenEffects.push({ type: "addCounter", counter: "atomic", amount: 1 }); tenEffects.push({ type: "officerMove", officerId: "missing", targetCastleId: "kiyosu" }); tenEffects.push({ type: "addLog", text: "must not commit" });
var pack = { id: "event_stress_pack", name: "Event Stress", version: "1", enabledByDefault: false, events: [event("stress_simple", null, []), event("stress_emit", null, [], 0, Sengoku.Config.EVENT_TRIGGERS.OFFICER_LOYALTY_CHANGED), event("stress_atomic", null, tenEffects)].concat(chain) };
var registered = Sengoku.Systems.Event.registerContentPack(pack), checks = [], failures = [];
if (!registered.ok) throw new Error("stress pack registration: " + registered.errors.join(" / "));
function check(name, condition) { checks.push({ name: name, result: condition ? "PASS" : "FAIL" }); if (!condition) failures.push(name); }
check("stress pack registration", registered.ok);
var emitState = state(); emitState.events.engine.enabledPackIds.push("event_stress_pack"); for (i = 0; i < 10000; i += 1) Sengoku.Systems.Event.emit(emitState, Sengoku.Config.EVENT_TRIGGERS.OFFICER_LOYALTY_CHANGED, { n: i }, { random: function () { return 0.5; } }); check("10000 Event.emit", emitState.events.engine.emissionCount === 10000);
for (i = 0; i < 250; i += 1) Sengoku.Systems.Event.addDiagnostic(emitState, "stress_" + i, "diagnostic " + i, null); check("diagnostics limit", emitState.events.engine.diagnostics.length === 200);
var historyState = state(); for (i = 0; i < 520; i += 1) { var historyQueued = Sengoku.Systems.Event.queueEvent(historyState, "stress_simple", { n: i }); if (!historyQueued.ok || !historyState.events.engine.activeEvent) throw new Error("history queue failed at " + i + ": " + JSON.stringify(historyQueued.errors || historyQueued)); var historyResolved = Sengoku.Systems.Event.resolveChoice(historyState, historyState.events.engine.activeEvent.instanceId, "ok"); if (!historyResolved.ok) throw new Error("history resolve failed at " + i + ": " + JSON.stringify(historyResolved.errors)); } check("history limit", historyState.events.engine.history.length === 500);
var queueState = state(); for (i = 0; i < 51; i += 1) Sengoku.Systems.Event.queueEvent(queueState, "stress_simple", { n: i }); var overflow = Sengoku.Systems.Event.queueEvent(queueState, "stress_simple", { n: 51 }); check("queue limit", queueState.events.engine.queue.length === 50 && overflow.ok === false);
var chainState = state(); Sengoku.Systems.Event.queueEvent(chainState, "stress_chain_1", {}); for (i = 1; i < 12; i += 1) Sengoku.Systems.Event.resolveChoice(chainState, chainState.events.engine.activeEvent.instanceId, "ok"); check("12 step chain", chainState.events.engine.activeEvent && chainState.events.engine.activeEvent.chainDepth === 12); check("13th step rejected", Sengoku.Systems.Event.resolveChoice(chainState, chainState.events.engine.activeEvent.instanceId, "ok").ok === false);
var selfCycle = Sengoku.Systems.Event.registerContentPack({ id: "stress_self_cycle", name: "self", version: "1", events: [event("stress_self", "stress_self")] }); check("direct cycle rejected", selfCycle.ok === false);
var indirectCycle = Sengoku.Systems.Event.registerContentPack({ id: "stress_indirect_cycle", name: "indirect", version: "1", events: [event("stress_a", "stress_b"), event("stress_b", "stress_a")] }); check("indirect cycle rejected", indirectCycle.ok === false);
var atomicState = state(); Sengoku.Systems.Event.queueEvent(atomicState, "stress_atomic", {}); var log = JSON.stringify(atomicState.events.log), history = atomicState.events.engine.history.length, atomicResult = Sengoku.Systems.Event.resolveChoice(atomicState, atomicState.events.engine.activeEvent.instanceId, "ok"); check("10-effect atomic rollback", atomicResult.ok === false && atomicState.events.engine.counters.atomic === undefined && JSON.stringify(atomicState.events.log) === log && atomicState.events.engine.history.length === history);
check("final validateState", Sengoku.State.validateState(emitState).ok && Sengoku.State.validateState(historyState).ok && Sengoku.State.validateState(queueState).ok && Sengoku.State.validateState(chainState).ok && Sengoku.State.validateState(atomicState).ok);
process.stdout.write(JSON.stringify({ checks: checks, result: failures.length ? "FAIL" : "PASS" }, null, 2) + "\n"); if (failures.length) process.exitCode = 1;
