"use strict";
var fs = require("fs"), path = require("path"), vm = require("vm"), root = path.resolve(__dirname, "..");
global.window = global; global.addEventListener = function () {};
[
  "src/namespace.js", "src/config/constants.js", "src/config/balance.js", "src/data/factions.js", "src/data/castles.js", "src/data/castleTraits.js", "src/data/officers.js", "src/data/tactics.js", "src/data/unitTypes.js", "src/data/events.js", "src/data/contentPacks.js", "src/data/eventExtensions.js", "src/data/difficulties.js", "src/data/scenarios.js", "src/data/diplomacy.js", "src/state/schema.js", "src/state/createInitialState.js", "src/state/validateState.js", "src/state/migrateState.js", "src/systems/officerSystem.js", "src/systems/unitSystem.js", "src/systems/armySystem.js", "src/systems/relationshipSystem.js", "src/systems/loyaltySystem.js", "src/systems/rivalrySystem.js", "src/systems/eventSystem.js", "src/systems/prisonerSystem.js", "src/systems/diplomacySystem.js", "src/systems/releaseSystem.js", "src/systems/domesticSystem.js", "src/systems/victorySystem.js", "src/systems/siegeSystem.js", "src/systems/battleSystem.js", "src/systems/aiSystem.js", "src/systems/turnSystem.js"
].forEach(function (file) { vm.runInThisContext(fs.readFileSync(path.join(root, file), "utf8"), { filename: file }); });
function invalidNumbers(value) { var count = 0; (function inspect(item) { if (typeof item === "number" && !Number.isFinite(item)) count += 1; else if (item && typeof item === "object") Object.keys(item).forEach(function (key) { inspect(item[key]); }); })(value); return count; }
function signature(state) { return JSON.stringify({ turn: state.campaign.turn, outcome: state.campaign.outcome, castles: Object.keys(state.castles).sort().map(function (id) { return [id, state.castles[id].factionId, state.castles[id].troops]; }), history: state.events.engine.history.map(function (entry) { return [entry.eventId, entry.selectedChoiceId, entry.result, entry.turn]; }), metrics: state.events.engine.metrics }); }
var profiles = [
  { seed: 911, playerFactionId: "aotsuki", difficultyId: "easy" }, { seed: 1223, playerFactionId: "tokizawa", difficultyId: "normal" },
  { seed: 1559, playerFactionId: "yukishiro", difficultyId: "hard" }, { seed: 1877, playerFactionId: "kurogane", difficultyId: "easy" },
  { seed: 2017, playerFactionId: "aotsuki", difficultyId: "normal" }, { seed: 2381, playerFactionId: "tokizawa", difficultyId: "hard" },
  { seed: 2711, playerFactionId: "yukishiro", difficultyId: "easy" }, { seed: 3037, playerFactionId: "kurogane", difficultyId: "normal" }
];
function run(profile) {
  var rng = Sengoku.Systems.Event.createDeterministicRng(profile.seed), state = Sengoku.State.createInitialState({ scenarioId: "core_campaign", playerFactionId: profile.playerFactionId, difficultyId: profile.difficultyId, eventSeed: profile.seed }), exception = null, simulation;
  try { Sengoku.Systems.Campaign.begin(state); simulation = Sengoku.Systems.AI.simulateAllFactions(state, 300, rng, { terminationLimit: 300 }); } catch (error) { exception = error; simulation = { ok: false, stateChanges: { completedSeasons: state.campaign.turn, treatyViolationAttacks: -1 } }; }
  var validation = Sengoku.State.validateState(state), governors = Object.keys(state.castles).map(function (id) { return state.castles[id].governorId; }).filter(Boolean), diagnostics = state.events.engine.diagnostics, coreFires = ["autumn_harvest", "winter_hardship", "summer_merchants"].reduce(function (sum, id) { return sum + (state.events.engine.firedEventIds[id] || 0); }, 0);
  var summary = { seed: profile.seed, playerFactionId: profile.playerFactionId, difficultyId: profile.difficultyId, completedSeasons: simulation.stateChanges.completedSeasons, emitCount: state.events.engine.emissionCount, matchedEventCount: state.events.engine.metrics.matchedEvents, queuedEventCount: state.events.engine.metrics.queuedEvents, automaticallyResolvedEventCount: state.events.engine.metrics.automaticResolutions, aiChoiceDistribution: state.events.engine.metrics.aiChoiceDistribution, arcStarts: state.events.engine.metrics.arcStarts, arcCompletions: state.events.engine.metrics.arcCompletions, diagnostics: diagnostics.length, maximumQueueLength: state.events.engine.metrics.maxQueueLength, maximumChainDepth: state.events.engine.metrics.maxChainDepth, unresolvedActiveEvents: state.events.engine.activeEvent ? 1 : 0, outcome: state.campaign.outcome, validation: validation.ok ? "PASS" : validation.errors, exceptions: exception ? 1 : 0, invalidNumbers: invalidNumbers(state), negativeTroops: Object.keys(state.castles).filter(function (id) { return state.castles[id].troops < 0; }).length, invalidReferences: validation.ok ? 0 : validation.errors.length, duplicateGovernors: governors.length - new Set(governors).size, treatyViolationAttacks: simulation.stateChanges.treatyViolationAttacks || 0, queueLimitViolations: diagnostics.filter(function (item) { return item.code === "queue_full"; }).length, chainLimitViolations: diagnostics.filter(function (item) { return item.code === "chain_limit"; }).length, coreSeasonEventFires: coreFires };
  summary.ok = Boolean(simulation.ok && validation.ok && !summary.exceptions && !summary.invalidNumbers && !summary.negativeTroops && !summary.invalidReferences && !summary.duplicateGovernors && !summary.treatyViolationAttacks && !summary.queueLimitViolations && !summary.chainLimitViolations && !summary.unresolvedActiveEvents && (state.campaign.gameOver || coreFires >= 2));
  return { state: state, summary: summary, signature: signature(state) };
}
var results = profiles.map(run), replay = run(profiles[0]), deterministic = results[0].signature === replay.signature, allOk = deterministic && results.every(function (item) { return item.summary.ok; });
process.stdout.write(JSON.stringify({ runs: results.map(function (item) { return item.summary; }), deterministicReplay: deterministic ? "PASS" : "FAIL", result: allOk ? "PASS" : "FAIL" }, null, 2) + "\n");
if (!allOk) process.exitCode = 1;
