(function (S, T) {
  "use strict";
  function fresh() { var state=S.State.createInitialState({scenarioId:"core_campaign",playerFactionId:"aotsuki"}); state.campaign.status="playing"; state.settings.aiEnabled=false; return state; }
  function war(state,a,b){ var r=S.Systems.Diplomacy.relation(state,a,b); r.status="war"; r.expiresTurn=null; r.sinceTurn=state.campaign.turn; r.lastActionTurn=-1; }
  function valid(state){ var v=S.State.validateState(state); T.assert(v.ok,v.errors.join(" / ")); }
  function enemyLaunch(state){ return S.Systems.Army.deployAndMarch(state,"narumi","kiyosu",[{officerId:"hiyori",unitType:"ashigaru",troops:20}],{commanderId:"hiyori",factionId:"tokizawa",consumeCommand:false,route:["narumi","kiyosu"],maxHops:1,mission:"attack"}); }
  function playerSpecs(){ return [{officerId:"keiketsu",unitType:"ashigaru",troops:20}]; }

  T.test("Phase9: 最終進軍区間に入った敵軍は迎撃可能", function(){ var s=fresh(); war(s,"aotsuki","tokizawa"); var e=enemyLaunch(s); T.assert(e.ok); var c=S.Systems.Army.canIntercept(s,e.stateChanges.armyId,"kiyosu"); T.assert(c.ok,c.errors&&c.errors.join(" / ")); T.equal(c.stateChanges.route.join(">"),"kiyosu>narumi"); valid(s); });

  T.test("Phase9: 迎撃軍は敵軍と逆向きの同一街道へ出陣する", function(){ var s=fresh(); war(s,"aotsuki","tokizawa"); var e=enemyLaunch(s); var p=S.Systems.Army.deployIntercept(s,"kiyosu",e.stateChanges.armyId,playerSpecs(),{commanderId:"keiketsu",consumeCommand:false}); T.assert(p.ok,p.errors&&p.errors.join(" / ")); var pa=s.armies[p.stateChanges.armyId], ea=s.armies[e.stateChanges.armyId]; T.equal(pa.mission,"intercept"); T.equal(pa.targetArmyId,ea.id); T.assert(S.Systems.Army.sameSegment(S.Systems.Army.currentSegment(pa,s),S.Systems.Army.currentSegment(ea,s))); valid(s); });

  T.test("Phase9: 同じ街道の敵Army接触を検出できる", function(){ var s=fresh(); war(s,"aotsuki","tokizawa"); var e=enemyLaunch(s); var p=S.Systems.Army.deployIntercept(s,"kiyosu",e.stateChanges.armyId,playerSpecs(),{commanderId:"keiketsu",consumeCommand:false}); var hit=S.Systems.Army.findEnemyContact(s,p.stateChanges.armyId); T.assert(hit); T.equal(hit.id,e.stateChanges.armyId); valid(s); });

  T.test("Phase9: Player Army接触はTactical野戦pendingを生成する", function(){ var s=fresh(); war(s,"aotsuki","tokizawa"); var e=enemyLaunch(s); var p=S.Systems.Army.deployIntercept(s,"kiyosu",e.stateChanges.armyId,playerSpecs(),{commanderId:"keiketsu",consumeCommand:false}); var r=S.Systems.Army.resolveFieldContact(s,p.stateChanges.armyId,e.stateChanges.armyId,{allowTactical:true}); T.assert(r.ok,r.errors&&r.errors.join(" / ")); T.equal(s.events.pendingTacticalBattle.kind,"field_battle"); T.equal(s.armies[p.stateChanges.armyId].status,"in_battle"); T.equal(s.armies[e.stateChanges.armyId].status,"in_battle"); T.assert(s.events.pendingTacticalBattle.battleSpec.attacker.units.length>0); T.assert(s.events.pendingTacticalBattle.battleSpec.defender.units.length>0); valid(s); });

  T.test("Phase9: Tactical迎撃勝利で敵軍は撤退し城所有権は変わらない", function(){ var s=fresh(); war(s,"aotsuki","tokizawa"); var ownerBefore=s.castles.narumi.factionId; var e=enemyLaunch(s); var enemyId=e.stateChanges.armyId; var p=S.Systems.Army.deployIntercept(s,"kiyosu",enemyId,playerSpecs(),{commanderId:"keiketsu",consumeCommand:false}); var playerId=p.stateChanges.armyId; var prep=S.Systems.Army.resolveFieldContact(s,playerId,enemyId,{allowTactical:true}); T.assert(prep.ok); var pending=s.events.pendingTacticalBattle, units=[]; pending.battleSpec.attacker.units.forEach(function(u){units.push({id:u.id,side:"player",officerId:u.officerId,troopsAfter:u.troops,morale:75,status:"active"});}); pending.battleSpec.defender.units.forEach(function(u){units.push({id:u.id,side:"enemy",officerId:u.officerId,coreOfficerId:u.coreOfficerId,troopsAfter:Math.floor(u.troops*0.2),morale:20,status:"routed"});}); var raw={seed:pending.seed,winner:"player",units:units,attackerLoss:0,defenderLoss:100,durationTicks:500}; var outcome=S.Systems.BattleAdapter.translateResult(s,pending,raw); T.assert(outcome); var applied=S.Systems.Army.applyFieldTacticalOutcome(s,pending,outcome); T.assert(applied.ok,applied.errors&&applied.errors.join(" / ")); s.events.pendingTacticalBattle=null; T.assert(s.armies[enemyId]&&s.armies[enemyId].status==="returning","Phase10では敗軍は1季だけ敗走Armyとして残る"); T.assert(!s.armies[playerId],"迎撃勝利後は防衛城へ帰還・解散する"); T.equal(s.castles.narumi.factionId,ownerBefore); valid(s); });

  T.test("Phase9: allowTactical=falseならArmy野戦を自動解決できる", function(){ var s=fresh(); war(s,"aotsuki","tokizawa"); var e=enemyLaunch(s); var p=S.Systems.Army.deployIntercept(s,"kiyosu",e.stateChanges.armyId,playerSpecs(),{commanderId:"keiketsu",consumeCommand:false}); var owners={kiyosu:s.castles.kiyosu.factionId,narumi:s.castles.narumi.factionId}; var r=S.Systems.Army.resolveFieldContact(s,p.stateChanges.armyId,e.stateChanges.armyId,{allowTactical:false,random:function(){return 0.5;}}); T.assert(r.ok,r.errors&&r.errors.join(" / ")); T.equal(s.castles.kiyosu.factionId,owners.kiyosu); T.equal(s.castles.narumi.factionId,owners.narumi); T.assert(!s.events.pendingTacticalBattle); valid(s); });

  T.test("Phase9: 敵軍が迎撃圏外なら出陣できない", function(){ var s=fresh(); war(s,"aotsuki","tokizawa"); var e=S.Systems.Army.deployAndMarch(s,"akane","kiyosu",[{officerId:"tokizawa_temp_3",unitType:"ashigaru",troops:20}],{commanderId:"tokizawa_temp_3",factionId:"tokizawa",consumeCommand:false,maxHops:3}); T.assert(e.ok,e.errors&&e.errors.join(" / ")); var c=S.Systems.Army.canIntercept(s,e.stateChanges.armyId,"kiyosu"); T.assert(!c.ok); valid(s); });

  T.run();
})(window.Sengoku, window.SengokuTest);
