(function (S, T) {
  "use strict";
  function fresh(options) { return S.State.createInitialState(Object.assign({ scenarioId: "owari_short", playerFactionId: "aotsuki", difficultyId: "normal" }, options || {})); }
  function campaign() { return S.State.createInitialState({ scenarioId: "core_campaign", playerFactionId: "aotsuki", difficultyId: "normal" }); }
  function asV09(state) {
    var old = S.Util.deepClone(state);
    old.schemaVersion = 9; old.gameVersion = "core-0.9";
    Object.keys(old.officers).forEach(function (id) { delete old.officers[id].profile; });
    delete old.events.engine; delete old.meta.schemaMigratedAt;
    return old;
  }
  function same(actual, expected, message) { T.equal(JSON.stringify(actual), JSON.stringify(expected), message); }

  T.test("Phase 1: schemaVersion 12とcore-0.95", function () { var state = fresh(); T.equal(state.schemaVersion, 12); T.equal(state.gameVersion, "core-0.95"); T.equal(S.State.schema.schemaVersion, 12); });
  T.test("Phase 1: 初期イベントengine", function () { var engine = fresh({ eventSeed: 42 }).events.engine; T.assert(engine.enabledPackIds.indexOf("core_season_events") >= 0); T.assert(engine.enabledPackIds.indexOf("core_opening_events") >= 0); T.equal(engine.rng.seed, 42); T.equal(engine.emissionCount, 0); T.assert(Array.isArray(engine.history)); });
  T.test("Phase 1: 全武将に空profile", function () { var state = campaign(); Object.keys(state.officers).forEach(function (id) { same(state.officers[id].profile, { personalityIds: [], traitIds: [], tags: [] }, id); }); });
  T.test("Phase 1: Content Pack Registry検証", function () { var result = S.Systems.Event.validateContentPackRegistry(S.Data.ContentPackRegistry); T.assert(result.ok, result.errors.join(" / ")); T.equal(S.Data.ContentPackRegistry.order[0], "core_season_events"); });
  T.test("Phase 1: 実行可能なイベントデータを拒否", function () { var pack = S.Util.deepClone(S.Data.ContentPackRegistry.packs.core_season_events); pack.id = "invalid_executable"; pack.events[0].handler = function () {}; T.equal(S.Systems.Event.validateContentPack(pack).ok, false); });
  T.test("Phase 1: raw HTMLメッセージを拒否", function () { var definition = S.Util.deepClone(S.Data.events[0]); definition.message = "<b>unsafe</b>"; T.equal(S.Systems.Event.validateDefinition(definition).ok, false); });
  T.test("Phase 1: trigger indexを優先度順にコンパイル", function () { var result = S.Systems.Event.compileTriggerIndex(); T.assert(result.ok, result.errors.join(" / ")); var items = result.triggerIndex[S.Config.EVENT_TRIGGERS.SEASON_START]; T.equal(items.length, 3); T.equal(items[0].id, "autumn_harvest"); T.equal(items[2].id, "summer_merchants"); });
  T.test("Phase 1: Event.emitで秋イベントを実行", function () { var state = fresh(), before = state.campaign.food; state.campaign.season = 2; var result = S.Systems.Event.emit(state, S.Config.EVENT_TRIGGERS.SEASON_START, {}, { random: function () { return 0; } }); T.assert(result.ok, result.errors.join(" / ")); T.equal(state.campaign.food, before + 23); same(result.stateChanges.appliedEventIds, ["autumn_harvest"]); T.equal(state.events.engine.emissionCount, 1); });
  T.test("Phase 1: 無効化Content Packは発火しない", function () { var state = fresh(), before = state.campaign.food; state.campaign.season = 2; state.events.engine.enabledPackIds = []; var result = S.Systems.Event.emit(state, S.Config.EVENT_TRIGGERS.SEASON_START, {}, { random: function () { return 0; } }); T.assert(result.ok); T.equal(state.campaign.food, before); });
  T.test("Phase 1: 注入RNGは確率判定へ使用", function () { var state = fresh(), before = state.campaign.gold; state.campaign.season = 1; S.Systems.Event.emit(state, S.Config.EVENT_TRIGGERS.SEASON_START, {}, { random: function () { return 0.99; } }); T.equal(state.campaign.gold, before); });
  T.test("Phase 1: deterministic RNGは同seedで同列", function () { var a = S.Systems.Event.createDeterministicRng(12345), b = S.Systems.Event.createDeterministicRng(12345), valuesA = [], valuesB = []; for (var i = 0; i < 6; i += 1) { valuesA.push(a()); valuesB.push(b()); } same(valuesA, valuesB); same(a.snapshot(), b.snapshot()); });
  T.test("Phase 1: state RNGは保存可能かつ決定的", function () { var a = fresh({ eventSeed: 77 }), b = fresh({ eventSeed: 77 }); a.campaign.season = 1; b.campaign.season = 1; var resultA = S.Systems.Event.emit(a, S.Config.EVENT_TRIGGERS.SEASON_START), resultB = S.Systems.Event.emit(b, S.Config.EVENT_TRIGGERS.SEASON_START); same(resultA.stateChanges.appliedEventIds, resultB.stateChanges.appliedEventIds); same(a.events.engine.rng, b.events.engine.rng); });
  T.test("Phase 1移行: schema 9データを保持", function () { var old = asV09(campaign()); old.campaign.gold = 321; old.diplomacy.warExhaustion.aotsuki = 47; old.relationships.officers["kanenobu|keiketsu"] = 37; old.officers.keiketsu.history.push({ turn: 4, text: "v0.9 marker" }); old.events.log.push({ text: "event marker", type: "major" }); var preserved = { campaign: old.campaign, factions: old.factions, castles: old.castles, diplomacy: old.diplomacy, relationships: old.relationships, prisoners: old.prisoners, rivalries: old.rivalries, chronicle: old.chronicle, events: old.events, officers: S.Util.deepClone(old.officers) }; var result = S.State.migrateState(old); T.assert(result.ok, result.errors && result.errors.join(" / ")); T.equal(result.source, "core-0.9"); same(result.state.campaign, preserved.campaign); same(result.state.factions, preserved.factions); same(result.state.castles, preserved.castles); same(result.state.diplomacy, preserved.diplomacy); same(result.state.relationships, preserved.relationships); same(result.state.events.log, preserved.events.log); same(result.state.officers.keiketsu.history, preserved.officers.keiketsu.history); T.equal(result.state.schemaVersion, 12); T.assert(result.state.events.engine); });
  T.test("Phase 1移行: profile既存拡張値を保持", function () { S.Data.PersonalityRegistry.definitions.future = { id: "future" }; S.Data.TraitRegistry.definitions.future_trait = { id: "future_trait" }; var old = asV09(fresh()); old.officers.keiketsu.profile = { personalityId: "future", traitIds: ["future_trait"], tags: ["future_tag"], custom: { keep: true } }; var result = S.State.migrateState(old); T.assert(result.ok, result.errors && result.errors.join(" / ")); same(result.state.officers.keiketsu.profile.custom, { keep: true }); T.equal(result.state.officers.keiketsu.profile.personalityIds[0], "future"); delete S.Data.PersonalityRegistry.definitions.future; delete S.Data.TraitRegistry.definitions.future_trait; });
  T.test("Phase 1検証: 不正イベントengineを拒否", function () { var state = fresh(); state.events.engine.rng.calls = -1; T.equal(S.State.validateState(state).ok, false); });
  T.test("Phase 1検証: 不正officer profileを拒否", function () { var state = fresh(); state.officers.keiketsu.profile.traitIds = ["same", "same"]; T.equal(S.State.validateState(state).ok, false); });
  T.test("Phase 1: 既存3季節イベント定義を検証", function () { T.equal(S.Data.events.length, 3); S.Data.events.forEach(function (definition) { var result = S.Systems.Event.validateDefinition(definition); T.assert(result.ok, result.errors.join(" / ")); }); });
  T.test("Phase 1: 既存季節進行から秋収穫を実行", function () { var state = fresh(), before = state.campaign.food; state.campaign.season = 1; S.Systems.Turn.advance(state, { skipAI: true, random: function () { return 0.99; } }); T.assert(state.campaign.food >= before + 23); T.assert(state.events.log.some(function (item) { return item.text.indexOf("秋の収穫") >= 0; })); });

  T.run();
})(window.Sengoku, window.SengokuTest);
