(function(S,T){
  "use strict";
  function fresh(){var s=S.State.createInitialState({scenarioId:"core_campaign",playerFactionId:"aotsuki"});s.campaign.status="playing";s.settings.aiEnabled=false;return s;}
  function war(s){var r=S.Systems.Diplomacy.relation(s,"aotsuki","tokizawa");r.status="war";r.expiresTurn=null;r.sinceTurn=s.campaign.turn;r.lastActionTurn=-1;}
  function makePlayerWin(s){war(s);var e=S.Systems.Army.deployAndMarch(s,"narumi","kiyosu",[{officerId:"hiyori",unitType:"ashigaru",troops:30}],{commanderId:"hiyori",factionId:"tokizawa",consumeCommand:false,route:["narumi","kiyosu"],maxHops:1,mission:"attack"});var p=S.Systems.Army.deployIntercept(s,"kiyosu",e.stateChanges.armyId,[{officerId:"keiketsu",unitType:"kiba",troops:60}],{commanderId:"keiketsu",consumeCommand:false});return S.Systems.Army.resolveFieldContact(s,p.stateChanges.armyId,e.stateChanges.armyId,{allowTactical:false,random:function(){return 0.5;}}).stateChanges.report;}
  function makeAIWin(s){war(s);var e=S.Systems.Army.deployAndMarch(s,"narumi","kiyosu",[{officerId:"hiyori",unitType:"ashigaru",troops:45}],{commanderId:"hiyori",factionId:"tokizawa",consumeCommand:false,route:["narumi","kiyosu"],maxHops:1,mission:"attack"});var p=S.Systems.Army.deployIntercept(s,"kiyosu",e.stateChanges.armyId,[{officerId:"keiketsu",unitType:"ashigaru",troops:10}],{commanderId:"keiketsu",consumeCommand:false});return S.Systems.Army.resolveFieldContact(s,e.stateChanges.armyId,p.stateChanges.armyId,{allowTactical:false,random:function(){return 0.5;}}).stateChanges.report;}
  T.test("Phase11 DOM: 追撃選択に騎馬比率・予想損害・疲労を表示",function(){var s=fresh(),report=makePlayerWin(s);S.State.current=s;S.UI.showBattleReport(report);var html=S.UI.el("modalContent").innerHTML;T.assert(html.indexOf("追撃可能 / 効果")>=0);T.assert(html.indexOf("騎馬 100%")>=0);T.assert(html.indexOf("予想追加損害")>=0);T.assert(html.indexOf("総大将疲労")>=0);});
  T.test("Phase11 DOM: AI追撃結果を戦報に表示",function(){var s=fresh(),report=makeAIWin(s);S.State.current=s;S.UI.showBattleReport(report);var html=S.UI.el("modalContent").innerHTML;T.assert(report.pursuitByAI);T.assert(html.indexOf("敵軍の追撃判断")>=0);T.assert(html.indexOf("敵軍の追撃")>=0||html.indexOf("深追い")>=0);});
  T.run();
})(window.Sengoku,window.SengokuTest);
