"use strict";
var fs=require("fs"),path=require("path"),vm=require("vm"),root=path.resolve(__dirname,"..");
global.window=global;global.addEventListener=function(){};
var elements={};global.document={getElementById:function(id){return elements[id]||(elements[id]={innerHTML:"",value:"",classList:{add:function(){},remove:function(){},contains:function(){return false;}}});},body:{classList:{add:function(){},remove:function(){}}},activeElement:null};
global.localStorage={data:{},setItem:function(k,v){this.data[k]=String(v)},getItem:function(k){return this.data[k]||null},removeItem:function(k){delete this.data[k]}};
[
"src/namespace.js","src/config/constants.js","src/config/balance.js","src/data/factions.js","src/data/castles.js","src/data/castleTraits.js","src/data/officers.js","src/data/tactics.js","src/data/unitTypes.js","src/data/events.js","src/data/contentPacks.js","src/data/eventExtensions.js","src/data/difficulties.js","src/data/scenarios.js","src/data/diplomacy.js","src/state/schema.js","src/state/createInitialState.js","src/state/validateState.js","src/state/migrateState.js","src/systems/officerSystem.js","src/systems/unitSystem.js","src/systems/armySystem.js","src/systems/relationshipSystem.js","src/systems/loyaltySystem.js","src/systems/rivalrySystem.js","src/systems/eventSystem.js","src/systems/prisonerSystem.js","src/systems/diplomacySystem.js","src/systems/releaseSystem.js","src/systems/domesticSystem.js","src/systems/victorySystem.js","src/systems/siegeSystem.js","src/systems/battleSystem.js","src/systems/aiSystem.js","src/systems/turnSystem.js","src/systems/uxSystem.js","src/save/saveSystem.js","src/ui/dom.js","src/ui/renderArmy.js","src/ui/renderDiplomacy.js","src/ui/commandVisual.js"
].forEach(function(f){vm.runInThisContext(fs.readFileSync(path.join(root,f),"utf8"),{filename:f});});
var S=global.Sengoku,U=S.UI,opened="",opts=null,passes=0,total=0;U.openModal=function(html,o){opened=html;opts=o||{};};U.notify=function(m){throw new Error(m)};
function test(n,fn){total++;try{fn();passes++;console.log("PASS "+n)}catch(e){console.error("FAIL "+n+" — "+e.message);process.exitCode=1}}function ok(c,m){if(!c)throw new Error(m||"assert")}
S.State.current=S.State.createInitialState({scenarioId:"core_campaign",playerFactionId:"aotsuki"});S.State.current.campaign.status="playing";S.State.current.campaign.commands=3;
var own=Object.keys(S.State.current.castles).map(function(id){return S.State.current.castles[id]}).find(function(c){return c.factionId==="aotsuki"&&S.Systems.Army.reachableEnemyTargets(S.State.current,c.id,"aotsuki",{maxHops:3}).length>0&&c.guardTroops>S.Config.MIN_GARRISON+S.Config.MIN_ATTACK_FORCE});
test("出陣準備画面が軍団カードを描画",function(){ok(own,"侵攻可能な自城なし");opened="";U.showArmyPlanner(own.id);ok(/sv-deploy-screen/.test(opened));ok(/総大将/.test(opened));ok(/侵攻先・進軍路/.test(opened));ok(opts.modalClass==="strategic-visual-modal");});
test("外交一覧が勢力カードを描画",function(){opened="";U.showDiplomacy();ok(/sv-diplomacy-grid/.test(opened));ok((opened.match(/sv-diplomacy-card /g)||[]).length>=2);});
test("外交詳細が操作タイルを描画",function(){var target=Object.keys(S.State.current.factions).find(function(id){return id!=="aotsuki"});opened="";U.showDiplomacyDetail(target);ok(/sv-diplomacy-actions/.test(opened));ok(opened.indexOf("関係改善")>=0);ok(opened.indexOf("同盟")>=0);});
test("評定画面が4つの家臣進言を描画",function(){S.State.current.campaign.selectedCastleId=own?own.id:Object.keys(S.State.current.castles)[0];opened="";U.showCouncilVisual();ok(/sv-council-grid/.test(opened));["徴兵","偵察","出陣","商業投資"].forEach(function(x){ok(opened.indexOf(x)>=0,x)});});
console.log(passes+" / "+total+" PASS");if(passes!==total)process.exitCode=1;
