(function (S, T) {
  "use strict";
  function fresh(options) { return S.State.createInitialState(Object.assign({ scenarioId: "owari_short", playerFactionId: "aotsuki", difficultyId: "normal" }, options || {})); }
  function same(actual, expected, message) { T.equal(JSON.stringify(actual), JSON.stringify(expected), message); }
  function definition(id, choices, selectors) { return { id: id, trigger: S.Config.EVENT_TRIGGERS.DIPLOMACY_CHANGED, blocking: true, once: false, priority: 1, chance: 1, kicker: "TEST", title: id, body: "test", message: "test", conditions: [], selectors: selectors || {}, choices: choices }; }
  var testPack = { id: "phase2_test_pack", name: "Phase 2 Test Pack", version: "1.0.0", enabledByDefault: false, events: [
    definition("phase2_basic", [
      { id: "enabled", label: "実行", conditions: [{ type: "campaignResourceAtLeast", resource: "gold", amount: 10 }], costs: [{ type: "campaignResource", resource: "gold", amount: 10 }], resultText: "{{officer.name}}が実行", effects: [{ type: "campaignResource", resource: "food", operation: "add", amount: 5 }, { type: "setFlag", flag: "phase2Enabled", value: true }] },
      { id: "disabled", label: "高額", costs: [{ type: "campaignResource", resource: "gold", amount: 999 }], disabledReason: "資源不足のため選べません", resultText: "disabled", effects: [] },
      { id: "fallback", label: "見送る", fallback: true, resultText: "見送り", effects: [{ type: "addCounter", counter: "fallbacks", amount: 1 }] }
    ], { officer: { type: "randomOfficer", factionId: "aotsuki" } }),
    definition("phase2_second", [{ id: "ok", label: "次を解決", fallback: true, resultText: "二件目", effects: [] }]),
    definition("phase2_next", [{ id: "next", label: "次へ", fallback: true, resultText: "連鎖", effects: [], nextEventId: "phase2_second" }]),
    definition("phase2_atomic", [{ id: "bad", label: "失敗", fallback: true, resultText: "失敗", effects: [{ type: "campaignResource", resource: "gold", operation: "add", amount: 10 }, { type: "castleMorale", target: "missingCastle", operation: "add", amount: -5 }] }], { castle: { type: "castleById", id: "kiyosu" } }),
    definition("phase2_cycle", [{ id: "ok", label: "循環", fallback: true, resultText: "循環", effects: [] }], { a: { type: "officerById", id: "keiketsu" }, b: { type: "officerById", id: "soma" } }),
    definition("phase2_no_candidate", [{ id: "ok", label: "なし", fallback: true, resultText: "なし", effects: [] }], { officer: { type: "officerById", id: "missing" } }),
    definition("phase2_queue_effect", [{ id: "queue", label: "追加", fallback: true, resultText: "追加", effects: [{ type: "queueEvent", eventId: "phase2_second", payload: { chained: true } }] }])
  ] };
  var registered = S.Systems.Event.registerContentPack(testPack); if (!registered.ok) throw new Error(registered.errors.join(" / "));

  T.test("Phase 2: event instance IDとpayload snapshotが安定", function () { var state = fresh(), payload = { marker: { value: 7 } }, result = S.Systems.Event.queueEvent(state, "phase2_basic", payload, { random: function () { return 0; } }); T.assert(result.ok); var active = S.Systems.Event.getActiveEvent(state); T.equal(active.instanceId, "evt-1"); T.equal(active.eventId, "phase2_basic"); T.equal(active.packId, "phase2_test_pack"); T.equal(active.createdTurn, 0); payload.marker.value = 99; T.equal(active.payloadSnapshot.marker.value, 7); });
  T.test("Phase 2: selector結果は再描画で再抽選しない", function () { var state = fresh(), calls = 0, result = S.Systems.Event.queueEvent(state, "phase2_basic", {}, { random: function () { calls += 1; return 0.4; } }); T.assert(result.ok); var before = S.Systems.Event.getActiveEvent(state).targets.officer.id; S.Systems.Event.renderEvent(state, S.Systems.Event.getActiveEvent(state)); S.Systems.Event.renderEvent(state, S.Systems.Event.getActiveEvent(state)); T.equal(calls, 1); T.equal(S.Systems.Event.getActiveEvent(state).targets.officer.id, before); });
  T.test("Phase 2: selector依存循環を拒否", function () { var state = fresh(), result = S.Systems.Event.resolveSelectors(state, { selectors: { a: { type: "officerById", id: "keiketsu", dependsOn: ["b"] }, b: { type: "officerById", id: "soma", dependsOn: ["a"] } } }, {}); T.equal(result.ok, false); T.assert(result.errors.some(function (item) { return item.indexOf("cycle") >= 0; })); });
  T.test("Phase 2: selector候補なしではeventを作らない", function () { var state = fresh(), result = S.Systems.Event.queueEvent(state, "phase2_no_candidate", {}); T.equal(result.ok, false); T.equal(state.events.engine.activeEvent, null); });
  T.test("Phase 2: blocking queue順序と次event活性化", function () { var state = fresh(); T.assert(S.Systems.Event.queueEvent(state, "phase2_basic", {}, { random: function () { return 0; } }).ok); T.assert(S.Systems.Event.queueEvent(state, "phase2_second", {}).ok); T.equal(state.events.engine.activeEvent.eventId, "phase2_basic"); T.equal(state.events.engine.queue[0].eventId, "phase2_second"); T.assert(S.Systems.Event.resolveChoice(state, state.events.engine.activeEvent.instanceId, "fallback").ok); T.equal(state.events.engine.activeEvent.eventId, "phase2_second"); });
  T.test("Phase 2: active eventをsave/load復元", function () { var state = fresh(), key = "phase2_active_restore"; S.Systems.Event.queueEvent(state, "phase2_basic", {}, { random: function () { return 0; } }); var id = state.events.engine.activeEvent.instanceId; T.assert(S.Save.save(state, key).ok); var loaded = S.Save.load(key); T.assert(loaded.ok, loaded.errors && loaded.errors.join(" / ")); T.equal(loaded.state.events.engine.activeEvent.instanceId, id); T.equal(loaded.state.events.engine.activeEvent.targets.officer.id, state.events.engine.activeEvent.targets.officer.id); S.Save.remove(key); });
  T.test("Phase 2: duplicate instanceを防止", function () { var state = fresh(), first = S.Systems.Event.queueEvent(state, "phase2_second", { key: 1 }), second = S.Systems.Event.queueEvent(state, "phase2_second", { key: 1 }); T.assert(first.ok); T.assert(second.duplicate); T.equal(state.events.engine.queue.length, 0); T.equal(state.events.engine.activeEvent.instanceId, first.instance.instanceId); });
  T.test("Phase 2: queue上限50件", function () { var state = fresh(); for (var i = 0; i < 51; i += 1) T.assert(S.Systems.Event.queueEvent(state, "phase2_second", { index: i }).ok); var overflow = S.Systems.Event.queueEvent(state, "phase2_second", { index: 51 }); T.equal(state.events.engine.queue.length, 50); T.equal(overflow.ok, false); });
  T.test("Phase 2: templateをHTML escape", function () { var state = fresh(); state.officers.keiketsu.name = "<img src=x onerror=alert(1)>"; S.Systems.Event.queueEvent(state, "phase2_basic", {}, { random: function () { return 0; } }); var instance = state.events.engine.activeEvent, text = S.Systems.Event.renderTemplate(state, instance, "{{officer.name}}", {}); T.assert(text.indexOf("&lt;img") >= 0); T.equal(text.indexOf("<img"), -1); });
  T.test("Phase 2: template欠損参照はdiagnostic", function () { var state = fresh(); S.Systems.Event.queueEvent(state, "phase2_second", {}); var text = S.Systems.Event.renderTemplate(state, state.events.engine.activeEvent, "前{{missing.name}}後", {}); T.equal(text, "前後"); T.assert(state.events.engine.diagnostics.some(function (item) { return item.code === "template_missing"; })); });
  T.test("Phase 2: enabledとdisabled choiceと理由", function () { var state = fresh(); S.Systems.Event.queueEvent(state, "phase2_basic", {}, { random: function () { return 0; } }); var views = S.Systems.Event.choiceViews(state, state.events.engine.activeEvent); T.equal(views[0].enabled, true); T.equal(views[1].enabled, false); T.equal(views[1].disabledReason, "資源不足のため選べません"); });
  T.test("Phase 2: cost不足を再検証して拒否", function () { var state = fresh(); state.campaign.gold = 5; S.Systems.Event.queueEvent(state, "phase2_basic", {}, { random: function () { return 0; } }); var id = state.events.engine.activeEvent.instanceId, before = state.campaign.gold, result = S.Systems.Event.resolveChoice(state, id, "enabled"); T.equal(result.ok, false); T.equal(state.campaign.gold, before); T.equal(state.events.engine.activeEvent.instanceId, id); });
  T.test("Phase 2: choice costとeffectsをcommit", function () { var state = fresh(); S.Systems.Event.queueEvent(state, "phase2_basic", {}, { random: function () { return 0; } }); var gold = state.campaign.gold, food = state.campaign.food, result = S.Systems.Event.resolveChoice(state, state.events.engine.activeEvent.instanceId, "enabled"); T.assert(result.ok, result.errors && result.errors.join(" / ")); T.equal(state.campaign.gold, gold - 10); T.equal(state.campaign.food, food + 5); T.equal(state.events.flags.phase2Enabled, true); });
  T.test("Phase 2: atomic effect失敗は完全rollback", function () { var state = fresh(); S.Systems.Event.queueEvent(state, "phase2_atomic", {}); var id = state.events.engine.activeEvent.instanceId, snapshot = { gold: state.campaign.gold, log: JSON.stringify(state.events.log), history: state.events.engine.history.length }, result = S.Systems.Event.resolveChoice(state, id, "bad"); T.equal(result.ok, false); T.equal(state.campaign.gold, snapshot.gold); T.equal(JSON.stringify(state.events.log), snapshot.log); T.equal(state.events.engine.history.length, snapshot.history); T.equal(state.events.engine.activeEvent.instanceId, id); });
  T.test("Phase 2: duplicate choice実行を防止", function () { var state = fresh(); S.Systems.Event.queueEvent(state, "phase2_second", {}); var id = state.events.engine.activeEvent.instanceId; T.assert(S.Systems.Event.resolveChoice(state, id, "ok").ok); var second = S.Systems.Event.resolveChoice(state, id, "ok"); T.equal(second.ok, false); T.equal(state.events.engine.history.filter(function (entry) { return entry.instanceId === id; }).length, 1); });
  T.test("Phase 2: fallback choice", function () { var state = fresh(); S.Systems.Event.queueEvent(state, "phase2_basic", {}, { random: function () { return 0; } }); var result = S.Systems.Event.resolveChoice(state, state.events.engine.activeEvent.instanceId, null); T.assert(result.ok); T.equal(result.stateChanges.choiceId, "fallback"); T.equal(state.events.engine.counters.fallbacks, 1); });
  T.test("Phase 2: nextEventIdで次eventをactive化", function () { var state = fresh(); S.Systems.Event.queueEvent(state, "phase2_next", {}); T.assert(S.Systems.Event.resolveChoice(state, state.events.engine.activeEvent.instanceId, "next").ok); T.equal(state.events.engine.activeEvent.eventId, "phase2_second"); });
  T.test("Phase 2: queueEvent effect", function () { var state = fresh(); S.Systems.Event.queueEvent(state, "phase2_queue_effect", {}); T.assert(S.Systems.Event.resolveChoice(state, state.events.engine.activeEvent.instanceId, "queue").ok); T.equal(state.events.engine.activeEvent.eventId, "phase2_second"); });
  T.test("Phase 2: season event regression", function () { var state = fresh(), before = state.campaign.food; state.campaign.season = 2; var result = S.Systems.Event.emit(state, S.Config.EVENT_TRIGGERS.SEASON_START, {}, { random: function () { return 0; } }); T.assert(result.ok, result.errors.join(" / ")); T.equal(state.campaign.food, before + 23); T.assert(state.events.engine.history.some(function (entry) { return entry.eventId === "autumn_harvest" && entry.status === "resolved"; })); });
  T.test("Phase 2: opening council三択", function () { ["standard", "night", "assault"].forEach(function (choiceId) { var state = fresh(); T.assert(S.Systems.Campaign.begin(state).ok); var active = state.events.engine.activeEvent; same(active.availableChoices.map(function (choice) { return choice.id; }), ["standard", "night", "assault"]); var result = S.Systems.Event.resolveChoice(state, active.instanceId, choiceId); T.assert(result.ok, result.errors && result.errors.join(" / ")); T.equal(state.events.engine.pendingInteraction.preset.tacticId, choiceId); }); });
  T.test("Phase 2: battle planner interaction", function () { var state = fresh(); S.Systems.Campaign.begin(state); var result = S.Systems.Event.resolveChoice(state, state.events.engine.activeEvent.instanceId, "night"); T.assert(result.ok); var interaction = S.Systems.Event.getPendingInteraction(state); T.equal(interaction.type, "requestBattlePlanner"); T.equal(interaction.sourceId, "kiyosu"); T.equal(interaction.targetId, "narumi"); T.equal(interaction.preset.commanderId, "soma"); T.assert(S.Systems.Event.completeInteraction(state, "requestBattlePlanner").ok); T.equal(state.events.engine.pendingInteraction, null); });
  T.test("Phase 2: event historyに選択と結果", function () { var state = fresh(); S.Systems.Event.queueEvent(state, "phase2_second", {}); var id = state.events.engine.activeEvent.instanceId; S.Systems.Event.resolveChoice(state, id, "ok"); var entry = state.events.engine.history[0]; T.equal(entry.eventId, "phase2_second"); T.equal(entry.packId, "phase2_test_pack"); T.equal(entry.selectedChoiceId, "ok"); T.equal(entry.result, "二件目"); T.equal(entry.status, "resolved"); });
  T.test("Phase 2: 消失定義のinstanceを安全取消", function () { var state = fresh(), pack = S.Data.ContentPackRegistry.packs.phase2_test_pack, index = pack.events.findIndex(function (item) { return item.id === "phase2_second"; }); S.Systems.Event.queueEvent(state, "phase2_second", {}); var removed = pack.events.splice(index, 1)[0], result = S.Systems.Event.reconcileInstances(state); T.equal(result.stateChanges.cancelledInstanceIds.length, 1); T.equal(state.events.engine.activeEvent, null); T.assert(state.events.engine.diagnostics.some(function (item) { return item.code === "event_definition_missing"; })); pack.events.splice(index, 0, removed); T.assert(S.Systems.Event.compileTriggerIndex().ok); });

  T.run();
})(window.Sengoku, window.SengokuTest);
