(function (S, T) {
  "use strict";
  function fresh(options) { return S.State.createInitialState(Object.assign({ scenarioId: "core_campaign", playerFactionId: "aotsuki", difficultyId: "normal", eventSeed: 123 }, options || {})); }
  function event(id, choices, selectors) { return { id: id, trigger: S.Config.EVENT_TRIGGERS.DIPLOMACY_CHANGED, blocking: true, once: false, priority: 1, chance: 1, title: id, body: "Phase 3 test", conditions: [], selectors: selectors || {}, choices: choices }; }
  function choice(id, effects) { return { id: id, label: id, fallback: true, aiWeight: 1, resultText: id + " result", effects: effects || [] }; }
  function same(a, b, message) { T.equal(JSON.stringify(a), JSON.stringify(b), message); }
  var arc = { id: "phase3_arc", name: "Verification Arc", description: "Temporary verification only", startEventId: "phase3_simple", initialStep: "one", steps: { one: { nextStep: "two" }, two: {} }, completionConditions: [], failureConditions: [] };
  var events = [
    event("phase3_simple", [choice("ok", [])]),
    event("phase3_ai", [
      { id: "disabled", label: "disabled", aiWeight: 999, conditions: [{ type: "resource", resource: "gold", operator: ">", value: 99999 }], resultText: "bad", effects: [] },
      { id: "costly", label: "costly", aiWeight: 999, costs: [{ type: "campaignResource", resource: "gold", amount: 99999 }], resultText: "bad", effects: [] },
      { id: "normal", label: "normal", aiWeight: 3, resultText: "normal", effects: [{ type: "addCounter", counter: "aiNormal", amount: 1 }] },
      { id: "fallback", label: "fallback", fallback: true, aiWeight: 0, resultText: "fallback", effects: [{ type: "addCounter", counter: "aiFallback", amount: 1 }] }
    ], { faction: { type: "factionById", id: "tokizawa" }, officer: { type: "officerById", id: "takama" } }),
    Object.assign(event("phase3_fallback", [
      { id: "normal", label: "normal", aiWeight: 1, conditions: [{ type: "eventFlag", flag: "never", operator: "==", value: true }], resultText: "bad", effects: [] },
      choice("fallback", [{ type: "addCounter", counter: "aiFallback", amount: 1 }])
    ], { faction: { type: "factionById", id: "tokizawa" } }), { fallbackChoiceId: "fallback" }),
    event("phase3_state_effects", [choice("apply", [
      { type: "setFlag", flag: "p3", value: true }, { type: "setVariable", variable: "v", value: 2 }, { type: "addVariable", variable: "v", amount: 3 },
      { type: "setCounter", counter: "c", value: 4 }, { type: "addCounter", counter: "c", amount: 2 }, { type: "setCooldown", cooldown: "cd", duration: 4 },
      { type: "campaignResource", resource: "gold", operation: "add", amount: 5 }, { type: "restoreCommand", amount: 1 }
    ])]),
    event("phase3_entity_effects", [choice("apply", [
      { type: "factionResource", factionTarget: "faction", resource: "gold", operation: "add", amount: 4 },
      { type: "factionReputation", factionTarget: "faction", amount: 1 }, { type: "warExhaustion", factionTarget: "faction", amount: 2 },
      { type: "castleTroops", castleTarget: "castle", amount: 3 }, { type: "castleDefense", castleTarget: "castle", amount: 1 },
      { type: "officerStat", officerTarget: "officer", stat: "politics", amount: 1 }, { type: "officerLoyalty", officerTarget: "officer", amount: 1 },
      { type: "officerMerit", officerTarget: "officer", amount: 2 }, { type: "officerAddTag", officerTarget: "officer", tag: "phase3" }
    ])], { faction: { type: "factionById", id: "tokizawa" }, castle: { type: "castleById", id: "suemori" }, officer: { type: "officerById", id: "takama" } }),
    event("phase3_relation_effects", [choice("apply", [
      { type: "officerRelationship", aId: "keiketsu", bId: "soma", amount: 2 },
      { type: "addRelationshipMemory", aId: "keiketsu", bId: "soma", text: "共同検証" },
      { type: "rivalryRespect", aId: "keiketsu", bId: "hiyori", amount: 2 }, { type: "rivalryEncounter", aId: "keiketsu", bId: "hiyori", amount: 1 },
      { type: "addOfficerHistory", officerId: "keiketsu", text: "履歴検証" }, { type: "addDiplomacyHistory", aId: "aotsuki", bId: "tokizawa", text: "外交履歴検証" },
      { type: "addBattleMemory", officerId: "keiketsu", text: "合戦記憶検証" }
    ])]),
    event("phase3_arc_effects", [choice("apply", [{ type: "startArc", arcId: "phase3_arc" }, { type: "advanceArc", arcId: "phase3_arc" }, { type: "completeArc", arcId: "phase3_arc" }])]),
    event("phase3_late_failure", [choice("bad", [
      { type: "addCounter", counter: "late", amount: 1 }, { type: "addCounter", counter: "late", amount: 1 }, { type: "addCounter", counter: "late", amount: 1 },
      { type: "addCounter", counter: "late", amount: 1 }, { type: "addCounter", counter: "late", amount: 1 }, { type: "addCounter", counter: "late", amount: 1 },
      { type: "addCounter", counter: "late", amount: 1 }, { type: "addLog", text: "must rollback" }, { type: "officerMove", officerId: "missing", targetCastleId: "kiyosu" },
      { type: "addCounter", counter: "late", amount: 1 }
    ])])
  ];
  var pack = { id: "phase3_test_pack", name: "Phase 3 Test Pack", version: "1.0.0", enabledByDefault: false, events: events, arcs: [arc] };
  var registration = S.Systems.Event.registerContentPack(pack); if (!registration.ok) throw new Error(registration.errors.join(" / "));

  T.test("Phase 3: empty personality and trait registries", function () { T.equal(Object.keys(S.Data.PersonalityRegistry.definitions).length, 0); T.equal(Object.keys(S.Data.TraitRegistry.definitions).length, 0); same(fresh().officers.keiketsu.profile, { personalityIds: [], traitIds: [], tags: [] }); });
  T.test("Phase 3: profile add remove and unknown rejection", function () { var state = fresh(); S.Data.PersonalityRegistry.definitions.test_personality = { id: "test_personality" }; S.Data.TraitRegistry.definitions.test_trait = { id: "test_trait" }; T.assert(S.Systems.Event.Profile.addPersonality(state, "keiketsu", "test_personality").ok); T.assert(S.Systems.Event.Profile.addTrait(state, "keiketsu", "test_trait").ok); T.assert(S.Systems.Event.Profile.addTag(state, "keiketsu", "tagged").ok); T.equal(S.Systems.Event.Profile.addTrait(state, "keiketsu", "unknown").ok, false); T.assert(S.Systems.Event.Profile.removePersonality(state, "keiketsu", "test_personality").ok); T.assert(S.Systems.Event.Profile.removeTrait(state, "keiketsu", "test_trait").ok); T.assert(S.Systems.Event.Profile.removeTag(state, "keiketsu", "tagged").ok); });
  T.test("Phase 3: personality and trait conditions", function () { var state = fresh(), instance = { targets: { officer: { type: "officer", id: "keiketsu" } } }; S.Systems.Event.Profile.addPersonality(state, "keiketsu", "test_personality"); S.Systems.Event.Profile.addTrait(state, "keiketsu", "test_trait"); T.assert(S.Systems.Event.evaluateConditions(state, [{ type: "officerPersonality", target: "officer", operator: "includes", value: "test_personality" }, { type: "officerTrait", target: "officer", operator: "includes", value: "test_trait" }], instance).ok); });
  T.test("Phase 3: AI selects only available and respects costs", function () { var state = fresh(), queued = S.Systems.Event.queueEvent(state, "phase3_ai", {}, { random: function () { return 0; } }); T.assert(queued.ok); var result = S.Systems.Event.resolveAIChoice(state, queued.instance.instanceId, { random: function () { return 0; } }); T.assert(result.ok, result.errors && result.errors.join(" / ")); T.equal(result.stateChanges.choiceId, "normal"); T.equal(state.events.engine.activeEvent, null); T.equal(state.events.engine.counters.aiNormal, 1); });
  T.test("Phase 3: AI fallback choice", function () { var state = fresh(), queued = S.Systems.Event.queueEvent(state, "phase3_fallback", {}); var result = S.Systems.Event.resolveAIChoice(state, queued.instance.instanceId, { random: function () { return 0.9; } }); T.assert(result.ok); T.equal(result.stateChanges.choiceId, "fallback"); });
  T.test("Phase 3: deterministic AI choice", function () { function run() { var state = fresh(), queued = S.Systems.Event.queueEvent(state, "phase3_ai", {}), rng = S.Systems.Event.createDeterministicRng(987); return S.Systems.Event.resolveAIChoice(state, queued.instance.instanceId, { random: rng }).stateChanges.choiceId; } T.equal(run(), run()); });
  T.test("Phase 3: AI modifiers tolerate empty definitions", function () { var state = fresh(), queued = S.Systems.Event.queueEvent(state, "phase3_ai", {}); T.assert(S.Systems.Event.resolveAIChoice(state, queued.instance.instanceId, { random: function () { return 0.4; } }).ok); });
  T.test("Phase 3: arc start and duplicate rejection", function () { var state = fresh(); T.assert(S.Systems.Event.Arc.start(state, "phase3_arc").ok); T.equal(S.Systems.Event.Arc.start(state, "phase3_arc").ok, false); T.equal(state.events.engine.arcs.phase3_arc.status, "active"); });
  T.test("Phase 3: arc advance and completion", function () { var state = fresh(); S.Systems.Event.Arc.start(state, "phase3_arc"); T.assert(S.Systems.Event.Arc.advance(state, "phase3_arc").ok); T.equal(state.events.engine.arcs.phase3_arc.currentStep, "two"); T.assert(S.Systems.Event.Arc.advance(state, "phase3_arc").ok); T.equal(state.events.engine.arcs.phase3_arc.status, "completed"); T.equal(S.Systems.Event.Arc.advance(state, "phase3_arc").ok, false); });
  T.test("Phase 3: arc failure and invalid step", function () { var state = fresh(); S.Systems.Event.Arc.start(state, "phase3_arc"); T.equal(S.Systems.Event.Arc.setStep(state, "phase3_arc", "missing").ok, false); T.assert(S.Systems.Event.Arc.fail(state, "phase3_arc").ok); T.equal(state.events.engine.arcs.phase3_arc.status, "failed"); });
  T.test("Phase 3: arc cycle rejection", function () { var bad = { id: "bad_arc", name: "bad", description: "bad", startEventId: "phase3_simple", initialStep: "a", steps: { a: { nextStep: "b" }, b: { nextStep: "a" } }, completionConditions: [], failureConditions: [] }; T.equal(S.Systems.Event.Arc.register(bad, "phase3_test_pack").ok, false); });
  T.test("Phase 3: arc save load", function () { var state = fresh(), key = "phase3_arc_save"; S.Systems.Event.Arc.start(state, "phase3_arc"); S.Systems.Event.Arc.advance(state, "phase3_arc"); T.assert(S.Save.save(state, key).ok); var loaded = S.Save.load(key); T.assert(loaded.ok, loaded.errors && loaded.errors.join(" / ")); T.equal(loaded.state.events.engine.arcs.phase3_arc.currentStep, "two"); S.Save.remove(key); });
  T.test("Phase 3: logical campaign faction conditions", function () { var state = fresh(), instance = { targets: { faction: { type: "faction", id: "aotsuki" } } }, conditions = [{ type: "all", conditions: [{ type: "scenario", value: "core_campaign" }, { type: "difficulty", value: "normal" }, { type: "turn", operator: ">=", value: 0 }, { type: "year", value: 1 }, { type: "season", operator: "between", value: [0, 3] }, { type: "resource", resource: "gold", operator: ">", value: 0 }] }, { type: "factionAlive", target: "faction", value: true }, { type: "factionCastleCount", target: "faction", operator: ">=", value: 1 }, { type: "factionTotalTroops", target: "faction", operator: ">", value: 0 }, { type: "factionRank", target: "faction", operator: ">=", value: 1 }, { type: "factionIsPlayer", target: "faction", value: true }, { type: "factionVassalStatus", target: "faction", value: "independent" }, { type: "not", condition: { type: "factionAlive", factionId: "missing", value: true } }]; T.assert(S.Systems.Event.evaluateConditions(state, conditions, instance).ok); });
  T.test("Phase 3: castle officer relationship conditions", function () { var state = fresh(), instance = { targets: { castle: { type: "castle", id: "kiyosu" }, officer: { type: "officer", id: "keiketsu" } } }; S.Systems.Rivalry.get(state, "keiketsu", "hiyori", true).respect = 4; var conditions = [{ type: "castleOwner", target: "castle", value: "aotsuki" }, { type: "castleTroops", target: "castle", operator: ">", value: 0 }, { type: "castleNeighbor", target: "castle", operator: "includes", value: "narumi" }, { type: "castleGovernor", target: "castle", operator: "exists" }, { type: "officerStatus", target: "officer", value: "active" }, { type: "officerStat", target: "officer", stat: "leadership", operator: ">", value: 0 }, { type: "officerLoyalty", target: "officer", operator: ">", value: 0 }, { type: "officerTag", target: "officer", operator: "notIncludes", value: "none" }, { type: "officerRelationship", aId: "keiketsu", bId: "soma", operator: ">", value: 0 }, { type: "rivalryRespect", aId: "keiketsu", bId: "hiyori", value: 4 }]; T.assert(S.Systems.Event.evaluateConditions(state, conditions, instance).ok); });
  T.test("Phase 3: diplomacy and event conditions", function () { var state = fresh(); state.events.flags.flag = true; state.events.engine.variables.x = 3; state.events.engine.counters.c = 2; state.events.engine.firedEventIds.phase3_simple = 1; state.events.engine.cooldowns.cd = 5; S.Systems.Event.Arc.start(state, "phase3_arc"); var conditions = [{ type: "diplomacyStatus", aId: "aotsuki", bId: "tokizawa", value: "war" }, { type: "diplomacyScore", aId: "aotsuki", bId: "tokizawa", operator: ">=", value: 0 }, { type: "diplomacyCommonEnemy", aId: "aotsuki", bId: "tokizawa", value: false }, { type: "eventFlag", flag: "flag", value: true }, { type: "eventVariable", variable: "x", value: 3 }, { type: "eventCounter", counter: "c", value: 2 }, { type: "eventFired", eventId: "phase3_simple", value: true }, { type: "arcStatus", arcId: "phase3_arc", value: "active" }, { type: "arcStep", arcId: "phase3_arc", value: "one" }, { type: "eventCooldown", cooldown: "cd", value: 5 }]; T.assert(S.Systems.Event.evaluateConditions(state, conditions, null).ok); });
  T.test("Phase 3: every selector type resolves or safely returns empty", function () { var state = fresh(); state.events.battleReports.push({ result: "攻撃側勝利", attackerFactionId: "aotsuki", targetId: "narumi" }); S.Systems.Prisoner.capture(state, "hiyori", "aotsuki"); var definitions = { faction: { type: "factionById", id: "aotsuki" }, castle: { type: "castleById", id: "kiyosu" }, officer: { type: "highestStatOfficer", factionId: "aotsuki", stat: "leadership" }, low: { type: "lowestLoyaltyOfficer", factionId: "aotsuki" }, grievance: { type: "highestGrievanceOfficer", factionId: "aotsuki" }, governor: { type: "castleGovernor", castleId: "kiyosu" }, prisoner: { type: "randomPrisoner" }, randomCastle: { type: "randomFactionCastle", factionId: "aotsuki" }, border: { type: "weakestBorderCastle", factionId: "aotsuki" }, strongCastle: { type: "strongestCastle", factionId: "aotsuki" }, recent: { type: "recentlyCapturedCastle", factionId: "aotsuki" }, strongest: { type: "strongestFaction" }, weakest: { type: "weakestFaction" }, enemy: { type: "randomEnemyFaction", factionId: "aotsuki" }, partner: { type: "diplomaticPartner", factionId: "aotsuki", status: "war" } }; var result = S.Systems.Event.resolveSelectors(state, { selectors: definitions }, {}, function () { return 0; }); T.assert(result.ok, result.errors.join(" / ")); T.equal(result.targets.recent.id, "narumi"); });
  T.test("Phase 3: selector dependency cycle", function () { var state = fresh(), result = S.Systems.Event.resolveSelectors(state, { selectors: { a: { type: "officerById", id: "keiketsu", dependsOn: ["b"] }, b: { type: "officerById", id: "soma", dependsOn: ["a"] } } }, {}); T.equal(result.ok, false); });
  T.test("Phase 3: state effects", function () { var state = fresh(); state.campaign.commands = state.campaign.maxCommands - 1; var gold = state.campaign.gold; S.Systems.Event.queueEvent(state, "phase3_state_effects", {}); var result = S.Systems.Event.resolveChoice(state, state.events.engine.activeEvent.instanceId, "apply"); T.assert(result.ok, result.errors && result.errors.join(" / ")); T.equal(state.events.flags.p3, true); T.equal(state.events.engine.variables.v, 5); T.equal(state.events.engine.counters.c, 6); T.equal(state.events.engine.cooldowns.cd, state.campaign.turn + 4); T.equal(state.campaign.gold, gold + 5); T.equal(state.campaign.commands, state.campaign.maxCommands); });
  T.test("Phase 3: faction castle officer effects", function () { var state = fresh(), gold = state.factions.tokizawa.gold, troops = state.castles.suemori.troops; S.Systems.Event.queueEvent(state, "phase3_entity_effects", {}); var result = S.Systems.Event.resolveChoice(state, state.events.engine.activeEvent.instanceId, "apply"); T.assert(result.ok, result.errors && result.errors.join(" / ")); T.equal(state.factions.tokizawa.gold, gold + 4); T.equal(state.castles.suemori.troops, troops + 3); T.assert(state.officers.takama.profile.tags.indexOf("phase3") >= 0); });
  T.test("Phase 3: relationship rivalry and record effects", function () { var state = fresh(), before = S.Systems.Relationship.value(state, "keiketsu", "soma"); S.Systems.Event.queueEvent(state, "phase3_relation_effects", {}); var result = S.Systems.Event.resolveChoice(state, state.events.engine.activeEvent.instanceId, "apply"); T.assert(result.ok, result.errors && result.errors.join(" / ")); T.equal(S.Systems.Relationship.value(state, "keiketsu", "soma"), before + 2); T.equal(S.Systems.Rivalry.get(state, "keiketsu", "hiyori", false).encounters, 1); T.assert(state.diplomacy.history.some(function (item) { return item.text === "外交履歴検証"; })); });
  T.test("Phase 3: arc effects", function () { var state = fresh(); S.Systems.Event.queueEvent(state, "phase3_arc_effects", {}); var result = S.Systems.Event.resolveChoice(state, state.events.engine.activeEvent.instanceId, "apply"); T.assert(result.ok, result.errors && result.errors.join(" / ")); T.equal(state.events.engine.arcs.phase3_arc.status, "completed"); });
  T.test("Phase 3: every required effect type is registered", function () { var required = "setFlag clearFlag setVariable addVariable setCounter addCounter setCooldown clearCooldown queueEvent cancelEvent campaignResource consumeCommand restoreCommand factionResource factionReputation warExhaustion castleTroops castleMorale castleDefense castleDevelopment castleOwner officerStat officerLoyalty officerGrievance officerLordTrust officerMerit officerExperience officerInjury officerRecover officerMove officerAppointGovernor officerStatus officerAddPersonality officerRemovePersonality officerAddTrait officerRemoveTrait officerAddTag officerRemoveTag officerPromise officerRelationship addRelationshipMemory rivalryRespect rivalryResentment rivalryEncounter releasePrisoner recruitPrisoner exchangePrisoner diplomacyScore diplomacyTrust diplomacyGrievance declareWar makePeace createCeasefire createNonAggression createAlliance breakTreaty createVassalage releaseVassal addLog addChronicle addOfficerHistory addDiplomacyHistory addBattleMemory startArc advanceArc setArcStep completeArc failArc requestBattlePlanner requestOfficerSelection requestCastleSelection requestFactionSelection".split(" "); required.forEach(function (type) { T.assert(S.Systems.Event.EFFECT_TYPES.indexOf(type) >= 0, type); }); });
  T.test("Phase 3: late failure rolls back 10-effect transaction", function () { var state = fresh(); S.Systems.Event.queueEvent(state, "phase3_late_failure", {}); var id = state.events.engine.activeEvent.instanceId, log = JSON.stringify(state.events.log), history = state.events.engine.history.length, result = S.Systems.Event.resolveChoice(state, id, "bad"); T.equal(result.ok, false); T.equal(state.events.engine.counters.late, undefined); T.equal(JSON.stringify(state.events.log), log); T.equal(state.events.engine.history.length, history); T.equal(state.events.engine.activeEvent.instanceId, id); });
  T.test("Phase 3: direct and indirect event cycles rejected", function () { var selfPack = { id: "self_cycle_pack", name: "self", version: "1", events: [event("self_cycle", [{ id: "x", label: "x", fallback: true, nextEventId: "self_cycle", effects: [] }])] }; T.equal(S.Systems.Event.registerContentPack(selfPack).ok, false); var indirect = { id: "indirect_cycle_pack", name: "indirect", version: "1", events: [event("cycle_a", [{ id: "x", label: "x", fallback: true, nextEventId: "cycle_b", effects: [] }]), event("cycle_b", [{ id: "x", label: "x", fallback: true, nextEventId: "cycle_a", effects: [] }])] }; T.equal(S.Systems.Event.registerContentPack(indirect).ok, false); });
  T.test("Phase 3: chain depth 12 accepted and 13 rejected", function () { var chainEvents = [], i; for (i = 1; i <= 13; i += 1) chainEvents.push(event("chain_" + i, [{ id: "next", label: "next", fallback: true, resultText: "next", effects: [], nextEventId: i < 13 ? "chain_" + (i + 1) : undefined }])); var result = S.Systems.Event.registerContentPack({ id: "chain_pack", name: "chain", version: "1", events: chainEvents }); T.assert(result.ok, result.errors.join(" / ")); var state = fresh(); S.Systems.Event.queueEvent(state, "chain_1", {}); for (i = 1; i < 12; i += 1) T.assert(S.Systems.Event.resolveChoice(state, state.events.engine.activeEvent.instanceId, "next").ok, "step " + i); T.equal(state.events.engine.activeEvent.chainDepth, 12); var rejected = S.Systems.Event.resolveChoice(state, state.events.engine.activeEvent.instanceId, "next"); T.equal(rejected.ok, false); T.equal(state.events.engine.activeEvent.chainDepth, 12); });
  T.test("Phase 3: queue limit", function () { var state = fresh(); for (var i = 0; i < 51; i += 1) T.assert(S.Systems.Event.queueEvent(state, "phase3_simple", { n: i }).ok); T.equal(state.events.engine.queue.length, 50); T.equal(S.Systems.Event.queueEvent(state, "phase3_simple", { n: 51 }).ok, false); });
  T.test("Phase 3: history and diagnostics limits", function () { var state = fresh(); for (var i = 0; i < 510; i += 1) { S.Systems.Event.queueEvent(state, "phase3_simple", { n: i }); S.Systems.Event.resolveChoice(state, state.events.engine.activeEvent.instanceId, "ok"); } T.equal(state.events.engine.history.length, 500); for (i = 0; i < 210; i += 1) S.Systems.Event.addDiagnostic(state, "d" + i, "m" + i, null); T.equal(state.events.engine.diagnostics.length, 200); });
  T.test("Phase 3: unsafe text escaped and executable data rejected", function () { var state = fresh(); state.officers.keiketsu.name = "<script>alert(1)</script>"; var escaped = S.Systems.Event.renderTemplate(state, { targets: { officer: { type: "officer", id: "keiketsu" } } }, "{{officer.name}}", {}); T.assert(escaped.indexOf("&lt;script&gt;") >= 0); var unsafe = event("unsafe_function", [choice("x", [])]); unsafe.handler = function () {}; T.equal(S.Systems.Event.validateDefinition(unsafe).ok, false); var html = event("unsafe_html", [choice("x", [])]); html.body = "<b>bad</b>"; T.equal(S.Systems.Event.validateDefinition(html).ok, false); });
  T.test("Phase 3: unknown profile reference rejected by state validation", function () { var state = fresh(); state.officers.keiketsu.profile.traitIds.push("unknown_trait"); T.equal(S.State.validateState(state).ok, false); });

  T.run();
})(window.Sengoku, window.SengokuTest);
