(function (S, T) {
  "use strict";
  function fresh(options) { return S.State.createInitialState(options); }
  function campaign(playerFactionId, difficultyId) { return fresh({ scenarioId: "core_campaign", playerFactionId: playerFactionId || "aotsuki", difficultyId: difficultyId || "normal" }); }
  function rng(seed) { return function () { seed = (seed * 1664525 + 1013904223) >>> 0; return seed / 4294967296; }; }
  function assertClean(state) {
    var validation = S.State.validateState(state), governors = {};
    T.assert(validation.ok, validation.errors.join(" / "));
    Object.keys(state.castles).forEach(function (id) { var castle = state.castles[id]; T.assert(Number.isFinite(castle.troops) && castle.troops >= 0, "兵力が不正: " + id); if (castle.governorId) { T.assert(!governors[castle.governorId], "城主重複: " + castle.governorId); governors[castle.governorId] = true; } });
    (function inspect(value, path) { if (typeof value === "number") T.assert(Number.isFinite(value), "NaN/Infinity: " + path); else if (value && typeof value === "object") Object.keys(value).forEach(function (key) { inspect(value[key], path + "." + key); }); })(state, "state");
  }
  function battlePlan(state, overrides) {
    return Object.assign({ sourceId: "kiyosu", targetId: "narumi", commanderId: "keiketsu", deputyId: "soma", tacticId: "standard", decisionId: "trust", committedTroops: 40, attackerFactionId: "aotsuki", defenderFactionId: "tokizawa" }, overrides || {});
  }
  function asV08(state) { var old = S.Util.deepClone(state); old.schemaVersion = 8; old.gameVersion = "core-0.8"; old.diplomacy = { relations: S.Util.deepClone(old.relationships.officers) }; delete old.relationships; return old; }

  /* Core v0.7から維持する13テスト。 */
  T.test("初期状態生成", function () { var state = fresh(); T.equal(state.schemaVersion, 12); T.equal(Object.keys(state.castles).length, 4); T.equal(Object.keys(state.officers).length, 6); });
  T.test("スキーマ検証", function () { var result = S.State.validateState(fresh()); T.assert(result.ok, result.errors.join(" / ")); });
  T.test("新規ゲーム", function () { var state = fresh(), result = S.Systems.Campaign.begin(state); T.assert(result.ok); T.equal(state.campaign.status, "opening"); });
  T.test("季節進行", function () { var state = fresh(), before = state.campaign.season, result = S.Systems.Turn.advance(state, { skipAI: true, random: function () { return 0.9; } }); T.assert(result.ok); T.equal(state.campaign.season, before + 1); T.equal(state.campaign.commands, state.campaign.maxCommands); });
  T.test("内政命令", function () { var state = fresh(), before = state.castles.kiyosu.income, result = S.Systems.Domestic.executeDevelopment(state, "kiyosu", "soma"); T.assert(result.ok, result.errors && result.errors.join(" / ")); T.assert(state.castles.kiyosu.income > before); T.equal(state.campaign.gold, 105); });
  T.test("徴兵", function () { var state = fresh(), before = state.castles.kiyosu.troops, result = S.Systems.Domestic.executeRecruitment(state, "kiyosu", "keiketsu"); T.assert(result.ok); T.assert(state.castles.kiyosu.troops > before); });
  T.test("合戦による城所有権変更", function () { var state = fresh(), start = S.Systems.Battle.start(state, battlePlan(state)); T.assert(start.ok, start.errors && start.errors.join(" / ")); var result = S.Systems.Battle.resolve(state, { forceWin: true, random: function () { return 0.99; } }); T.assert(result.ok); T.equal(state.castles.narumi.factionId, "aotsuki"); });
  T.test("捕虜処理", function () { var state = fresh(), captured = S.Systems.Prisoner.capture(state, "hiyori", "aotsuki"); T.assert(captured.ok); T.assert(state.prisoners.indexOf("hiyori") >= 0); var released = S.Systems.Prisoner.release(state, "hiyori"); T.assert(released.ok); T.equal(state.officers.hiyori.status, "active"); });
  T.test("勢力滅亡", function () { var state = fresh(); Object.keys(state.castles).forEach(function (id) { if (state.castles[id].factionId === "tokizawa") state.castles[id].factionId = "aotsuki"; }); var eliminated = S.Systems.Victory.updateEliminations(state); T.assert(eliminated.indexOf("tokizawa") >= 0); T.equal(state.factions.tokizawa.alive, false); });
  T.test("勝利判定", function () { var state = fresh(); Object.keys(state.castles).forEach(function (id) { state.castles[id].factionId = "aotsuki"; state.castles[id].governorId = null; }); S.Systems.Victory.check(state); T.equal(state.campaign.outcome, "victory"); T.equal(state.campaign.gameOver, true); });
  T.test("セーブ・ロード一致", function () { var state = fresh(), key = "project_sengoku_core_test_temp"; state.campaign.gold = 777; var saved = S.Save.save(state, key); T.assert(saved.ok, saved.errors && saved.errors.join(" / ")); var loaded = S.Save.load(key); T.assert(loaded.ok, loaded.errors && loaded.errors.join(" / ")); T.equal(loaded.state.campaign.gold, 777); S.Save.remove(key); });
  T.test("不正セーブ拒否", function () { var invalid = fresh(); invalid.schemaVersion = 6; delete invalid.castles; var result = S.State.migrateState(invalid); T.equal(result.ok, false); });
  T.test("v0.6セーブ移行", function () { var state = fresh(), factionNumbers = { aotsuki: 0, tokizawa: 1, yukishiro: 2 }, legacy = { mode: "campaign", year: 2, season: 1, gold: 88, food: 77, commands: 1, maxCommands: 2, selectedCastleId: "kiyosu", turnCount: 5, castles: Object.keys(state.castles).map(function (id) { var castle = S.Util.deepClone(state.castles[id]); castle.owner = factionNumbers[castle.factionId]; delete castle.factionId; return castle; }), officers: Object.keys(state.officers).map(function (id) { var officer = S.Util.deepClone(state.officers[id]); officer.faction = factionNumbers[officer.factionId]; delete officer.factionId; return officer; }), prisoners: [], chronicle: [], log: [], relations: {}, rivalries: {} }; var result = S.State.migrateState(legacy); T.assert(result.ok, result.errors && result.errors.join(" / ")); T.equal(result.state.schemaVersion, 12); T.equal(result.state.campaign.gold, 88); T.equal(result.state.castles.kiyosu.factionId, "aotsuki"); });

  T.test("幽霊兵力防止: 実兵力超過を拒否", function () { var state = fresh(), before = state.castles.kiyosu.troops, result = S.Systems.Battle.plan(state, battlePlan(state, { committedTroops: before })); T.equal(result.ok, false); T.equal(state.events.pendingBattle, null); T.equal(state.castles.kiyosu.troops, before); });
  T.test("最低守備兵を残す", function () { var state = fresh(), max = S.Systems.Battle.maxCommit(state, "kiyosu"), started = S.Systems.Battle.plan(state, battlePlan(state, { committedTroops: max })); T.assert(started.ok); S.Systems.Battle.resolve(state, { forceWin: false, random: function () { return 0.5; } }); T.assert(state.castles.kiyosu.troops >= S.Config.MIN_GARRISON); });
  T.test("最低攻撃兵未満を拒否", function () { var state = fresh(), result = S.Systems.Battle.plan(state, battlePlan(state, { committedTroops: S.Config.MIN_ATTACK_FORCE - 1 })); T.equal(result.ok, false); });
  T.test("AIも幽霊兵力制約を共有", function () { var state = campaign(), source = state.castles.narumi; source.troops = S.Config.MIN_GARRISON + S.Config.MIN_ATTACK_FORCE - 1; T.equal(S.Systems.Battle.canAttack(state, source.id), false); T.equal(S.Systems.AI.attackCandidates(state, "tokizawa").some(function (item) { return item.source.id === source.id; }), false); });
  T.test("共通城主任命で重複防止", function () { var state = campaign(); T.assert(S.Systems.Officer.assignGovernor(state, "keiketsu", "kiyosu", { consumeCommand: false }).ok); T.assert(S.Systems.Officer.assignGovernor(state, "keiketsu", "aonohara", { consumeCommand: false }).ok); T.equal(state.castles.kiyosu.governorId, null); T.equal(state.castles.aonohara.governorId, "keiketsu"); });
  T.test("重複城主を厳格検証で検出", function () { var state = campaign(); state.castles.aonohara.governorId = "keiketsu"; state.officers.keiketsu.castleId = "aonohara"; var result = S.State.validateState(state); T.equal(result.ok, false); T.assert(result.errors.some(function (text) { return text.indexOf("複数城") >= 0; })); });
  T.test("離反で旧城主解除と配属更新", function () { var state = campaign(); var result = S.Systems.Loyalty.defectOfficer(state, "keiketsu", "tokizawa"); T.assert(result.ok); T.equal(state.castles.kiyosu.governorId, null); T.equal(state.officers.keiketsu.factionId, "tokizawa"); T.equal(state.castles[state.officers.keiketsu.castleId].factionId, "tokizawa"); });
  T.test("離反記録を全系統へ保存", function () { var state = campaign(); S.Systems.Loyalty.defectOfficer(state, "keiketsu", "tokizawa"); T.assert(state.events.loyaltyEvents.some(function (item) { return item.officerId === "keiketsu" && item.type === "離反"; })); T.assert(state.chronicle.some(function (item) { return item.text.indexOf("離反") >= 0; })); T.assert(state.events.log.some(function (item) { return item.text.indexOf("離反") >= 0; })); T.assert(state.officers.keiketsu.history.some(function (item) { return item.text.indexOf("離反") >= 0; })); });
  T.test("離反後に元勢力参照が残らない", function () { var state = campaign(); S.Systems.Loyalty.defectOfficer(state, "keiketsu", "tokizawa"); T.equal(Object.keys(state.castles).some(function (id) { return state.castles[id].factionId === "aotsuki" && state.castles[id].governorId === "keiketsu"; }), false); T.assert(S.State.validateState(state).ok); });
  T.test("全城の隣接が双方向", function () { var state = campaign(); Object.keys(state.castles).forEach(function (id) { state.castles[id].neighbors.forEach(function (neighborId) { T.assert(state.castles[neighborId].neighbors.indexOf(id) >= 0, id + "<->" + neighborId); }); }); });
  T.test("片方向隣接を検出", function () { var state = campaign(); state.castles.narumi.neighbors = state.castles.narumi.neighbors.filter(function (id) { return id !== "kiyosu"; }); var result = S.State.validateState(state); T.equal(result.ok, false); T.assert(result.errors.some(function (text) { return text.indexOf("双方向") >= 0; })); });
  T.test("不正な城勢力参照を検出", function () { var state = campaign(); state.castles.kiyosu.factionId = "missing"; T.equal(S.State.validateState(state).ok, false); });
  T.test("不正な武将配属参照を検出", function () { var state = campaign(); state.officers.soma.castleId = "missing"; T.equal(S.State.validateState(state).ok, false); });
  T.test("不正な捕虜参照と捕獲勢力を検出", function () { var state = campaign(); S.Systems.Prisoner.capture(state, "hiyori", "missing"); var result = S.State.validateState(state); T.equal(result.ok, false); T.assert(result.errors.some(function (text) { return text.indexOf("捕獲勢力") >= 0; })); });
  T.test("pendingBattleの不正参照と兵力超過を検出", function () { var state = fresh(); state.events.pendingBattle = battlePlan(state, { sourceId: "missing", committedTroops: 999 }); var result = S.State.validateState(state); T.equal(result.ok, false); });
  T.test("データ駆動イベント定義", function () { S.Data.events.forEach(function (definition) { T.assert(S.Systems.Event.validateDefinition(definition).ok); }); var state = fresh(); state.campaign.season = 2; var before = state.campaign.food, result = S.Systems.Event.apply(state, S.Data.events[0], function () { return 0; }); T.assert(result.ok); T.assert(state.campaign.food > before); });
  T.test("季節進行がevents.jsを実行", function () { var state = fresh(); state.campaign.season = 1; var before = state.campaign.food; S.Systems.Turn.advance(state, { skipAI: true, random: function () { return 0.99; } }); T.assert(state.campaign.food > before); T.assert(state.events.log.some(function (item) { return item.text.indexOf("秋の収穫") >= 0; })); });
  T.test("2シナリオを生成", function () { var shortState = fresh({ scenarioId: "owari_short" }), longState = campaign(); T.equal(shortState.campaign.scenarioId, "owari_short"); T.equal(longState.campaign.scenarioId, "core_campaign"); T.assert(S.State.validateState(shortState).ok && S.State.validateState(longState).ok); });
  T.test("長期キャンペーンは12城", function () { T.equal(Object.keys(campaign().castles).length, 12); });
  T.test("長期キャンペーンは4勢力各3城", function () { var state = campaign(); T.equal(Object.keys(state.factions).length, 4); Object.keys(state.factions).forEach(function (id) { T.equal(Object.keys(state.castles).filter(function (castleId) { return state.castles[castleId].factionId === id; }).length, 3); }); });
  T.test("4勢力で新規開始", function () { ["aotsuki", "tokizawa", "yukishiro", "kurogane"].forEach(function (id) { var state = campaign(id); T.equal(state.campaign.playerFactionId, id); T.equal(S.Systems.Turn.playerCastles(state).length, 3); T.assert(S.State.validateState(state).ok); }); });
  T.test("プレイヤー勢力が動的", function () { var state = campaign("kurogane"); T.assert(S.Systems.Loyalty.privateAudience(state, "kurogane_temp_1").ok); T.equal(S.Systems.Loyalty.privateAudience(state, "keiketsu").ok, false); });
  T.test("3難易度を生成", function () { T.equal(S.Data.difficulties.length, 3); ["easy", "normal", "hard"].forEach(function (id) { var state = campaign("aotsuki", id); T.equal(state.campaign.difficultyId, id); T.assert(S.State.validateState(state).ok); }); });
  T.test("難易度を初期資源へ適用", function () { var easy = campaign("aotsuki", "easy"), hard = campaign("aotsuki", "hard"); T.assert(easy.campaign.gold > hard.campaign.gold); T.assert(easy.castles.kiyosu.troops > hard.castles.kiyosu.troops); });
  T.test("AI徴兵", function () { var state = campaign(), castle = state.castles.narumi, before = castle.troops, result = S.Systems.AI.takeAction(state, "tokizawa", { forceAction: "recruit" }); T.assert(result.ok, result.errors && result.errors.join(" / ")); T.assert(castle.troops > before); });
  T.test("AI対AI侵攻", function () { var state = campaign(); T.assert(S.Systems.Diplomacy.declareWar(state, "tokizawa", "yukishiro", {}).ok); state.castles.suemori.troops = 220; state.castles.atsuta.troops = 10; var result = S.Systems.AI.takeAction(state, "tokizawa", { forceAction: "attack", targetFactionId: "yukishiro", forceWin: true, random: function () { return 0.8; } }); T.assert(result.ok, result.errors && result.errors.join(" / ")); var report = state.events.battleReports.slice(-1)[0]; T.equal(report.attackerFactionId, "tokizawa"); T.equal(report.defenderFactionId, "yukishiro"); });
  T.test("AI対プレイヤー侵攻", function () { var state = campaign("aotsuki"); state.castles.narumi.troops = 220; state.castles.kiyosu.troops = 10; var result = S.Systems.AI.takeAction(state, "tokizawa", { forceAction: "attack", targetFactionId: "aotsuki", forceWin: false, random: function () { return 0.8; } }); T.assert(result.ok, result.errors && result.errors.join(" / ")); T.equal(state.events.battleReports.slice(-1)[0].defenderFactionId, "aotsuki"); T.equal(state.events.defenseNotifications.length, 1); });
  T.test("AI季節行動は各勢力1〜2回", function () { var state = campaign(), result = S.Systems.AI.runSeason(state, { random: function () { return 0; } }); T.assert(result.ok); var counts = {}; result.stateChanges.actions.forEach(function (item) { counts[item.factionId] = (counts[item.factionId] || 0) + 1; }); Object.keys(state.factions).filter(function (id) { return id !== state.campaign.playerFactionId; }).forEach(function (id) { T.assert((counts[id] || 0) >= 1 && counts[id] <= 2, id); }); });
  T.test("勢力滅亡で残存武将を浪人化", function () { var state = campaign(); Object.keys(state.castles).forEach(function (id) { if (state.castles[id].factionId === "kurogane") { state.castles[id].factionId = "aotsuki"; state.castles[id].governorId = null; } }); S.Systems.Victory.check(state); T.equal(state.factions.kurogane.alive, false); Object.keys(state.officers).filter(function (id) { return state.officers[id].factionId === "kurogane"; }).forEach(function (id) { T.equal(state.officers[id].status, "ronin"); }); });
  T.test("天下統一判定", function () { var state = campaign("tokizawa"); Object.keys(state.castles).forEach(function (id) { state.castles[id].factionId = "tokizawa"; state.castles[id].governorId = null; }); S.Systems.Victory.check(state); T.equal(state.campaign.outcome, "victory"); });
  T.test("所有城0で敗北", function () { var state = campaign("yukishiro"); Object.keys(state.castles).forEach(function (id) { if (state.castles[id].factionId === "yukishiro") { state.castles[id].factionId = "aotsuki"; state.castles[id].governorId = null; } }); S.Systems.Victory.check(state); T.equal(state.campaign.outcome, "defeat"); });
  T.test("武将移動は命令1で城主解除", function () { var state = campaign(), before = state.campaign.commands, result = S.Systems.Officer.moveOfficer(state, "keiketsu", "aonohara", {}); T.assert(result.ok); T.equal(state.campaign.commands, before - 1); T.equal(state.castles.kiyosu.governorId, null); T.equal(state.officers.keiketsu.castleId, "aonohara"); });
  T.test("捕虜・重傷武将は移動不可", function () { var state = campaign(); S.Systems.Prisoner.capture(state, "keiketsu", "tokizawa"); T.equal(S.Systems.Officer.moveOfficer(state, "keiketsu", "aonohara", {}).ok, false); var other = fresh(); other.officers.soma.injury = "重傷"; T.equal(S.Systems.Officer.moveOfficer(other, "soma", "kiyosu", {}).ok, false); });
  T.test("v0.7セーブをowari_shortへ移行", function () { var old = asV08(fresh()); old.schemaVersion = 7; old.gameVersion = "core-0.7"; delete old.campaign.scenarioId; delete old.campaign.difficultyId; delete old.events.triggeredIds; delete old.events.defenseNotifications; delete old.events.aiHistory; var result = S.State.migrateState(old); T.assert(result.ok, result.errors && result.errors.join(" / ")); T.equal(result.source, "core-0.7"); T.equal(result.state.schemaVersion, 12); T.equal(result.state.campaign.scenarioId, "owari_short"); T.equal(result.state.campaign.difficultyId, "normal"); });
  T.test("v0.8セーブ・ロードとメタ情報", function () { var state = asV08(campaign("kurogane", "hard")), key = "project_sengoku_core_v08_test"; state.campaign.year = 4; localStorage.setItem(key, JSON.stringify(state)); var peek = S.Save.peek(key); T.assert(peek.ok); T.equal(peek.summary.scenarioName, "群雄キャンペーン（仮）"); T.equal(peek.summary.factionName, "黒鉄家（仮）"); T.equal(peek.summary.difficultyName, "難しい"); var loaded = S.Save.load(key); T.assert(loaded.ok, loaded.errors && loaded.errors.join(" / ")); T.equal(loaded.source, "core-0.8"); T.equal(loaded.state.schemaVersion, 12); T.equal(loaded.state.campaign.year, 4); S.Save.remove(key); });
  T.test("明示的整合性修復", function () { var state = campaign(); state.castles.kiyosu.governorId = "missing"; state.castles.narumi.neighbors = state.castles.narumi.neighbors.filter(function (id) { return id !== "kiyosu"; }); var repaired = S.State.repairState(state); T.assert(repaired.changes.length >= 2); T.assert(S.State.validateState(state).ok, S.State.validateState(state).errors.join(" / ")); });
  T.test("100季節シミュレーション 1", function () { var state = campaign("aotsuki", "easy"), result = S.Systems.AI.simulate(state, 100, rng(101)); T.assert(result.ok, result.errors.join(" / ")); T.equal(result.stateChanges.completedSeasons, 100); assertClean(state); });
  T.test("100季節シミュレーション 2", function () { var state = campaign("tokizawa", "normal"), result = S.Systems.AI.simulate(state, 100, rng(202)); T.assert(result.ok, result.errors.join(" / ")); T.equal(result.stateChanges.completedSeasons, 100); assertClean(state); });
  T.test("100季節シミュレーション 3", function () { var state = campaign("yukishiro", "hard"), result = S.Systems.AI.simulate(state, 100, rng(303)); T.assert(result.ok, result.errors.join(" / ")); T.equal(result.stateChanges.completedSeasons, 100); assertClean(state); });

  /* Core v0.9 外交・条約・戦略AIテスト。 */
  T.test("schemaVersion 12とゲーム版", function () { var state = campaign(); T.equal(state.schemaVersion, 12); T.equal(state.gameVersion, "core-0.95"); });
  T.test("武将関係と勢力外交の名前空間分離", function () { var state = campaign(); T.equal(S.Systems.Relationship.value(state, "keiketsu", "soma"), 16); T.assert(state.diplomacy.relations["aotsuki|tokizawa"].status === "war"); T.equal(typeof state.diplomacy.relations["keiketsu|soma"], "undefined"); });
  T.test("v0.8武将関係を値損失なく移行", function () { var old = asV08(campaign()); old.diplomacy.relations = { "kanenobu|keiketsu": 23, "keiketsu|soma": -7, "hiyori|takama": 41 }; var migrated = S.State.migrateState(old); T.assert(migrated.ok, migrated.errors && migrated.errors.join(" / ")); T.equal(migrated.state.relationships.officers["kanenobu|keiketsu"], 23); T.equal(migrated.state.relationships.officers["keiketsu|soma"], -7); T.equal(migrated.state.relationships.officers["hiyori|takama"], 41); T.equal(migrated.state.diplomacy.relations["keiketsu|soma"], undefined); });
  T.test("全シナリオの勢力外交ペア完全生成", function () { S.Data.scenarios.forEach(function (scenario) { var state = fresh({ scenarioId: scenario.id }); T.equal(Object.keys(state.diplomacy.relations).length, scenario.factionIds.length * (scenario.factionIds.length - 1) / 2); T.assert(S.State.validateState(state).ok); }); });
  T.test("外交自己ペアなし", function () { var state = campaign(); T.equal(Object.keys(state.diplomacy.relations).some(function (key) { var ids = key.split("|"); return ids[0] === ids[1]; }), false); });
  T.test("短期シナリオ初期戦争", function () { var state = fresh(); T.equal(S.Systems.Diplomacy.status(state, "aotsuki", "tokizawa"), "war"); T.equal(S.Systems.Diplomacy.status(state, "aotsuki", "yukishiro"), "neutral"); });
  T.test("長期シナリオ初期戦争2組", function () { var state = campaign(); T.equal(S.Systems.Diplomacy.status(state, "aotsuki", "tokizawa"), "war"); T.equal(S.Systems.Diplomacy.status(state, "yukishiro", "kurogane"), "war"); });
  T.test("neutral攻撃拒否", function () { var state = campaign(), result = S.Systems.Battle.plan(state, { sourceId: "aonohara", targetId: "iwato", commanderId: "soma", committedTroops: 20, attackerFactionId: "aotsuki", defenderFactionId: "kurogane" }); T.equal(result.ok, false); T.assert(result.errors[0].indexOf("外交") >= 0); });
  T.test("war攻撃許可", function () { var state = fresh(), result = S.Systems.Battle.plan(state, battlePlan(state)); T.assert(result.ok, result.errors && result.errors.join(" / ")); T.equal(result.stateChanges.pendingBattle.diplomacyLegal, true); });
  T.test("全条約で攻撃拒否", function () { ["ceasefire", "non_aggression", "alliance"].forEach(function (status) { var state = fresh(), relation = S.Systems.Diplomacy.relation(state, "aotsuki", "tokizawa"); relation.status = status; relation.expiresTurn = 4; var result = S.Systems.Battle.plan(state, battlePlan(state)); T.equal(result.ok, false, status); }); });
  T.test("宣戦布告", function () { var state = campaign(), result = S.Systems.Diplomacy.declareWar(state, "aotsuki", "yukishiro", {}); T.assert(result.ok, result.errors && result.errors.join(" / ")); T.equal(S.Systems.Diplomacy.status(state, "aotsuki", "yukishiro"), "war"); T.assert(state.diplomacy.history.some(function (item) { return item.type === "declare_war"; })); });
  T.test("和平締結", function () { var state = fresh(), result = S.Systems.Diplomacy.makePeace(state, "aotsuki", "tokizawa", { forceAccept: true }); T.assert(result.ok); T.equal(S.Systems.Diplomacy.status(state, "aotsuki", "tokizawa"), "neutral"); });
  T.test("停戦期限", function () { var state = fresh(), result = S.Systems.Diplomacy.makeCeasefire(state, "aotsuki", "tokizawa", { forceAccept: true, duration: 2 }); T.assert(result.ok); var relation = S.Systems.Diplomacy.relation(state, "aotsuki", "tokizawa"); T.equal(relation.status, "ceasefire"); state.campaign.turn = relation.expiresTurn; S.Systems.Diplomacy.expireTreaties(state); T.equal(relation.status, "neutral"); });
  T.test("不戦条約", function () { var state = campaign(), result = S.Systems.Diplomacy.makeNonAggression(state, "aotsuki", "yukishiro", { forceAccept: true }); T.assert(result.ok); T.equal(S.Systems.Diplomacy.status(state, "aotsuki", "yukishiro"), "non_aggression"); });
  T.test("同盟", function () { var state = campaign(), result = S.Systems.Diplomacy.makeAlliance(state, "aotsuki", "yukishiro", { forceAccept: true }); T.assert(result.ok); T.equal(S.Systems.Diplomacy.status(state, "aotsuki", "yukishiro"), "alliance"); });
  T.test("条約延長", function () { var state = campaign(); S.Systems.Diplomacy.makeAlliance(state, "aotsuki", "yukishiro", { forceAccept: true }); var relation = S.Systems.Diplomacy.relation(state, "aotsuki", "yukishiro"), before = relation.expiresTurn; state.campaign.turn += 1; var result = S.Systems.Diplomacy.extendTreaty(state, "aotsuki", "yukishiro", {}); T.assert(result.ok); T.assert(relation.expiresTurn > before); });
  T.test("同季節の締結・破棄禁止", function () { var state = campaign(); S.Systems.Diplomacy.makeAlliance(state, "aotsuki", "yukishiro", { forceAccept: true }); T.equal(S.Systems.Diplomacy.breakTreaty(state, "aotsuki", "yukishiro", {}).ok, false); });
  T.test("条約破棄ペナルティ", function () { var state = campaign(); S.Systems.Diplomacy.makeAlliance(state, "aotsuki", "yukishiro", { forceAccept: true }); state.campaign.turn += 1; var relation = S.Systems.Diplomacy.relation(state, "aotsuki", "yukishiro"), trust = relation.trust, reputation = state.diplomacy.reputation.aotsuki, result = S.Systems.Diplomacy.breakTreaty(state, "aotsuki", "yukishiro", {}); T.assert(result.ok); T.assert(relation.trust < trust); T.assert(state.diplomacy.reputation.aotsuki < reputation); T.equal(relation.brokenTreaties, 1); });
  T.test("関係改善は使者政治を利用", function () { var state = campaign(), before = S.Systems.Diplomacy.relation(state, "aotsuki", "yukishiro").score, gold = state.campaign.gold, result = S.Systems.Diplomacy.improveRelations(state, "aotsuki", "yukishiro", "soma", {}); T.assert(result.ok); T.assert(S.Systems.Diplomacy.relation(state, "aotsuki", "yukishiro").score > before); T.assert(state.campaign.gold < gold); });
  T.test("物資援助を実資源で移動", function () { var state = campaign(), source = state.campaign.gold, target = state.factions.yukishiro.gold, result = S.Systems.Diplomacy.sendAid(state, "aotsuki", "yukishiro", { gold: 12, food: 8 }); T.assert(result.ok); T.equal(state.campaign.gold, source - 12); T.equal(state.factions.yukishiro.gold, target + 12); });
  T.test("援軍は実兵力のみ移動", function () { var state = campaign(); S.Systems.Diplomacy.makeAlliance(state, "aotsuki", "yukishiro", { forceAccept: true }); var source = state.castles.kiyosu.troops, target = state.castles.atsuta.troops, result = S.Systems.Diplomacy.sendReinforcement(state, "aotsuki", "yukishiro", "kiyosu", "atsuta", 10); T.assert(result.ok); T.equal(state.castles.kiyosu.troops, source - 10); T.equal(state.castles.atsuta.troops, target + 10); });
  T.test("援軍の幽霊兵力拒否", function () { var state = campaign(); S.Systems.Diplomacy.makeAlliance(state, "aotsuki", "yukishiro", { forceAccept: true }); var before = state.castles.kiyosu.troops, result = S.Systems.Diplomacy.sendReinforcement(state, "aotsuki", "yukishiro", "kiyosu", "atsuta", before); T.equal(result.ok, false); T.equal(state.castles.kiyosu.troops, before); });
  T.test("捕虜交換", function () { var state = campaign(); S.Systems.Prisoner.capture(state, "hiyori", "aotsuki"); S.Systems.Prisoner.capture(state, "soma", "tokizawa"); var result = S.Systems.Diplomacy.exchangePrisoners(state, "aotsuki", "tokizawa"); T.assert(result.ok, result.errors && result.errors.join(" / ")); T.equal(state.prisoners.indexOf("hiyori"), -1); T.equal(state.prisoners.indexOf("soma"), -1); });
  T.test("一方的捕虜解放", function () { var state = campaign(); S.Systems.Prisoner.capture(state, "hiyori", "aotsuki"); var before = S.Systems.Diplomacy.relation(state, "aotsuki", "tokizawa").trust, result = S.Systems.Diplomacy.releasePrisoner(state, "aotsuki", "hiyori"); T.assert(result.ok); T.assert(S.Systems.Diplomacy.relation(state, "aotsuki", "tokizawa").trust > before); });
  T.test("降伏勧告で従属", function () { var state = fresh(), result = S.Systems.Diplomacy.recommendSurrender(state, "aotsuki", "tokizawa", { forceAccept: true }); T.assert(result.ok, result.errors && result.errors.join(" / ")); T.equal(S.Systems.Diplomacy.overlordOf(state, "tokizawa"), "aotsuki"); });
  T.test("方向性のある従属", function () { var state = campaign(), result = S.Systems.Diplomacy.vassalize(state, "aotsuki", "yukishiro", {}); T.assert(result.ok); T.equal(state.diplomacy.vassalage.yukishiro.overlordFactionId, "aotsuki"); T.equal(state.diplomacy.vassalage.aotsuki, undefined); });
  T.test("従属循環拒否", function () { var state = campaign(); T.assert(S.Systems.Diplomacy.vassalize(state, "aotsuki", "yukishiro", {}).ok); T.equal(S.Systems.Diplomacy.vassalize(state, "yukishiro", "aotsuki", {}).ok, false); });
  T.test("tributeを一季一回処理", function () { var state = campaign(); S.Systems.Diplomacy.vassalize(state, "aotsuki", "yukishiro", {}); var playerGold = state.campaign.gold, subjectGold = state.factions.yukishiro.gold; state.campaign.turn = 1; S.Systems.Diplomacy.processSeasonStart(state); var after = state.campaign.gold; S.Systems.Diplomacy.processSeasonStart(state); T.assert(after > playerGold); T.assert(state.factions.yukishiro.gold < subjectGold); T.equal(state.campaign.gold, after); });
  T.test("従属解除", function () { var state = campaign(); S.Systems.Diplomacy.vassalize(state, "aotsuki", "yukishiro", {}); T.assert(S.Systems.Diplomacy.releaseVassal(state, "aotsuki", "yukishiro").ok); T.equal(state.diplomacy.vassalage.yukishiro, undefined); T.assert(S.State.validateState(state).ok, S.State.validateState(state).errors.join(" / ")); });
  T.test("独立", function () { var state = campaign(); S.Systems.Diplomacy.vassalize(state, "aotsuki", "yukishiro", {}); var result = S.Systems.Diplomacy.independence(state, "yukishiro", { forceSuccess: true }); T.assert(result.ok); T.equal(state.diplomacy.vassalage.yukishiro, undefined); T.equal(S.Systems.Diplomacy.status(state, "aotsuki", "yukishiro"), "war"); });
  T.test("従属勢力の軍事制限", function () { var state = campaign(); S.Systems.Diplomacy.vassalize(state, "aotsuki", "yukishiro", {}); T.equal(S.Systems.Diplomacy.canAttack(state, "yukishiro", "kurogane").ok, false); });
  T.test("戦争疲弊が合戦で上昇", function () { var state = fresh(), before = state.diplomacy.warExhaustion.aotsuki; S.Systems.Battle.plan(state, battlePlan(state)); S.Systems.Battle.resolve(state, { forceWin: false, random: function () { return 0.9; } }); T.assert(state.diplomacy.warExhaustion.aotsuki > before); });
  T.test("戦争疲弊が徴兵効率へ反映", function () { var normal = fresh(), tired = fresh(); tired.diplomacy.warExhaustion.aotsuki = 100; var beforeNormal = normal.castles.kiyosu.troops, beforeTired = tired.castles.kiyosu.troops; S.Systems.Domestic.executeRecruitment(normal, "kiyosu", "keiketsu"); S.Systems.Domestic.executeRecruitment(tired, "kiyosu", "keiketsu"); T.assert(normal.castles.kiyosu.troops - beforeNormal > tired.castles.kiyosu.troops - beforeTired); });
  T.test("AIからプレイヤーへの提案を保留保存", function () { var state = campaign(), result = S.Systems.Diplomacy.propose(state, "alliance", "yukishiro", "aotsuki", {}); T.assert(result.ok); T.equal(result.stateChanges.pending, true); T.equal(state.diplomacy.proposals.slice(-1)[0].status, "pending"); });
  T.test("AI提案の受諾", function () { var state = campaign(), proposed = S.Systems.Diplomacy.propose(state, "alliance", "yukishiro", "aotsuki", {}), id = proposed.stateChanges.proposal.id; var response = S.Systems.Diplomacy.respondProposal(state, id, true, {}); T.assert(response.ok); T.equal(S.Systems.Diplomacy.status(state, "aotsuki", "yukishiro"), "alliance"); });
  T.test("AI提案の拒否", function () { var state = campaign(), proposed = S.Systems.Diplomacy.propose(state, "alliance", "yukishiro", "aotsuki", {}), id = proposed.stateChanges.proposal.id; T.assert(S.Systems.Diplomacy.respondProposal(state, id, false, {}).ok); T.equal(state.diplomacy.proposals.slice(-1)[0].status, "rejected"); });
  T.test("AI外交は季節0〜1行動", function () { var state = campaign(), result = S.Systems.AI.runDiplomacySeason(state, { random: function () { return 0; } }); T.assert(result.ok); var counts = {}; result.stateChanges.actions.forEach(function (item) { counts[item.factionId] = (counts[item.factionId] || 0) + 1; }); Object.keys(counts).forEach(function (id) { T.assert(counts[id] <= 1); }); });
  T.test("停滞12季で戦略再評価", function () { var state = campaign(), detected = false; for (var i = 0; i < 12; i += 1) if (S.Systems.Diplomacy.updateStagnation(state)) detected = true; T.equal(detected, true); T.assert(state.diplomacy.history.some(function (item) { return item.type === "strategic_reevaluation"; })); });
  T.test("覇権勝利", function () { var state = campaign("aotsuki"); ["tokizawa", "yukishiro", "kurogane"].forEach(function (id) { T.assert(S.Systems.Diplomacy.vassalize(state, "aotsuki", id, {}).ok); }); var result = S.Systems.Victory.check(state); T.equal(state.campaign.outcome, "victory"); T.equal(result.stateChanges.hegemony, true); });
  T.test("schema 12保存・ロード", function () { var state = campaign(), key = "project_sengoku_core_v095_test"; state.diplomacy.warExhaustion.aotsuki = 33; T.assert(S.Save.save(state, key).ok); var loaded = S.Save.load(key); T.assert(loaded.ok); T.equal(loaded.source, "core-0.95"); T.equal(loaded.state.diplomacy.warExhaustion.aotsuki, 33); S.Save.remove(key); });
  T.test("不正外交status拒否", function () { var state = campaign(); state.diplomacy.relations["aotsuki|tokizawa"].status = "friend"; T.equal(S.State.validateState(state).ok, false); });
  T.test("不正外交値拒否", function () { var state = campaign(); state.diplomacy.relations["aotsuki|tokizawa"].trust = 101; T.equal(S.State.validateState(state).ok, false); });
  T.test("不正外交提案拒否", function () { var state = campaign(); state.diplomacy.proposals.push({ id: "bad", type: "unknown" }); T.equal(S.State.validateState(state).ok, false); });
  T.test("外交ペア欠損拒否", function () { var state = campaign(); delete state.diplomacy.relations["aotsuki|tokizawa"]; T.equal(S.State.validateState(state).ok, false); });
  T.test("循環従属データ拒否", function () { var state = campaign(); state.diplomacy.vassalage.aotsuki = { subjectFactionId: "aotsuki", overlordFactionId: "tokizawa", sinceTurn: 0, independenceAllowedTurn: 8, tribute: S.Util.deepClone(S.Data.diplomacy.tribute) }; state.diplomacy.vassalage.tokizawa = { subjectFactionId: "tokizawa", overlordFactionId: "aotsuki", sinceTurn: 0, independenceAllowedTurn: 8, tribute: S.Util.deepClone(S.Data.diplomacy.tribute) }; T.equal(S.State.validateState(state).ok, false); });
  T.test("neutral pendingBattleを厳格拒否", function () { var state = campaign(); state.events.pendingBattle = { sourceId: "aonohara", targetId: "iwato", commanderId: "soma", deputyId: null, enemyId: "kurogane_temp_2", attackerFactionId: "aotsuki", defenderFactionId: "kurogane", committedTroops: 10, diplomacyLegal: false, debugDiplomacyOverride: false }; T.equal(S.State.validateState(state).ok, false); });
  T.test("条約違反合戦記録を拒否", function () { var state = campaign(); state.events.battleReports.push({ id: "illegal", diplomacyLegal: false, debugDiplomacyOverride: false }); T.equal(S.State.validateState(state).ok, false); });
  T.test("合戦計画後の和平で解決拒否", function () { var state = fresh(); T.assert(S.Systems.Battle.plan(state, battlePlan(state)).ok); T.assert(S.Systems.Diplomacy.makePeace(state, "aotsuki", "tokizawa", { forceAccept: true }).ok); T.equal(S.Systems.Battle.resolve(state, {}).ok, false); T.equal(state.events.pendingBattle, null); });
  T.test("再宣戦クールダウン", function () { var state = fresh(); S.Systems.Diplomacy.makePeace(state, "aotsuki", "tokizawa", { forceAccept: true }); state.campaign.turn += 1; T.equal(S.Systems.Diplomacy.declareWar(state, "aotsuki", "tokizawa", {}).ok, false); });
  T.test("同時戦争2件上限", function () { var state = campaign(); T.assert(S.Systems.Diplomacy.declareWar(state, "aotsuki", "yukishiro", {}).ok); T.equal(S.Systems.Diplomacy.declareWar(state, "aotsuki", "kurogane", {}).ok, false); });
  T.test("全AI長期シミュレーション", function () { var state = campaign("aotsuki", "normal"), result = S.Systems.AI.simulateAllFactions(state, 200, rng(909), { terminationLimit: 300 }); T.assert(result.ok, result.errors.join(" / ")); T.equal(result.stateChanges.treatyViolationAttacks, 0); T.assert(result.stateChanges.maximumStagnation < 24); assertClean(state); });
  T.run();
})(window.Sengoku, window.SengokuTest);
