(function (S) {
  "use strict";
  var U = S.UI;
  function name(state, id) { return state.factions[id] ? state.factions[id].name : id; }
  function treatyRemaining(state, relation) { return Number.isInteger(relation.expiresTurn) ? Math.max(0, relation.expiresTurn - state.campaign.turn) + "季" : "—"; }
  function vassalLabel(state, factionId) {
    var overlord = S.Systems.Diplomacy.overlordOf(state, factionId); if (overlord) return "従属 → " + name(state, overlord);
    var subjects = Object.keys(state.diplomacy.vassalage).filter(function (id) { return state.diplomacy.vassalage[id].overlordFactionId === factionId; });
    return subjects.length ? "宗主（" + subjects.map(function (id) { return name(state, id); }).join("・") + "）" : "独立";
  }
  function statusClass(status) { return status === "war" ? "war" : status === "alliance" ? "alliance" : status === "ceasefire" ? "ceasefire" : status === "non_aggression" ? "pact" : "neutral"; }
  function crest(state, factionId) {
    var faction = state.factions[factionId];
    return '<span class="sv-faction-crest" style="--faction-color:' + U.escape((faction && faction.color) || '#6883aa') + '">紋</span>';
  }
  function visualOpen(html) { U.openModal('<div class="strategic-visual-screen">' + html + '</div>', { modalClass: "strategic-visual-modal" }); }

  U.showDiplomacy = function () {
    var state = S.State.current, playerId = state.campaign.playerFactionId, pending = state.diplomacy.proposals.filter(function (item) { return item.status === "pending" && item.targetFactionId === playerId; });
    var cards = Object.keys(state.factions).filter(function (id) { return id !== playerId; }).map(function (id) {
      var relation = S.Systems.Diplomacy.relation(state, playerId, id), power = Math.round(S.Systems.Diplomacy.power(state, id)), cls = statusClass(relation.status);
      return '<button type="button" class="sv-diplomacy-card ' + cls + '" data-diplomacy-target="' + U.escape(id) + '">' + crest(state, id) + '<div class="sv-diplomacy-card-copy"><small>' + U.escape(vassalLabel(state, id)) + '</small><strong>' + U.escape(name(state, id)) + '</strong><em>' + U.escape(S.Systems.Diplomacy.label(relation.status)) + '</em></div><div class="sv-diplomacy-meter"><span>関係<b>' + relation.score + '</b></span><i><b style="width:' + Math.max(0, Math.min(100, relation.score)) + '%"></b></i><span>信頼 ' + relation.trust + ' / 遺恨 ' + relation.grievance + '</span></div><div class="sv-diplomacy-card-stats"><span>国力<strong>' + power + '</strong></span><span>評判<strong>' + state.diplomacy.reputation[id] + '</strong></span><span>疲弊<strong>' + state.diplomacy.warExhaustion[id] + '</strong></span><span>残り<strong>' + treatyRemaining(state, relation) + '</strong></span></div></button>';
    }).join("");
    visualOpen('<!-- FACTION DIPLOMACY --><header class="sv-screen-header"><div><small>外交評定</small><h2>' + U.escape(name(state, playerId)) + '　外交</h2></div><div class="sv-resource-chips"><span>評判<strong>' + state.diplomacy.reputation[playerId] + '</strong></span><span>戦争疲弊<strong>' + state.diplomacy.warExhaustion[playerId] + '</strong></span><span>提案<strong>' + pending.length + '</strong></span></div></header><section class="sv-diplomacy-banner"><img src="assets/ui/diplomacy-scroll.svg" alt="外交の仮ビジュアル"><div><strong>天下は戦だけでは動かない</strong><p>各勢力との関係、条約、援軍、捕虜交換をここで管理します。</p></div></section><div class="sv-diplomacy-grid">' + cards + '</div><div class="sv-screen-actions">' + (pending.length ? '<button class="button danger" data-open-proposals>届いた提案 ' + pending.length + '件</button>' : '') + '<button class="button secondary" data-open-diplomacy-history>外交履歴</button><button class="button primary" data-close-modal>閉じる</button></div>');
  };

  U.showDiplomacyDetail = function (targetId) {
    var state = S.State.current, playerId = state.campaign.playerFactionId, target = state.factions[targetId], relation = S.Systems.Diplomacy.relation(state, playerId, targetId);
    if (!target || !relation) { U.notify("外交対象が見つかりません", "error"); return; }
    var messengers = Object.keys(state.officers).map(function (id) { return state.officers[id]; }).filter(function (officer) { return officer.factionId === playerId && officer.status === "active"; }).sort(function (a, b) { return b.stats.politics - a.stats.politics; });
    var sourceCastles = S.Systems.Diplomacy.castlesFor(state, targetId), targetCastles = S.Systems.Diplomacy.castlesFor(state, playerId), availability = S.Systems.Diplomacy.actionAvailability(state, playerId, targetId), availabilityById = {};
    availability.forEach(function (item) { availabilityById[item.id] = item; });
    function action(id, label, icon) { var item = availabilityById[id] || { enabled: true, reason: "実行可能" }; return '<button class="sv-diplomacy-action" data-diplomacy-action="' + id + '" data-diplomacy-faction="' + U.escape(targetId) + '"' + (item.enabled ? '' : ' disabled') + ' title="' + U.escape(item.reason) + '"><span>' + icon + '</span><strong>' + U.escape(label) + '</strong><small>' + U.escape(item.reason) + '</small></button>'; }
    var playerSubject = state.diplomacy.vassalage[playerId], targetSubject = state.diplomacy.vassalage[targetId], prisoner = state.prisoners.find(function (id) { return state.officers[id].captorFactionId === playerId && state.officers[id].factionId === targetId; });
    visualOpen('<!-- DIPLOMACY DETAIL --><header class="sv-screen-header"><div><small>外交対象</small><h2>' + U.escape(target.name) + '</h2></div><div class="sv-resource-chips"><span>状態<strong>' + U.escape(S.Systems.Diplomacy.label(relation.status)) + '</strong></span><span>関係<strong>' + relation.score + '</strong></span><span>国力<strong>' + Math.round(S.Systems.Diplomacy.power(state, targetId)) + '</strong></span></div></header>' +
      '<section class="sv-diplomacy-detail-head">' + crest(state, targetId) + '<div><small>' + U.escape(vassalLabel(state, targetId)) + '</small><strong>' + U.escape(target.name) + '</strong><span>信頼 ' + relation.trust + '　遺恨 ' + relation.grievance + '　評判 ' + state.diplomacy.reputation[targetId] + '　疲弊 ' + state.diplomacy.warExhaustion[targetId] + '　条約残り ' + treatyRemaining(state, relation) + '</span></div><label><small>使者</small><select id="diplomacyMessenger">' + messengers.map(function (officer) { return '<option value="' + U.escape(officer.id) + '">' + U.escape(officer.name) + '（政治' + officer.stats.politics + '）</option>'; }).join('') + '</select></label></section>' +
      '<div class="sv-diplomacy-actions">' + action("improve", "関係改善", "礼") + action("declare_war", "宣戦", "戦") + action("peace", "和平", "和") + action("ceasefire", "停戦", "停") + action("non_aggression", "不戦条約", "約") + action("alliance", "同盟", "盟") + action("extend", "条約延長", "延") + action("break_treaty", "条約破棄", "断") + action("aid", "物資援助", "援") + action("reinforcement", "援軍要請", "軍") + action("prisoner_exchange", "捕虜交換", "換") + (prisoner ? action("release_prisoner", "捕虜解放", "放") : "") + action("surrender", "降伏勧告", "降") + action("vassalage", "従属提案", "従") + (targetSubject && targetSubject.overlordFactionId === playerId ? action("release_vassal", "従属解除", "解") : "") + (playerSubject && playerSubject.overlordFactionId === targetId ? action("independence", "独立", "独") : "") + '</div>' +
      '<details class="sv-diplomacy-options"><summary>援助・援軍の詳細指定</summary><div class="sv-diplomacy-option-grid"><label><span>援助（金）</span><input id="diplomacyAidGold" type="number" min="0" value="10"></label><label><span>援助（兵糧）</span><input id="diplomacyAidFood" type="number" min="0" value="10"></label><label><span>援軍元（相手）</span><select id="diplomacyReinforceSource">' + sourceCastles.map(function (castle) { return '<option value="' + U.escape(castle.id) + '">' + U.escape(castle.name) + '（兵' + castle.troops + '）</option>'; }).join('') + '</select></label><label><span>援軍先（自勢力）</span><select id="diplomacyReinforceTarget">' + targetCastles.map(function (castle) { return '<option value="' + U.escape(castle.id) + '">' + U.escape(castle.name) + '</option>'; }).join('') + '</select></label><label><span>援軍数</span><input id="diplomacyReinforceTroops" type="number" min="1" value="10"></label></div></details>' +
      '<div class="sv-screen-actions"><button class="button secondary" data-open-diplomacy>外交一覧へ</button><button class="button primary" data-close-modal>閉じる</button></div>');
  };

  U.showDiplomacyHistory = function () {
    var entries = S.State.current.diplomacy.history.slice().reverse();
    visualOpen('<!-- DIPLOMACY HISTORY 同盟 --><header class="sv-screen-header"><div><small>外交記録</small><h2>外交履歴</h2></div></header><div class="sv-history-list">' + (entries.length ? entries.map(function (entry) { return '<div class="sv-history-entry"><span>第' + entry.turn + '季</span><strong>' + U.escape(S.Systems.Diplomacy.proposalLabel(entry.type)) + '</strong><p>' + U.escape(entry.text) + '</p></div>'; }).join('') : '<p class="sv-empty-note">外交履歴はありません。</p>') + '</div><div class="sv-screen-actions"><button class="button secondary" data-open-diplomacy>外交へ</button><button class="button primary" data-close-modal>閉じる</button></div>');
  };

  U.showPendingProposals = function () {
    var state = S.State.current, playerId = state.campaign.playerFactionId, proposals = state.diplomacy.proposals.filter(function (item) { return item.status === "pending" && item.targetFactionId === playerId; });
    visualOpen('<header class="sv-screen-header"><div><small>使者到来</small><h2>外交提案</h2></div><div class="sv-resource-chips"><span>件数<strong>' + proposals.length + '</strong></span></div></header><div class="sv-proposal-grid">' + (proposals.length ? proposals.map(function (proposal) { return '<article class="sv-proposal-card">' + crest(state, proposal.actorFactionId) + '<div><strong>' + U.escape(name(state, proposal.actorFactionId)) + '</strong><h3>' + U.escape(S.Systems.Diplomacy.proposalLabel(proposal.type)) + '</h3><small>期限：第' + proposal.expiresTurn + '季</small></div><div class="sv-proposal-actions"><button class="button secondary" data-respond-proposal="reject" data-proposal-id="' + U.escape(proposal.id) + '">拒否</button><button class="button primary" data-respond-proposal="accept" data-proposal-id="' + U.escape(proposal.id) + '">受諾</button></div></article>'; }).join('') : '<p class="sv-empty-note">保留中の提案はありません。</p>') + '</div><div class="sv-screen-actions"><button class="button secondary" data-open-diplomacy>外交へ</button><button class="button primary" data-close-modal>閉じる</button></div>');
  };
})(window.Sengoku);
