(function (S) {
  "use strict";
  var E = S.Systems.Event = {};
  var LIMITS = { chainDepth: 12, eventsPerEmit: 20, queue: 50, history: 500, diagnostics: 200, choices: 12, effects: 30, selectors: 20 };
  var triggerValues = Object.keys(S.Config.EVENT_TRIGGERS).map(function (key) { return S.Config.EVENT_TRIGGERS[key]; }).filter(function (value, index, values) { return values.indexOf(value) === index; });
  var selectorTypes = ["triggerOfficer", "triggerCastle", "triggerFaction", "playerFaction", "selectedCastle", "battleAttacker", "battleDefender", "officerById", "randomOfficer", "castleById", "randomPlayerCastle", "highestStatOfficer", "lowestStatOfficer", "highestLoyaltyOfficer", "lowestLoyaltyOfficer", "highestGrievanceOfficer", "castleGovernor", "randomPrisoner", "randomFactionCastle", "weakestBorderCastle", "strongestCastle", "recentlyCapturedCastle", "factionById", "strongestFaction", "weakestFaction", "randomEnemyFaction", "diplomaticPartner"];
  var conditionTypes = ["seasonIn", "playerCastleCountAtLeast", "scenarioIs", "campaignResourceAtLeast", "targetExists", "flagEquals", "counterAtLeast", "all", "any", "not", "scenario", "difficulty", "turn", "year", "season", "resource", "factionAlive", "factionCastleCount", "factionTotalTroops", "factionResource", "factionRank", "factionIsPlayer", "factionWarExhaustion", "factionReputation", "factionVassalStatus", "castleOwner", "castleTroops", "castleDefense", "castleMorale", "castleDevelopment", "castleNeighbor", "castleGovernor", "officerStatus", "officerFaction", "officerCastle", "officerStat", "officerLoyalty", "officerGrievance", "officerAmbition", "officerInjury", "officerLevel", "officerMerit", "officerPersonality", "officerTrait", "officerTag", "officerPromiseStatus", "officerRelationship", "rivalryRespect", "rivalryResentment", "rivalryEncounters", "diplomacyStatus", "diplomacyScore", "diplomacyTrust", "diplomacyGrievance", "diplomacyCommonEnemy", "eventFlag", "eventVariable", "eventCounter", "eventFired", "arcStatus", "arcStep", "eventCooldown"];
  var effectTypes = ["setFlag", "clearFlag", "setVariable", "addVariable", "setCounter", "addCounter", "setCooldown", "clearCooldown", "queueEvent", "cancelEvent", "campaignResource", "consumeCommand", "restoreCommand", "factionResource", "factionReputation", "warExhaustion", "castleTroops", "castleMorale", "castleDefense", "castleDevelopment", "castleOwner", "officerStat", "officerLoyalty", "officerGrievance", "officerLordTrust", "officerMerit", "officerExperience", "officerInjury", "officerRecover", "officerMove", "officerAppointGovernor", "officerStatus", "officerAddPersonality", "officerRemovePersonality", "officerAddTrait", "officerRemoveTrait", "officerAddTag", "officerRemoveTag", "officerPromise", "officerRelationship", "addRelationshipMemory", "rivalryRespect", "rivalryResentment", "rivalryEncounter", "releasePrisoner", "recruitPrisoner", "exchangePrisoner", "diplomacyScore", "diplomacyTrust", "diplomacyGrievance", "declareWar", "makePeace", "createCeasefire", "createNonAggression", "createAlliance", "breakTreaty", "createVassalage", "releaseVassal", "addLog", "addChronicle", "addOfficerHistory", "addDiplomacyHistory", "addBattleMemory", "startArc", "advanceArc", "setArcStep", "completeArc", "failArc", "requestBattlePlanner", "requestOfficerSelection", "requestCastleSelection", "requestFactionSelection"];
  var operators = ["==", "!=", ">", ">=", "<", "<=", "includes", "notIncludes", "between", "exists", "notExists"];

  function isObject(value) { return Boolean(value) && typeof value === "object" && !Array.isArray(value); }
  function clone(value) { return S.Util.deepClone(value); }
  function clamp(value, minimum, maximum) { return Math.max(minimum, Math.min(maximum, value)); }
  function finite(value) { return typeof value === "number" && Number.isFinite(value); }
  function containsExecutable(value) { if (typeof value === "function") return true; if (typeof value === "string") return /^(?:javascript:|https?:\/\/|file:|data:text\/html)/i.test(value); if (!value || typeof value !== "object") return false; return Object.keys(value).some(function (key) { return /^(?:handler|script|url|storage|file|dom|html)$/i.test(key) || containsExecutable(value[key]); }); }
  function hasRawHtml(value) { return typeof value === "string" && /<\/?[a-z][^>]*>/i.test(value); }
  function containsRawHtml(value) { if (hasRawHtml(value)) return true; if (!value || typeof value !== "object") return false; return Object.keys(value).some(function (key) { return containsRawHtml(value[key]); }); }
  function validId(value) { return typeof value === "string" && /^[a-z0-9][a-z0-9_.-]*$/.test(value); }
  function validRandom(value) { return finite(value) && value >= 0 && value < 1; }
  function escapeText(value) { return String(value == null ? "" : value).replace(/[&<>'"]/g, function (char) { return { "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" }[char]; }); }
  function dateLabel(state) { return S.Systems.Turn ? S.Systems.Turn.dateLabel(state) : "turn " + state.campaign.turn; }
  function normalizeRandom(state, injected) {
    if (typeof injected === "function") return injected;
    if (injected && typeof injected.next === "function") return function () { return injected.next(); };
    return function () { var rng = state.events.engine.rng; rng.state = (Math.imul(1664525, rng.state >>> 0) + 1013904223) >>> 0; rng.calls += 1; return rng.state / 4294967296; };
  }
  function addDiagnostic(state, code, message, instanceId) {
    var list = state.events.engine.diagnostics, duplicate = list.slice(-10).some(function (item) { return item.code === code && item.message === message && item.instanceId === (instanceId || null); });
    if (!duplicate) list.push({ turn: state.campaign.turn, code: code, message: String(message), instanceId: instanceId || null });
    while (list.length > LIMITS.diagnostics) list.shift();
  }
  function account(state, factionId) { return factionId === state.campaign.playerFactionId ? state.campaign : state.factions[factionId]; }
  function targetObject(state, ref) { if (!ref) return null; if (ref.type === "officer") return state.officers[ref.id] || null; if (ref.type === "castle") return state.castles[ref.id] || null; if (ref.type === "faction") return state.factions[ref.id] || null; return null; }
  function targetRef(type, item) { return item ? { type: type, id: item.id } : null; }
  function valueFromTarget(state, instance, name) { return instance && instance.targets && targetObject(state, instance.targets[name]); }
  function idFrom(state, instance, data, kind) {
    var direct = data[kind + "Id"] || data["target" + kind.charAt(0).toUpperCase() + kind.slice(1) + "Id"];
    if (direct) return direct;
    var name = data.target || data[kind + "Target"] || kind;
    var ref = instance && instance.targets && instance.targets[name];
    return ref && ref.type === kind ? ref.id : null;
  }
  function factionForInstance(state, instance) {
    var names = Object.keys((instance && instance.targets) || {}), id = instance && instance.payloadSnapshot && (instance.payloadSnapshot.factionId || instance.payloadSnapshot.triggerFactionId);
    if (id && state.factions[id]) return id;
    for (var i = 0; i < names.length; i += 1) if (instance.targets[names[i]].type === "faction") return instance.targets[names[i]].id;
    return state.campaign.playerFactionId;
  }
  function amountOf(effect, fallback) { return finite(effect.amount) ? effect.amount : finite(effect.value) ? effect.value : fallback; }
  function applyNumber(current, effect, minimum, maximum) { var amount = amountOf(effect, 0), next = effect.operation === "set" ? amount : current + amount; return clamp(next, minimum, maximum); }

  function conditionsOf(definition) {
    if (Array.isArray(definition.conditions)) return definition.conditions;
    var legacy = definition.conditions || {}, result = [];
    if (Array.isArray(legacy.seasons)) result.push({ type: "seasonIn", values: legacy.seasons });
    if (Number.isFinite(legacy.minPlayerCastles)) result.push({ type: "playerCastleCountAtLeast", value: legacy.minPlayerCastles });
    return result;
  }
  function choicesOf(definition) { return Array.isArray(definition.choices) && definition.choices.length ? definition.choices : [{ id: "auto", label: "確認", fallback: true, resultText: definition.message || "", effects: definition.effects || [] }]; }
  function compare(actual, condition, expected) {
    var op = condition.operator || "==";
    if (op === "==") return actual === expected;
    if (op === "!=") return actual !== expected;
    if (op === ">") return actual > expected;
    if (op === ">=") return actual >= expected;
    if (op === "<") return actual < expected;
    if (op === "<=") return actual <= expected;
    if (op === "includes") return Array.isArray(actual) ? actual.indexOf(expected) >= 0 : typeof actual === "string" && actual.indexOf(String(expected)) >= 0;
    if (op === "notIncludes") return Array.isArray(actual) ? actual.indexOf(expected) < 0 : typeof actual !== "string" || actual.indexOf(String(expected)) < 0;
    if (op === "between") { var range = Array.isArray(expected) ? expected : [condition.minimum, condition.maximum]; return range.length === 2 && actual >= range[0] && actual <= range[1]; }
    if (op === "exists") return actual !== undefined && actual !== null;
    if (op === "notExists") return actual === undefined || actual === null;
    return false;
  }
  function expectedValue(condition) { return condition.value !== undefined ? condition.value : condition.amount !== undefined ? condition.amount : condition.values; }
  function relationPair(state, instance, condition) {
    var a = condition.aId || condition.factionAId || idFrom(state, instance, { target: condition.aTarget || "factionA" }, "faction");
    var b = condition.bId || condition.factionBId || idFrom(state, instance, { target: condition.bTarget || "factionB" }, "faction");
    return { a: a, b: b };
  }
  function conditionActual(state, condition, instance) {
    var type = condition.type, factionId = idFrom(state, instance, condition, "faction"), castleId = idFrom(state, instance, condition, "castle"), officerId = idFrom(state, instance, condition, "officer");
    var faction = state.factions[factionId], castle = state.castles[castleId], officer = state.officers[officerId], pair, relation, rivalry, list;
    if (type === "scenario") return state.campaign.scenarioId;
    if (type === "difficulty") return state.campaign.difficultyId;
    if (type === "turn") return state.campaign.turn;
    if (type === "year") return state.campaign.year;
    if (type === "season") return state.campaign.season;
    if (type === "resource") return state.campaign[condition.resource];
    if (type === "factionAlive") return faction && faction.alive;
    if (type === "factionCastleCount") return Object.keys(state.castles).filter(function (id) { return state.castles[id].factionId === factionId; }).length;
    if (type === "factionTotalTroops") return S.Systems.Unit ? S.Systems.Unit.totalFactionTroops(state, factionId) : Object.keys(state.castles).reduce(function (sum, id) { return sum + (state.castles[id].factionId === factionId ? state.castles[id].troops : 0); }, 0);
    if (type === "factionResource") return account(state, factionId) && account(state, factionId)[condition.resource];
    if (type === "factionRank") { list = Object.keys(state.factions).filter(function (id) { return state.factions[id].alive; }).sort(function (a, b) { return S.Systems.Diplomacy.power(state, b) - S.Systems.Diplomacy.power(state, a); }); return list.indexOf(factionId) + 1; }
    if (type === "factionIsPlayer") return factionId === state.campaign.playerFactionId;
    if (type === "factionWarExhaustion") return state.diplomacy.warExhaustion[factionId];
    if (type === "factionReputation") return state.diplomacy.reputation[factionId];
    if (type === "factionVassalStatus") return state.diplomacy.vassalage[factionId] ? "subject" : Object.keys(state.diplomacy.vassalage).some(function (id) { return state.diplomacy.vassalage[id].overlordFactionId === factionId; }) ? "overlord" : "independent";
    if (type === "castleOwner") return castle && castle.factionId;
    if (type === "castleTroops") return castle && castle.troops;
    if (type === "castleDefense") return castle && castle.defense;
    if (type === "castleMorale") return castle && castle.morale;
    if (type === "castleDevelopment") return castle && (finite(castle.development) ? castle.development : castle.income);
    if (type === "castleNeighbor") return castle && castle.neighbors;
    if (type === "castleGovernor") return castle && castle.governorId;
    if (type === "officerStatus") return officer && officer.status;
    if (type === "officerFaction") return officer && officer.factionId;
    if (type === "officerCastle") return officer && officer.castleId;
    if (type === "officerStat") return officer && officer.stats[condition.stat];
    if (type === "officerLoyalty") return officer && officer.loyalty;
    if (type === "officerGrievance") return officer && officer.grievance;
    if (type === "officerAmbition") return officer && officer.ambition;
    if (type === "officerInjury") return officer && officer.injury;
    if (type === "officerLevel") return officer && officer.level;
    if (type === "officerMerit") return officer && officer.merit;
    if (type === "officerPersonality") return officer && officer.profile.personalityIds;
    if (type === "officerTrait") return officer && officer.profile.traitIds;
    if (type === "officerTag") return officer && officer.profile.tags;
    if (type === "officerPromiseStatus") return officer && officer.promise ? officer.promise.status : null;
    if (type === "officerRelationship") { var oa = condition.aId || idFrom(state, instance, { target: condition.aTarget || "officerA" }, "officer"), ob = condition.bId || idFrom(state, instance, { target: condition.bTarget || "officerB" }, "officer"); return oa && ob ? S.Systems.Relationship.value(state, oa, ob) : undefined; }
    if (type.indexOf("rivalry") === 0) { var ra = condition.aId || idFrom(state, instance, { target: condition.aTarget || "officerA" }, "officer"), rb = condition.bId || idFrom(state, instance, { target: condition.bTarget || "officerB" }, "officer"); rivalry = ra && rb ? S.Systems.Rivalry.get(state, ra, rb, false) : null; return type === "rivalryRespect" ? rivalry && rivalry.respect : type === "rivalryResentment" ? rivalry && rivalry.resentment : rivalry && rivalry.encounters; }
    if (type.indexOf("diplomacy") === 0) { pair = relationPair(state, instance, condition); relation = pair.a && pair.b ? S.Systems.Diplomacy.relation(state, pair.a, pair.b) : null; if (type === "diplomacyCommonEnemy") return pair.a && pair.b ? S.Systems.Diplomacy.commonEnemies(state, pair.a, pair.b).length > 0 : false; return relation && relation[type.replace("diplomacy", "").replace(/^./, function (char) { return char.toLowerCase(); })]; }
    if (type === "eventFlag") return state.events.flags[condition.flag || condition.key];
    if (type === "eventVariable") return state.events.engine.variables[condition.variable || condition.key];
    if (type === "eventCounter") return state.events.engine.counters[condition.counter || condition.key] || 0;
    if (type === "eventFired") return (state.events.engine.firedEventIds[condition.eventId] || 0) > 0;
    if (type === "arcStatus") return state.events.engine.arcs[condition.arcId] ? state.events.engine.arcs[condition.arcId].status : "inactive";
    if (type === "arcStep") return state.events.engine.arcs[condition.arcId] && state.events.engine.arcs[condition.arcId].currentStep;
    if (type === "eventCooldown") return state.events.engine.cooldowns[condition.cooldown || condition.key] || 0;
    return undefined;
  }
  function evaluateCondition(state, condition, instance) {
    if (condition.type === "all") return (condition.conditions || []).every(function (item) { return evaluateCondition(state, item, instance); });
    if (condition.type === "any") return (condition.conditions || []).some(function (item) { return evaluateCondition(state, item, instance); });
    if (condition.type === "not") return !evaluateCondition(state, condition.condition || (condition.conditions || [])[0], instance);
    if (condition.type === "seasonIn") return condition.values.indexOf(state.campaign.season) >= 0;
    if (condition.type === "playerCastleCountAtLeast") return E.playerCastles(state).length >= condition.value;
    if (condition.type === "scenarioIs") return state.campaign.scenarioId === condition.value;
    if (condition.type === "campaignResourceAtLeast") return state.campaign[condition.resource] >= condition.amount;
    if (condition.type === "targetExists") return Boolean(valueFromTarget(state, instance, condition.target));
    if (condition.type === "flagEquals") return state.events.flags[condition.flag] === condition.value;
    if (condition.type === "counterAtLeast") return (state.events.engine.counters[condition.counter] || 0) >= condition.value;
    return compare(conditionActual(state, condition, instance), condition, expectedValue(condition));
  }
  function evaluateConditions(state, conditions, instance) { for (var i = 0; i < (conditions || []).length; i += 1) if (!evaluateCondition(state, conditions[i], instance)) return { ok: false, reason: conditions[i].disabledReason || "条件を満たしていません" }; return { ok: true, reason: "" }; }
  function conditionNeedsInstance(condition) { if (!condition) return false; if (condition.type === "all" || condition.type === "any") return (condition.conditions || []).some(conditionNeedsInstance); if (condition.type === "not") return conditionNeedsInstance(condition.condition || (condition.conditions || [])[0]); return Boolean(condition.target || condition.officerTarget || condition.castleTarget || condition.factionTarget || condition.aTarget || condition.bTarget); }

  function selectorValue(state, spec, targets, field) {
    var value = spec[field];
    if (spec.idFrom && field === "id") { var from = targetObject(state, targets[spec.idFrom.target]); return from && from[spec.idFrom.field || "id"]; }
    if (typeof value === "string" && value.charAt(0) === "@") { var parts = value.slice(1).split("."), object = targetObject(state, targets[parts.shift()]); while (object && parts.length) object = object[parts.shift()]; return object; }
    return value;
  }
  function dependencyNames(spec) { var names = Array.isArray(spec.dependsOn) ? spec.dependsOn.slice() : []; if (spec.idFrom && spec.idFrom.target) names.push(spec.idFrom.target); Object.keys(spec).forEach(function (key) { var value = spec[key]; if (typeof value === "string" && value.charAt(0) === "@") names.push(value.slice(1).split(".")[0]); }); return names.filter(function (name, index, all) { return all.indexOf(name) === index; }); }
  function officerCandidates(state, spec, targets) {
    var factionId = selectorValue(state, spec, targets, "factionId"), castleId = selectorValue(state, spec, targets, "castleId");
    return Object.keys(state.officers).map(function (id) { return state.officers[id]; }).filter(function (officer) {
      var profile = officer.profile || S.State.createOfficerProfile();
      return (!spec.status || officer.status === spec.status) && (!spec.activeOnly || officer.status === "active") && (!factionId || officer.factionId === factionId) && (!castleId || officer.castleId === castleId) && (!spec.personalityId || profile.personalityIds.indexOf(spec.personalityId) >= 0) && (!spec.traitId || profile.traitIds.indexOf(spec.traitId) >= 0) && (!spec.tag || profile.tags.indexOf(spec.tag) >= 0);
    });
  }
  function randomItem(list, random) { if (!list.length) return null; var roll = random(); return validRandom(roll) ? list[Math.floor(roll * list.length)] : null; }
  function castlePower(castle) { return castle.troops + castle.defense * 15 + castle.morale; }
  function resolveOneSelector(state, spec, targets, payload, random) {
    var id, list, item, factionId = selectorValue(state, spec, targets, "factionId"), castleId = selectorValue(state, spec, targets, "castleId"), field;
    if (spec.type === "triggerOfficer") return targetRef("officer", state.officers[payload.triggerOfficerId || payload.officerId]);
    if (spec.type === "triggerCastle") return targetRef("castle", state.castles[payload.triggerCastleId || payload.castleId]);
    if (spec.type === "triggerFaction") return targetRef("faction", state.factions[payload.triggerFactionId || payload.factionId]);
    if (spec.type === "playerFaction") return targetRef("faction", state.factions[state.campaign.playerFactionId]);
    if (spec.type === "selectedCastle") return targetRef("castle", state.castles[state.campaign.selectedCastleId]);
    if (spec.type === "battleAttacker" || spec.type === "battleDefender") { var side = spec.type === "battleAttacker" ? "attacker" : "defender"; return targetRef(payload[side + "OfficerId"] ? "officer" : payload[side + "CastleId"] ? "castle" : "faction", state.officers[payload[side + "OfficerId"]] || state.castles[payload[side + "CastleId"]] || state.factions[payload[side + "FactionId"]]); }
    if (spec.type === "officerById") return targetRef("officer", state.officers[selectorValue(state, spec, targets, "id")]);
    if (spec.type === "castleById") return targetRef("castle", state.castles[selectorValue(state, spec, targets, "id")]);
    if (spec.type === "factionById") return targetRef("faction", state.factions[selectorValue(state, spec, targets, "id")]);
    if (spec.type === "randomPlayerCastle") list = Object.keys(state.castles).map(function (key) { return state.castles[key]; }).filter(function (castle) { return castle.factionId === state.campaign.playerFactionId; });
    else if (spec.type === "randomOfficer") list = officerCandidates(state, Object.assign({ activeOnly: true }, spec), targets);
    else if (["highestStatOfficer", "lowestStatOfficer", "highestLoyaltyOfficer", "lowestLoyaltyOfficer", "highestGrievanceOfficer"].indexOf(spec.type) >= 0) {
      list = officerCandidates(state, spec, targets); field = spec.type.indexOf("Stat") >= 0 ? function (officer) { return officer.stats[spec.stat || "leadership"]; } : spec.type.indexOf("Loyalty") >= 0 ? function (officer) { return officer.loyalty; } : function (officer) { return officer.grievance; };
      list.sort(function (a, b) { var delta = field(b) - field(a); return spec.type.indexOf("lowest") === 0 ? -delta : delta; }); return targetRef("officer", list[0]);
    } else if (spec.type === "castleGovernor") { var governorCastle = state.castles[castleId || selectorValue(state, spec, targets, "id")]; return targetRef("officer", governorCastle && state.officers[governorCastle.governorId]); }
    else if (spec.type === "randomPrisoner") list = state.prisoners.map(function (key) { return state.officers[key]; }).filter(function (officer) { return officer && (!factionId || officer.captorFactionId === factionId || officer.factionId === factionId); });
    else if (spec.type === "randomFactionCastle") list = Object.keys(state.castles).map(function (key) { return state.castles[key]; }).filter(function (castle) { return castle.factionId === factionId; });
    else if (spec.type === "weakestBorderCastle") { list = Object.keys(state.castles).map(function (key) { return state.castles[key]; }).filter(function (castle) { return castle.factionId === factionId && castle.neighbors.some(function (neighborId) { return state.castles[neighborId].factionId !== factionId; }); }).sort(function (a, b) { return castlePower(a) - castlePower(b); }); return targetRef("castle", list[0]); }
    else if (spec.type === "strongestCastle") { list = Object.keys(state.castles).map(function (key) { return state.castles[key]; }).filter(function (castle) { return !factionId || castle.factionId === factionId; }).sort(function (a, b) { return castlePower(b) - castlePower(a); }); return targetRef("castle", list[0]); }
    else if (spec.type === "recentlyCapturedCastle") { for (var reportIndex = state.events.battleReports.length - 1; reportIndex >= 0; reportIndex -= 1) { var report = state.events.battleReports[reportIndex]; if (report.result === "攻撃側勝利" && (!factionId || report.attackerFactionId === factionId)) return targetRef("castle", state.castles[report.targetId]); } return null; }
    else if (spec.type === "strongestFaction" || spec.type === "weakestFaction") { list = Object.keys(state.factions).map(function (key) { return state.factions[key]; }).filter(function (faction) { return faction.alive && (!spec.excludePlayer || faction.id !== state.campaign.playerFactionId); }).sort(function (a, b) { var delta = S.Systems.Diplomacy.power(state, b.id) - S.Systems.Diplomacy.power(state, a.id); return spec.type === "weakestFaction" ? -delta : delta; }); return targetRef("faction", list[0]); }
    else if (spec.type === "randomEnemyFaction") { list = Object.keys(state.factions).map(function (key) { return state.factions[key]; }).filter(function (faction) { return faction.alive && faction.id !== factionId && S.Systems.Diplomacy.status(state, factionId, faction.id) === "war"; }); }
    else if (spec.type === "diplomaticPartner") { list = Object.keys(state.factions).map(function (key) { return state.factions[key]; }).filter(function (faction) { var status = faction.id === factionId ? null : S.Systems.Diplomacy.status(state, factionId, faction.id); return faction.alive && status && (spec.status ? status === spec.status : status !== "war"); }); list.sort(function (a, b) { return S.Systems.Diplomacy.relation(state, factionId, b.id).score - S.Systems.Diplomacy.relation(state, factionId, a.id).score; }); return targetRef("faction", list[0]); }
    item = randomItem(list || [], random);
    if (!item) return null;
    return targetRef(state.officers[item.id] ? "officer" : state.castles[item.id] ? "castle" : "faction", item);
  }
  function resolveSelectors(state, definition, payload, random) {
    var selectors = definition.selectors || {}, targets = {}, visiting = {}, visited = {}, errors = [];
    function visit(name) { if (visited[name]) return true; if (visiting[name]) { errors.push("selector dependency cycle: " + name); return false; } var spec = selectors[name]; if (!isObject(spec)) { errors.push("selectorが存在しません: " + name); return false; } visiting[name] = true; var deps = dependencyNames(spec); for (var i = 0; i < deps.length; i += 1) if (!selectors[deps[i]] || !visit(deps[i])) { if (!selectors[deps[i]]) errors.push("selector dependencyが存在しません: " + deps[i]); return false; } targets[name] = resolveOneSelector(state, spec, targets, payload, random); if (!targets[name]) { errors.push("selector候補がありません: " + name); return false; } visiting[name] = false; visited[name] = true; return true; }
    Object.keys(selectors).forEach(function (name) { if (!errors.length) visit(name); });
    return { ok: errors.length === 0, targets: targets, errors: errors };
  }

  function findDefinition(eventId) { var found = null; (S.Data.ContentPackRegistry.order || []).some(function (packId) { var pack = S.Data.ContentPackRegistry.packs[packId]; return pack && pack.events.some(function (definition) { if (definition.id !== eventId) return false; found = Object.assign({ _packId: packId }, definition); return true; }); }); return found; }
  function stableKey(definition, state, payload, targets) { return definition.id + "|" + state.campaign.turn + "|" + JSON.stringify(payload || {}) + "|" + JSON.stringify(targets || {}); }
  function createInstance(state, definition, payload, random, depth) {
    depth = depth || 1; if (depth > LIMITS.chainDepth) { addDiagnostic(state, "chain_limit", "イベント連鎖上限12段に達しました", null); return { ok: false, errors: ["イベント連鎖上限12段に達しました"] }; }
    var selected = resolveSelectors(state, definition, payload, random); if (!selected.ok) { selected.errors.forEach(function (error) { addDiagnostic(state, error.indexOf("cycle") >= 0 ? "selector_cycle" : "selector_empty", error, null); }); return { ok: false, skipped: true, errors: selected.errors }; }
    var engine = state.events.engine, key = stableKey(definition, state, payload, selected.targets); if (engine.instanceKeys[key]) return { ok: true, duplicate: true, skipped: true, instanceId: engine.instanceKeys[key], errors: [] };
    var id = "evt-" + engine.nextInstanceId; engine.nextInstanceId += 1; engine.instanceKeys[key] = id; engine.metrics.maxChainDepth = Math.max(engine.metrics.maxChainDepth, depth);
    return { ok: true, instance: { instanceId: id, eventId: definition.id, packId: definition._packId, trigger: definition.trigger, createdTurn: state.campaign.turn, chainDepth: depth, targets: clone(selected.targets), payloadSnapshot: clone(payload || {}), availableChoices: clone(choicesOf(definition)), status: definition.blocking ? "queued" : "active", blocking: Boolean(definition.blocking), dedupeKey: key, selectedChoiceId: null, resultText: null }, errors: [] };
  }
  function addHistory(state, instance, definition, choice, result, status) { var entry = { instanceId: instance.instanceId, eventId: instance.eventId, packId: instance.packId, title: plainTemplate(state, instance, definition.title || definition.message || definition.id, {}).text, selectedChoiceId: choice ? choice.id : null, selectedChoiceLabel: choice ? plainTemplate(state, instance, choice.label, {}).text : null, result: result || "", turn: state.campaign.turn, date: dateLabel(state), targets: clone(instance.targets || {}), status: status }; state.events.engine.history.push(entry); while (state.events.engine.history.length > LIMITS.history) state.events.engine.history.shift(); return entry; }
  function cancelInstance(state, instance, code, reason) { instance.status = "cancelled"; addDiagnostic(state, code, reason, instance.instanceId); return addHistory(state, instance, findDefinition(instance.eventId) || { title: instance.eventId }, null, reason, "cancelled"); }
  function activateNext(state) { var engine = state.events.engine; if (engine.activeEvent) return engine.activeEvent; while (engine.queue.length) { var next = engine.queue.shift(); if (!findDefinition(next.eventId)) { cancelInstance(state, next, "event_definition_missing", "イベント定義が見つからないため取り消しました"); continue; } next.status = "active"; engine.activeEvent = next; return next; } return null; }
  function enqueueBlocking(state, instance) { var engine = state.events.engine; if (!engine.activeEvent) { instance.status = "active"; engine.activeEvent = instance; engine.metrics.queuedEvents += 1; return { ok: true, active: true, errors: [] }; } if (engine.queue.length >= LIMITS.queue) { delete engine.instanceKeys[instance.dedupeKey]; addDiagnostic(state, "queue_full", "イベントキュー上限50件に達しました", instance.instanceId); return { ok: false, errors: ["イベントキュー上限50件に達しました"] }; } instance.status = "queued"; engine.queue.push(instance); engine.metrics.queuedEvents += 1; engine.metrics.maxQueueLength = Math.max(engine.metrics.maxQueueLength, engine.queue.length); return { ok: true, active: false, errors: [] }; }
  function queueById(state, eventId, payload, random, depth) { var definition = findDefinition(eventId); if (!definition) { addDiagnostic(state, "event_reference_missing", "イベント定義が見つかりません: " + eventId, null); return { ok: false, errors: ["イベント定義が見つかりません: " + eventId] }; } if (!definition.blocking) return { ok: false, errors: ["queueEventはblockingイベントのみ対応します"] }; var created = createInstance(state, definition, payload || {}, random, depth || 1); if (!created.ok || created.skipped) return created; var queued = enqueueBlocking(state, created.instance); queued.instance = created.instance; return queued; }

  function plainTemplate(state, instance, template, values) { var diagnostics = [], text = String(template == null ? "" : template).replace(/\{\{\s*([a-zA-Z0-9_.]+)\s*\}\}/g, function (_, path) { var parts = path.split("."), root = parts.shift(), current = root === "campaign" ? state.campaign : root === "value" ? values || {} : instance && targetObject(state, instance.targets[root]); while (current != null && parts.length) current = current[parts.shift()]; if (current === undefined || current === null || typeof current === "object") { var message = "template参照が見つかりません: " + path; diagnostics.push(message); addDiagnostic(state, "template_missing", message, instance && instance.instanceId); return ""; } return String(current); }); return { text: text, diagnostics: diagnostics }; }
  function costAccount(state, instance, cost) { var factionId = cost.factionId || factionForInstance(state, instance); return cost.type === "factionResource" || factionId !== state.campaign.playerFactionId ? account(state, factionId) : state.campaign; }
  function costsAvailable(state, instance, costs) { for (var i = 0; i < (costs || []).length; i += 1) { var source = costAccount(state, instance, costs[i]); if (!source || source[costs[i].resource] < costs[i].amount) return { ok: false, reason: costs[i].resource === "gold" ? "金が不足しています" : "兵糧が不足しています" }; } return { ok: true, reason: "" }; }
  function choiceAvailability(state, instance, choice) { var condition = evaluateConditions(state, choice.conditions || [], instance); if (!condition.ok) return { enabled: false, reason: choice.disabledReason || condition.reason }; var costs = costsAvailable(state, instance, choice.costs || []); return costs.ok ? { enabled: true, reason: "" } : { enabled: false, reason: choice.disabledReason || costs.reason }; }
  function validateTargets(state, instance) { var missing = Object.keys(instance.targets || {}).filter(function (name) { return !targetObject(state, instance.targets[name]); }); return missing.length ? { ok: false, errors: ["イベントtargetが存在しません: " + missing.join(",")] } : { ok: true, errors: [] }; }

  function profileChange(state, officerId, kind, id, add) { var officer = state.officers[officerId]; if (!officer) return { ok: false, errors: ["武将が見つかりません"] }; var registry = kind === "personality" ? S.Data.PersonalityRegistry : kind === "trait" ? S.Data.TraitRegistry : null, field = kind === "personality" ? "personalityIds" : kind === "trait" ? "traitIds" : "tags"; if (registry && !registry.definitions[id]) return { ok: false, errors: ["未登録の" + kind + " IDです: " + id] }; var list = officer.profile[field]; if (add && list.indexOf(id) < 0) list.push(id); if (!add) officer.profile[field] = list.filter(function (item) { return item !== id; }); return { ok: true, stateChanges: { officerId: officerId, field: field }, errors: [], messages: [] }; }
  function arcDefinition(id) { return S.Data.StoryArcRegistry.definitions[id] || null; }
  function recordArc(state, arc, action, message) { var definition = arcDefinition(arc.arcId) || { packId: "unknown", name: arc.arcId }; addHistory(state, { instanceId: "arc-" + arc.arcId + "-" + state.campaign.turn + "-" + action, eventId: "arc:" + arc.arcId, packId: definition.packId || definition._packId || "unknown", targets: {}, status: "resolved" }, { title: definition.name || arc.arcId }, { id: action, label: action }, message, "resolved"); addDiagnostic(state, "arc_" + action, message, null); }
  E.Arc = {
    register: function (definition, packId) { var result = validateArcDefinition(Object.assign({}, definition, { packId: definition.packId || packId })); if (!result.ok) return result; if (S.Data.StoryArcRegistry.definitions[definition.id]) return { ok: false, errors: ["Story Arcは登録済みです: " + definition.id] }; var stored = clone(Object.assign({}, definition, { packId: definition.packId || packId || "manual" })); S.Data.StoryArcRegistry.manualDefinitions[definition.id] = stored; S.Data.StoryArcRegistry.definitions[definition.id] = stored; S.Data.StoryArcRegistry.order.push(definition.id); return { ok: true, errors: [] }; },
    start: function (state, arcId) { var definition = arcDefinition(arcId), current = state.events.engine.arcs[arcId]; if (!definition) return { ok: false, errors: ["Story Arcが見つかりません: " + arcId] }; if (current && current.status !== "inactive") return { ok: false, errors: ["Story Arcは開始済みです: " + arcId] }; var arc = { arcId: arcId, status: "active", currentStep: definition.initialStep, completedSteps: [], startedTurn: state.campaign.turn, updatedTurn: state.campaign.turn, completedTurn: null, failedTurn: null }; state.events.engine.arcs[arcId] = arc; state.events.engine.metrics.arcStarts += 1; recordArc(state, arc, "start", (definition.name || arcId) + "を開始しました"); return { ok: true, stateChanges: clone(arc), errors: [], messages: [] }; },
    setStep: function (state, arcId, stepId) { var definition = arcDefinition(arcId), arc = state.events.engine.arcs[arcId]; if (!definition || !arc || arc.status !== "active") return { ok: false, errors: ["進行中のStory Arcではありません"] }; if (!definition.steps[stepId]) return { ok: false, errors: ["Story Arc stepが不明です: " + stepId] }; if (arc.currentStep && arc.completedSteps.indexOf(arc.currentStep) < 0) arc.completedSteps.push(arc.currentStep); arc.currentStep = stepId; arc.updatedTurn = state.campaign.turn; recordArc(state, arc, "step", (definition.name || arcId) + "を" + stepId + "へ進めました"); return { ok: true, stateChanges: clone(arc), errors: [], messages: [] }; },
    advance: function (state, arcId) { var definition = arcDefinition(arcId), arc = state.events.engine.arcs[arcId]; if (!definition || !arc || arc.status !== "active") return { ok: false, errors: ["進行中のStory Arcではありません"] }; var step = definition.steps[arc.currentStep], next = step && (step.nextStep || step.nextStepId); if (!next) return E.Arc.complete(state, arcId); return E.Arc.setStep(state, arcId, next); },
    complete: function (state, arcId) { var arc = state.events.engine.arcs[arcId], definition = arcDefinition(arcId); if (!arc || arc.status !== "active") return { ok: false, errors: ["進行中のStory Arcではありません"] }; if (arc.currentStep && arc.completedSteps.indexOf(arc.currentStep) < 0) arc.completedSteps.push(arc.currentStep); arc.status = "completed"; arc.updatedTurn = state.campaign.turn; arc.completedTurn = state.campaign.turn; state.events.engine.metrics.arcCompletions += 1; recordArc(state, arc, "complete", (definition.name || arcId) + "を完了しました"); return { ok: true, stateChanges: clone(arc), errors: [], messages: [] }; },
    fail: function (state, arcId) { var arc = state.events.engine.arcs[arcId], definition = arcDefinition(arcId); if (!arc || arc.status !== "active") return { ok: false, errors: ["進行中のStory Arcではありません"] }; arc.status = "failed"; arc.updatedTurn = state.campaign.turn; arc.failedTurn = state.campaign.turn; recordArc(state, arc, "fail", (definition.name || arcId) + "が失敗しました"); return { ok: true, stateChanges: clone(arc), errors: [], messages: [] }; }
  };
  E.Profile = { addPersonality: function (state, officerId, id) { return profileChange(state, officerId, "personality", id, true); }, removePersonality: function (state, officerId, id) { return profileChange(state, officerId, "personality", id, false); }, addTrait: function (state, officerId, id) { return profileChange(state, officerId, "trait", id, true); }, removeTrait: function (state, officerId, id) { return profileChange(state, officerId, "trait", id, false); }, addTag: function (state, officerId, id) { return profileChange(state, officerId, "tag", id, true); }, removeTag: function (state, officerId, id) { return profileChange(state, officerId, "tag", id, false); } };
  function registerProfileDefinition(registry, definition) { if (!isObject(definition) || !validId(definition.id) || containsExecutable(definition) || containsRawHtml(definition)) return { ok: false, errors: ["profile定義が不正です"] }; if (registry.definitions[definition.id]) return { ok: false, errors: ["profile定義が重複しています: " + definition.id] }; registry.definitions[definition.id] = clone(definition); registry.order.push(definition.id); return { ok: true, errors: [], messages: [], stateChanges: { id: definition.id } }; }
  E.Profile.registerPersonality = function (definition) { return registerProfileDefinition(S.Data.PersonalityRegistry, definition); };
  E.Profile.registerTrait = function (definition) { return registerProfileDefinition(S.Data.TraitRegistry, definition); };

  function systemResult(result) { return result && result.ok ? null : result && result.errors && result.errors[0] || "System処理に失敗しました"; }
  function applyEffect(state, instance, effect, values, random) {
    var engine = state.events.engine, officerId = idFrom(state, instance, effect, "officer"), castleId = idFrom(state, instance, effect, "castle"), factionId = idFrom(state, instance, effect, "faction"), officer = state.officers[officerId], castle = state.castles[castleId], result, amount, pair, relation, rivalry, text;
    if (effect.type === "setFlag") state.events.flags[effect.flag || effect.key] = clone(effect.value);
    else if (effect.type === "clearFlag") delete state.events.flags[effect.flag || effect.key];
    else if (effect.type === "setVariable") engine.variables[effect.variable || effect.key] = clone(effect.value);
    else if (effect.type === "addVariable") engine.variables[effect.variable || effect.key] = (engine.variables[effect.variable || effect.key] || 0) + amountOf(effect, 0);
    else if (effect.type === "setCounter") engine.counters[effect.counter || effect.key] = amountOf(effect, 0);
    else if (effect.type === "addCounter") engine.counters[effect.counter || effect.key] = (engine.counters[effect.counter || effect.key] || 0) + amountOf(effect, 0);
    else if (effect.type === "setCooldown") engine.cooldowns[effect.cooldown || effect.key] = Number.isInteger(effect.untilTurn) ? effect.untilTurn : state.campaign.turn + Math.max(0, Math.floor(effect.duration || effect.turns || 0));
    else if (effect.type === "clearCooldown") delete engine.cooldowns[effect.cooldown || effect.key];
    else if (effect.type === "queueEvent") { result = queueById(state, effect.eventId, effect.payload || instance.payloadSnapshot, random, instance.chainDepth + 1); if (!result.ok && !result.duplicate) return result.errors[0]; }
    else if (effect.type === "cancelEvent") { var cancelId = effect.instanceId || null, removed = false; if (engine.activeEvent && engine.activeEvent.instanceId !== instance.instanceId && (!cancelId || engine.activeEvent.instanceId === cancelId || engine.activeEvent.eventId === effect.eventId)) { cancelInstance(state, engine.activeEvent, "event_cancelled", "イベント効果で取り消しました"); engine.activeEvent = null; removed = true; } engine.queue = engine.queue.filter(function (item) { var match = (!cancelId || item.instanceId === cancelId) && (!effect.eventId || item.eventId === effect.eventId); if (match) { cancelInstance(state, item, "event_cancelled", "イベント効果で取り消しました"); removed = true; } return !match; }); if (!removed) return "取消対象イベントがありません"; }
    else if (effect.type === "campaignResource") { amount = finite(effect.amount) ? effect.amount : effect.formula.base + effect.formula.perPlayerCastle * E.playerCastles(state).length; state.campaign[effect.resource] = applyNumber(state.campaign[effect.resource], Object.assign({}, effect, { amount: amount }), 0, Number.MAX_SAFE_INTEGER); if (effect.storeAs) values[effect.storeAs] = amount; }
    else if (effect.type === "consumeCommand") { amount = Math.max(1, amountOf(effect, 1)); if (state.campaign.commands < amount) return "命令回数が不足しています"; state.campaign.commands -= amount; }
    else if (effect.type === "restoreCommand") state.campaign.commands = Math.min(state.campaign.maxCommands, state.campaign.commands + Math.max(1, amountOf(effect, 1)));
    else if (effect.type === "factionResource") { var factionAccount = account(state, factionId); if (!factionAccount) return "勢力資源対象が不正です"; factionAccount[effect.resource] = applyNumber(factionAccount[effect.resource], effect, 0, Number.MAX_SAFE_INTEGER); }
    else if (effect.type === "factionReputation") state.diplomacy.reputation[factionId] = applyNumber(state.diplomacy.reputation[factionId], effect, 0, 100);
    else if (effect.type === "warExhaustion") state.diplomacy.warExhaustion[factionId] = applyNumber(state.diplomacy.warExhaustion[factionId], effect, 0, 100);
    else if (["castleTroops", "castleMorale", "castleDefense", "castleDevelopment"].indexOf(effect.type) >= 0) { if (!castle) return "城効果対象が不正です"; var field = effect.type === "castleTroops" ? "troops" : effect.type === "castleMorale" ? "morale" : effect.type === "castleDefense" ? "defense" : (castle.development !== undefined ? "development" : "income"); var nextCastleValue = applyNumber(castle[field], effect, finite(effect.minimum) ? effect.minimum : 0, finite(effect.maximum) ? effect.maximum : field === "morale" ? 100 : Number.MAX_SAFE_INTEGER); if (field === "troops" && S.Systems.Unit) S.Systems.Unit.setGuardTroops(state, castle, nextCastleValue); else castle[field] = nextCastleValue; }
    else if (effect.type === "castleOwner") { result = S.Systems.Campaign.transferCastle(state, castleId, effect.newFactionId || effect.ownerFactionId || factionId); if ((text = systemResult(result))) return text; }
    else if (effect.type === "officerStat") { if (!officer || !officer.stats.hasOwnProperty(effect.stat)) return "武将能力対象が不正です"; officer.stats[effect.stat] = applyNumber(officer.stats[effect.stat], effect, 0, 100); }
    else if (effect.type === "officerLoyalty") { result = S.Systems.Loyalty.change(state, officerId, amountOf(effect, 0), effect.reason || "イベントによる忠誠変化"); if ((text = systemResult(result))) return text; }
    else if (effect.type === "officerGrievance") officer.grievance = applyNumber(officer.grievance, effect, 0, 100);
    else if (effect.type === "officerLordTrust") officer.lordTrust = applyNumber(officer.lordTrust, effect, 0, 100);
    else if (effect.type === "officerMerit") { result = S.Systems.Officer.gainMerit(state, officerId, amountOf(effect, 0), effect.reason || ""); if ((text = systemResult(result))) return text; }
    else if (effect.type === "officerExperience") { officer.exp = Math.max(0, officer.exp + amountOf(effect, 0)); result = S.Systems.Officer.gainMerit(state, officerId, 0, ""); if ((text = systemResult(result))) return text; }
    else if (effect.type === "officerInjury") { if (!officer) return "武将対象が不正です"; officer.injury = effect.injury || effect.value || "軽傷"; officer.health = Math.min(officer.health, officer.injury === "重傷" ? 55 : 78); }
    else if (effect.type === "officerRecover") { result = S.Systems.Officer.rest(state, officerId); if ((text = systemResult(result))) return text; }
    else if (effect.type === "officerMove") { result = S.Systems.Officer.moveOfficer(state, officerId, effect.targetCastleId || castleId, { consumeCommand: false, silent: true }); if ((text = systemResult(result))) return text; }
    else if (effect.type === "officerAppointGovernor") { result = S.Systems.Officer.assignGovernor(state, officerId, castleId, { consumeCommand: false }); if ((text = systemResult(result))) return text; }
    else if (effect.type === "officerStatus") { var nextStatus = effect.status || effect.value; if (!officer) return "武将対象が不正です"; if (nextStatus === "prisoner") result = S.Systems.Prisoner.capture(state, officerId, effect.captorFactionId || factionId); else if (officer.status === "prisoner" && nextStatus === "active") result = S.Systems.Prisoner.release(state, officerId, "イベント"); else { S.Systems.Officer.clearGovernorAssignments(state, officerId, null); officer.status = nextStatus; if (nextStatus !== "active") { officer.castleId = null; officer.assignment = { type: "idle", castleId: null, armyId: null }; } else { var statusCastle = state.castles[effect.targetCastleId || castleId] || Object.keys(state.castles).map(function (id) { return state.castles[id]; }).find(function (item) { return item.factionId === (effect.newFactionId || officer.factionId); }); if (!statusCastle) return "active武将の配属城がありません"; officer.factionId = statusCastle.factionId; officer.castleId = statusCastle.id; officer.assignment = { type: "idle", castleId: statusCastle.id, armyId: null }; } result = { ok: true }; } if ((text = systemResult(result))) return text; }
    else if (effect.type.indexOf("officerAdd") === 0 || effect.type.indexOf("officerRemove") === 0) { var adding = effect.type.indexOf("officerAdd") === 0, kind = effect.type.indexOf("Personality") >= 0 ? "personality" : effect.type.indexOf("Trait") >= 0 ? "trait" : "tag", profileId = effect.personalityId || effect.traitId || effect.tag || effect.value; result = profileChange(state, officerId, kind, profileId, adding); if ((text = systemResult(result))) return text; }
    else if (effect.type === "officerPromise") officer.promise = effect.promise === null ? null : clone(effect.promise || { type: effect.promiseType || "event", text: effect.text || "", madeTurn: state.campaign.turn, dueTurn: state.campaign.turn + (effect.duration || 2), status: effect.status || "pending" });
    else if (effect.type === "officerRelationship") { var officerA = effect.aId || idFrom(state, instance, { target: effect.aTarget || "officerA" }, "officer"), officerB = effect.bId || idFrom(state, instance, { target: effect.bTarget || "officerB" }, "officer"); result = S.Systems.Relationship.change(state, officerA, officerB, amountOf(effect, 0), effect.memory || null); if ((text = systemResult(result))) return text; }
    else if (effect.type === "addRelationshipMemory") { text = plainTemplate(state, instance, effect.text || "", values).text; state.relationships.memories.push({ turn: state.campaign.turn, officerAId: effect.aId, officerBId: effect.bId, text: text }); if (effect.aId) S.Systems.Officer.remember(state, effect.aId, text, Boolean(effect.important)); if (effect.bId) S.Systems.Officer.remember(state, effect.bId, text, Boolean(effect.important)); }
    else if (effect.type.indexOf("rivalry") === 0) { var rivalA = effect.aId || idFrom(state, instance, { target: effect.aTarget || "officerA" }, "officer"), rivalB = effect.bId || idFrom(state, instance, { target: effect.bTarget || "officerB" }, "officer"); rivalry = S.Systems.Rivalry.get(state, rivalA, rivalB, true); if (!rivalry) return "因縁対象が不正です"; if (effect.type === "rivalryRespect") rivalry.respect = Math.max(0, rivalry.respect + amountOf(effect, 0)); else if (effect.type === "rivalryResentment") rivalry.resentment = Math.max(0, rivalry.resentment + amountOf(effect, 0)); else rivalry.encounters += Math.max(1, amountOf(effect, 1)); }
    else if (effect.type === "releasePrisoner") { result = S.Systems.Prisoner.release(state, officerId, effect.reason || "イベント"); if ((text = systemResult(result))) return text; }
    else if (effect.type === "recruitPrisoner") { result = S.Systems.Prisoner.recruit(state, officerId, effect.recruiterId, true, random, effect.method); if ((text = systemResult(result))) return text; }
    else if (effect.type === "exchangePrisoner") { pair = relationPair(state, instance, effect); result = S.Systems.Diplomacy.exchangePrisoners(state, pair.a, pair.b); if ((text = systemResult(result))) return text; }
    else if (["diplomacyScore", "diplomacyTrust", "diplomacyGrievance"].indexOf(effect.type) >= 0) { pair = relationPair(state, instance, effect); var changes = {}; changes[effect.type.replace("diplomacy", "").replace(/^./, function (char) { return char.toLowerCase(); })] = amountOf(effect, 0); result = S.Systems.Diplomacy.changeRelation(state, pair.a, pair.b, changes); if ((text = systemResult(result))) return text; }
    else if (["declareWar", "makePeace", "createCeasefire", "createNonAggression", "createAlliance", "breakTreaty", "createVassalage", "releaseVassal"].indexOf(effect.type) >= 0) { pair = relationPair(state, instance, effect); var diplomacyOptions = { forceAccept: true, ignoreTiming: true, ignoreWarLimit: true, autoResolvePlayer: true, random: random, duration: effect.duration }; if (effect.type === "declareWar") result = S.Systems.Diplomacy.declareWar(state, pair.a, pair.b, diplomacyOptions); else if (effect.type === "makePeace") result = S.Systems.Diplomacy.makePeace(state, pair.a, pair.b, diplomacyOptions); else if (effect.type === "createCeasefire") result = S.Systems.Diplomacy.makeCeasefire(state, pair.a, pair.b, diplomacyOptions); else if (effect.type === "createNonAggression") result = S.Systems.Diplomacy.makeNonAggression(state, pair.a, pair.b, diplomacyOptions); else if (effect.type === "createAlliance") result = S.Systems.Diplomacy.makeAlliance(state, pair.a, pair.b, diplomacyOptions); else if (effect.type === "breakTreaty") result = S.Systems.Diplomacy.breakTreaty(state, pair.a, pair.b, diplomacyOptions); else if (effect.type === "createVassalage") result = S.Systems.Diplomacy.vassalize(state, pair.a, pair.b, {}); else result = S.Systems.Diplomacy.releaseVassal(state, pair.a, pair.b); if ((text = systemResult(result))) return text; }
    else if (effect.type === "addLog") E.addLog(state, plainTemplate(state, instance, effect.text, values).text, effect.logType || "");
    else if (effect.type === "addChronicle") E.addChronicle(state, plainTemplate(state, instance, effect.text, values).text);
    else if (effect.type === "addOfficerHistory") { if (!S.Systems.Officer.remember(state, officerId, plainTemplate(state, instance, effect.text, values).text, effect.important)) return "武将履歴対象が不正です"; }
    else if (effect.type === "addDiplomacyHistory") { pair = relationPair(state, instance, effect); S.Systems.Diplomacy.history(state, effect.historyType || "event", pair.a, pair.b, plainTemplate(state, instance, effect.text, values).text, effect.details || {}); }
    else if (effect.type === "addBattleMemory") { if (!S.Systems.Officer.remember(state, officerId, plainTemplate(state, instance, effect.text, values).text, true)) return "合戦記憶対象が不正です"; }
    else if (effect.type === "startArc") result = E.Arc.start(state, effect.arcId);
    else if (effect.type === "advanceArc") result = E.Arc.advance(state, effect.arcId);
    else if (effect.type === "setArcStep") result = E.Arc.setStep(state, effect.arcId, effect.stepId);
    else if (effect.type === "completeArc") result = E.Arc.complete(state, effect.arcId);
    else if (effect.type === "failArc") result = E.Arc.fail(state, effect.arcId);
    else if (["requestBattlePlanner", "requestOfficerSelection", "requestCastleSelection", "requestFactionSelection"].indexOf(effect.type) >= 0) { if (engine.pendingInteraction) return "別のイベントinteractionが進行中です"; var interaction = { type: effect.type, instanceId: instance.instanceId, prompt: effect.prompt || "選択してください" }; if (effect.type === "requestBattlePlanner") { var source = valueFromTarget(state, instance, effect.sourceTarget); interaction.sourceId = source && source.id; interaction.targetId = effect.targetId; interaction.opening = Boolean(effect.opening); interaction.preset = clone(effect.preset || {}); } else interaction.options = clone(effect.options || {}); engine.pendingInteraction = interaction; }
    if (result && (text = systemResult(result))) return text;
    return null;
  }
  function preflightEffect(state, instance, effect) { var working = clone(state), workingInstance = clone(instance), error; try { error = applyEffect(working, workingInstance, effect, {}, normalizeRandom(working, function () { return 0.5; })); } catch (exception) { return "effect preflight例外: " + exception.message; } return error; }
  function commitState(state, working) { Object.keys(state).forEach(function (key) { delete state[key]; }); Object.keys(working).forEach(function (key) { state[key] = working[key]; }); }
  function resolveTransaction(state, instance, choiceId, standalone, options) {
    options = options || {}; if (state.events.engine.history.some(function (entry) { return entry.instanceId === instance.instanceId && entry.status === "resolved"; })) return { ok: false, errors: ["このイベント選択は既に実行されています"] };
    var definition = findDefinition(instance.eventId); if (!definition) return { ok: false, errors: ["イベント定義が見つかりません"] };
    var choices = instance.availableChoices || choicesOf(definition), choice = choices.find(function (item) { return item.id === choiceId; });
    if (!choice && (choiceId === null || choiceId === undefined)) choice = choices.find(function (item) { return (item.fallback || definition.fallbackChoiceId === item.id) && choiceAvailability(state, instance, item).enabled; });
    if (!choice) return { ok: false, errors: ["イベント選択肢が見つかりません"] };
    var targetValidation = validateTargets(state, instance); if (!targetValidation.ok) return targetValidation; var eventCondition = evaluateConditions(state, conditionsOf(definition), instance); if (!eventCondition.ok) return { ok: false, errors: [eventCondition.reason] }; var availability = choiceAvailability(state, instance, choice); if (!availability.enabled) return { ok: false, errors: [availability.reason] };
    var effects = choice.effects || [], preflightErrors = [], preflightState = clone(state), preflightInstance = clone(instance), preflightValues = {}, preflightRandom = normalizeRandom(preflightState, function () { return 0.5; }); effects.forEach(function (effect) { if (preflightErrors.length) return; var error; try { error = applyEffect(preflightState, preflightInstance, effect, preflightValues, preflightRandom); } catch (exception) { error = "effect preflight例外: " + exception.message; } if (error) preflightErrors.push(error); }); if (choice.nextEventId && (!findDefinition(choice.nextEventId) || !findDefinition(choice.nextEventId).blocking)) preflightErrors.push("nextEventIdのblockingイベント定義がありません: " + choice.nextEventId); if (preflightErrors.length) return { ok: false, errors: preflightErrors };
    var working = clone(state), workingInstance = standalone ? clone(instance) : working.events.engine.activeEvent, values = {}, random = normalizeRandom(working, options.random || options.rng); (choice.costs || []).forEach(function (cost) { costAccount(working, workingInstance, cost)[cost.resource] -= cost.amount; });
    for (var i = 0; i < effects.length; i += 1) { var error = applyEffect(working, workingInstance, effects[i], values, random); if (error) return { ok: false, errors: [error] }; }
    if (choice.nextEventId) { var queued = queueById(working, choice.nextEventId, workingInstance.payloadSnapshot, random, workingInstance.chainDepth + 1); if (!queued.ok && !queued.duplicate) return { ok: false, errors: queued.errors }; }
    var resultText = plainTemplate(working, workingInstance, choice.resultText || definition.message || "", values).text; workingInstance.status = "resolved"; workingInstance.selectedChoiceId = choice.id; workingInstance.resultText = resultText; workingInstance.resolvedTurn = working.campaign.turn;
    if (working.events.triggeredIds.indexOf(definition.id) < 0) working.events.triggeredIds.push(definition.id); if (definition.once) working.events.engine.onceKeys[definition.id] = true; working.events.engine.firedEventIds[definition.id] = (working.events.engine.firedEventIds[definition.id] || 0) + 1; var historyEntry = addHistory(working, workingInstance, definition, choice, resultText, "resolved");
    if (!standalone) { working.events.engine.activeEvent = null; activateNext(working); }
    if (options.ai) { working.events.engine.metrics.automaticResolutions += 1; working.events.engine.metrics.aiChoiceDistribution[choice.id] = (working.events.engine.metrics.aiChoiceDistribution[choice.id] || 0) + 1; if (choice.important && factionForInstance(working, workingInstance) !== working.campaign.playerFactionId) working.events.defenseNotifications.push({ title: definition.title || definition.id, text: resultText }); }
    var validation = S.State.validateState(working); if (!validation.ok) return { ok: false, errors: ["イベント効果をロールバックしました"].concat(validation.errors) }; commitState(state, working); return { ok: true, stateChanges: { instanceId: instance.instanceId, choiceId: choice.id, resultText: resultText, historyEntry: historyEntry, interaction: clone(state.events.engine.pendingInteraction), activeEvent: clone(state.events.engine.activeEvent), ai: Boolean(options.ai) }, messages: resultText ? [resultText] : [], errors: [] };
  }
  function aiModifier(state, instance, choice) { var factionId = factionForInstance(state, instance), source = account(state, factionId), weight = finite(choice.aiWeight) ? Math.max(0, choice.aiWeight) : 1, costs = choice.costs || [], exhaustion = state.diplomacy.warExhaustion[factionId] || 0, wars = S.Systems.Diplomacy.warsFor(state, factionId).length, difficulty = state.campaign.difficultyId; if (costs.length && source) weight *= source.gold + source.food < 100 ? 0.85 : 1.03; if (wars) weight *= choice.aiTags && choice.aiTags.indexOf("peace") >= 0 ? 1.08 : 0.98; if (exhaustion > 65) weight *= choice.aiTags && choice.aiTags.indexOf("peace") >= 0 ? 1.12 : 0.94; weight *= difficulty === "hard" ? 1.03 : difficulty === "easy" ? 0.98 : 1; Object.keys(instance.targets || {}).forEach(function (name) { var ref = instance.targets[name], officer = ref.type === "officer" && state.officers[ref.id]; if (!officer) return; weight *= officer.loyalty < 40 ? 0.96 : 1.01; officer.profile.personalityIds.concat(officer.profile.traitIds).forEach(function (id) { var definition = S.Data.PersonalityRegistry.definitions[id] || S.Data.TraitRegistry.definitions[id]; if (definition && definition.aiChoiceModifiers && finite(definition.aiChoiceModifiers[choice.id])) weight *= definition.aiChoiceModifiers[choice.id]; }); }); return Math.max(0, weight); }
  function chooseAI(state, instance, options) { var definition = findDefinition(instance.eventId), available = (instance.availableChoices || []).filter(function (choice) { return !choice.fallback && choiceAvailability(state, instance, choice).enabled; }), random = normalizeRandom(state, options && (options.random || options.rng)); if (!available.length) { var fallbackId = definition.fallbackChoiceId, fallback = (instance.availableChoices || []).find(function (choice) { return choice.id === fallbackId || !fallbackId && choice.fallback; }); return fallback && choiceAvailability(state, instance, fallback).enabled ? fallback : null; } var weights = available.map(function (choice) { return aiModifier(state, instance, choice); }), total = weights.reduce(function (sum, value) { return sum + value; }, 0), roll = random(); if (!validRandom(roll)) return null; if (total <= 0) return available[0]; var cursor = roll * total; for (var i = 0; i < available.length; i += 1) { cursor -= weights[i]; if (cursor <= 0) return available[i]; } return available[available.length - 1]; }
  function processDefinition(state, definition, payload, random) { var allConditions = conditionsOf(definition), earlyConditions = allConditions.filter(function (item) { return !conditionNeedsInstance(item); }), condition = evaluateConditions(state, earlyConditions, null); if (!condition.ok) return { ok: true, skipped: true, errors: [] }; if (definition.once && (state.events.engine.onceKeys[definition.id] || state.events.triggeredIds.indexOf(definition.id) >= 0)) return { ok: true, skipped: true, errors: [] }; if (state.events.engine.cooldowns[definition.id] > state.campaign.turn) return { ok: true, skipped: true, errors: [] }; var roll = random(); if (!validRandom(roll)) return { ok: false, errors: ["イベントRNGが0以上1未満の数値を返しません"] }; if (roll >= definition.chance) return { ok: true, skipped: true, errors: [] }; var created = createInstance(state, definition, payload, random, 1); if (!created.ok || created.skipped) return created; condition = evaluateConditions(state, allConditions, created.instance); if (!condition.ok) { delete state.events.engine.instanceKeys[created.instance.dedupeKey]; return { ok: true, skipped: true, errors: [] }; } state.events.engine.metrics.matchedEvents += 1; var aiFaction = factionForInstance(state, created.instance), isAI = definition.blocking && aiFaction !== state.campaign.playerFactionId; if (isAI) { var aiChoice = chooseAI(state, created.instance, { random: random }); if (!aiChoice) { addDiagnostic(state, "ai_choice_unavailable", "AIが選べるイベント選択肢がありません", created.instance.instanceId); return { ok: false, errors: ["AIが選べるイベント選択肢がありません"] }; } var aiResult = resolveTransaction(state, created.instance, aiChoice.id, true, { ai: true, random: random }); aiResult.instance = created.instance; return aiResult; } if (definition.blocking) { var enqueued = enqueueBlocking(state, created.instance); return enqueued.ok ? { ok: true, instance: created.instance, queued: !enqueued.active, messages: [], errors: [] } : enqueued; } var resolved = resolveTransaction(state, created.instance, null, true, { random: random }); resolved.instance = created.instance; return resolved; }

  function validateCondition(condition, label) { if (!isObject(condition) || conditionTypes.indexOf(condition.type) < 0) return "未対応のconditionです: " + label; if (condition.operator !== undefined && operators.indexOf(condition.operator) < 0) return "condition operatorが不正です: " + label; if (condition.type === "all" || condition.type === "any") { if (!Array.isArray(condition.conditions) || !condition.conditions.length) return "logical conditionが不正です: " + label; for (var i = 0; i < condition.conditions.length; i += 1) { var nested = validateCondition(condition.conditions[i], label); if (nested) return nested; } } if (condition.type === "not") return validateCondition(condition.condition || (condition.conditions || [])[0], label); return null; }
  function validateEffect(effect, label) { if (!isObject(effect) || effectTypes.indexOf(effect.type) < 0) return "未対応のevent effectです: " + label; if ((effect.type.indexOf("add") === 0 || effect.type === "addLog" || effect.type === "addChronicle") && effect.text !== undefined && hasRawHtml(effect.text)) return "event effect textが不正です: " + label; return null; }
  function validateArcDefinition(definition) { var errors = []; if (!isObject(definition) || !validId(definition.id)) return { ok: false, errors: ["Story Arc IDが不正です"] }; if (containsExecutable(definition) || containsRawHtml(definition)) errors.push("Story Arcに安全でないデータがあります: " + definition.id); if (!isObject(definition.steps) || !definition.steps[definition.initialStep]) errors.push("Story Arc initialStepが不正です: " + definition.id); var visiting = {}, visited = {}; function visit(stepId) { if (visiting[stepId]) { errors.push("Story Arc step cycle: " + definition.id); return; } if (visited[stepId]) return; var step = definition.steps[stepId], next = step && (step.nextStep || step.nextStepId); if (!step) { errors.push("Story Arc stepが存在しません: " + stepId); return; } visiting[stepId] = true; if (next) { if (!definition.steps[next]) errors.push("Story Arc next stepが存在しません: " + next); else visit(next); } visiting[stepId] = false; visited[stepId] = true; } if (isObject(definition.steps)) Object.keys(definition.steps).forEach(visit); return { ok: errors.length === 0, errors: errors }; }
  function eventReferences(definition) { var refs = []; choicesOf(definition).forEach(function (choice) { if (choice.nextEventId) refs.push(choice.nextEventId); (choice.effects || []).forEach(function (effect) { if (effect.type === "queueEvent" && effect.eventId) refs.push(effect.eventId); }); }); return refs; }
  E.validateDefinition = function (definition) { var errors = []; if (!isObject(definition)) return { ok: false, errors: ["イベント定義がオブジェクトではありません"] }; if (containsExecutable(definition)) errors.push("イベント定義に実行可能な値を使用できません"); if (containsRawHtml(definition)) errors.push("イベント定義にraw HTMLを使用できません"); if (!validId(definition.id)) errors.push("イベントIDが不正です"); if (triggerValues.indexOf(definition.trigger) < 0) errors.push("イベントtriggerが不正です: " + definition.id); if (!finite(definition.chance) || definition.chance < 0 || definition.chance > 1) errors.push("イベントchanceが不正です: " + definition.id); if (Object.keys(definition.selectors || {}).length > LIMITS.selectors) errors.push("selector上限20件を超えています: " + definition.id); Object.keys(definition.selectors || {}).forEach(function (name) { var selector = definition.selectors[name]; if (!isObject(selector) || selectorTypes.indexOf(selector.type) < 0) errors.push("selectorが不正です: " + definition.id + "." + name); }); conditionsOf(definition).forEach(function (condition) { var error = validateCondition(condition, definition.id); if (error) errors.push(error); }); var choices = choicesOf(definition), ids = {}, fallback = 0; if (choices.length > LIMITS.choices) errors.push("choice上限12件を超えています: " + definition.id); choices.forEach(function (choice) { if (!isObject(choice) || !validId(choice.id) || ids[choice.id]) errors.push("choice IDが不正または重複しています: " + definition.id); else ids[choice.id] = true; if (choice.fallback) fallback += 1; if (!Array.isArray(choice.effects)) errors.push("choice effectsが配列ではありません: " + definition.id); else { if (choice.effects.length > LIMITS.effects) errors.push("effect上限30件を超えています: " + definition.id); choice.effects.forEach(function (effect) { var error = validateEffect(effect, definition.id + "." + choice.id); if (error) errors.push(error); }); } (choice.conditions || []).forEach(function (condition) { var error = validateCondition(condition, definition.id + "." + choice.id); if (error) errors.push(error); }); (choice.costs || []).forEach(function (cost) { if (!isObject(cost) || ["campaignResource", "factionResource"].indexOf(cost.type) < 0 || ["gold", "food"].indexOf(cost.resource) < 0 || !finite(cost.amount) || cost.amount < 0) errors.push("choice costが不正です: " + definition.id); }); }); if (fallback > 1) errors.push("fallback choiceが重複しています: " + definition.id); if (definition.fallbackChoiceId && !ids[definition.fallbackChoiceId]) errors.push("fallbackChoiceIdが不正です: " + definition.id); var selectorValidation = resolveSelectorGraph(definition.selectors || {}); errors = errors.concat(selectorValidation.errors); return { ok: errors.length === 0, errors: errors }; };
  function resolveSelectorGraph(selectors) { var errors = [], visiting = {}, visited = {}; function visit(name) { if (visiting[name]) { errors.push("selector dependency cycle: " + name); return; } if (visited[name]) return; visiting[name] = true; dependencyNames(selectors[name]).forEach(function (dependency) { if (!selectors[dependency]) errors.push("selector dependencyが存在しません: " + dependency); else visit(dependency); }); visiting[name] = false; visited[name] = true; } Object.keys(selectors).forEach(visit); return { ok: !errors.length, errors: errors }; }
  E.validateContentPack = function (pack) { var errors = [], eventIds = {}, arcIds = {}; if (!isObject(pack)) return { ok: false, errors: ["Content Packがオブジェクトではありません"] }; if (containsExecutable(pack)) errors.push("Content Packに実行可能な値を使用できません"); if (containsRawHtml(pack)) errors.push("Content Packにraw HTMLを使用できません"); if (!validId(pack.id) || typeof pack.version !== "string" || typeof pack.name !== "string") errors.push("Content Pack metadataが不正です"); if (!Array.isArray(pack.events)) errors.push("Content Pack eventsが配列ではありません: " + pack.id); else pack.events.forEach(function (definition) { var result = E.validateDefinition(definition); if (eventIds[definition && definition.id]) errors.push("Content Pack内でイベントIDが重複しています: " + definition.id); if (definition && definition.id) eventIds[definition.id] = true; errors = errors.concat(result.errors); }); (pack.arcs || []).forEach(function (arc) { var result = validateArcDefinition(Object.assign({}, arc, { packId: pack.id })); if (arcIds[arc && arc.id]) errors.push("Content Pack内でStory Arc IDが重複しています: " + arc.id); if (arc && arc.id) arcIds[arc.id] = true; errors = errors.concat(result.errors); }); return { ok: errors.length === 0, errors: errors }; };
  var validateContentPackBase = E.validateContentPack;
  E.validateContentPack = function (pack) { var result = validateContentPackBase(pack), errors = result.errors.slice(), localEvents = {}; (pack && pack.events || []).forEach(function (definition) { if (definition && definition.id) localEvents[definition.id] = true; }); (pack && pack.arcs || []).forEach(function (arc) { if (arc.startEventId && !localEvents[arc.startEventId]) errors.push("Story Arc startEventIdが存在しません: " + arc.startEventId); (arc.completionConditions || []).concat(arc.failureConditions || []).forEach(function (condition) { var error = validateCondition(condition, arc.id); if (error) errors.push(error); }); }); return { ok: errors.length === 0, errors: errors }; };
  E.compileTriggerIndex = function (registry) { registry = registry || S.Data.ContentPackRegistry; var errors = [], index = {}, eventIds = {}, arcIds = {}, graph = {}, manualArcs = S.Data.StoryArcRegistry.manualDefinitions || {}; if (!isObject(registry) || !isObject(registry.packs) || !Array.isArray(registry.order)) return { ok: false, errors: ["Content Pack Registryが不正です"] }; S.Data.StoryArcRegistry.definitions = {}; S.Data.StoryArcRegistry.order = []; Object.keys(manualArcs).forEach(function (arcId) { S.Data.StoryArcRegistry.definitions[arcId] = manualArcs[arcId]; S.Data.StoryArcRegistry.order.push(arcId); arcIds[arcId] = true; }); registry.order.forEach(function (packId) { var pack = registry.packs[packId], result = E.validateContentPack(pack); if (!pack || pack.id !== packId) errors.push("Content Pack RegistryのIDが一致しません: " + packId); errors = errors.concat(result.errors); if (!result.ok) return; pack.events.forEach(function (definition) { if (eventIds[definition.id]) errors.push("Registry内でイベントIDが重複しています: " + definition.id); else { eventIds[definition.id] = Object.assign({ _packId: packId }, definition); graph[definition.id] = eventReferences(definition); index[definition.trigger] = index[definition.trigger] || []; index[definition.trigger].push(eventIds[definition.id]); } }); (pack.arcs || []).forEach(function (arc) { if (arcIds[arc.id]) errors.push("Registry内でStory Arc IDが重複しています: " + arc.id); else { arcIds[arc.id] = true; S.Data.StoryArcRegistry.definitions[arc.id] = clone(Object.assign({}, arc, { packId: packId })); S.Data.StoryArcRegistry.order.push(arc.id); } }); }); Object.keys(registry.packs).forEach(function (packId) { if (registry.order.indexOf(packId) < 0) errors.push("Content Packがorderにありません: " + packId); }); Object.keys(graph).forEach(function (eventId) { graph[eventId].forEach(function (ref) { if (!eventIds[ref]) errors.push("unknown event reference: " + eventId + " -> " + ref); }); }); var visiting = {}, visited = {}; function visit(id) { if (visiting[id]) { errors.push("event chain cycle: " + id); return; } if (visited[id]) return; visiting[id] = true; (graph[id] || []).forEach(function (next) { if (eventIds[next]) visit(next); }); visiting[id] = false; visited[id] = true; } Object.keys(graph).forEach(visit); Object.keys(index).forEach(function (trigger) { index[trigger].sort(function (a, b) { return (a.priority || 0) - (b.priority || 0) || a.id.localeCompare(b.id); }); }); if (!errors.length) registry.triggerIndex = index; return { ok: errors.length === 0, triggerIndex: index, errors: errors }; };
  E.validateContentPackRegistry = function (registry) { var result = E.compileTriggerIndex(registry); return { ok: result.ok, errors: result.errors }; }; E.validateRegistry = E.validateContentPackRegistry;
  E.registerContentPack = function (pack) { var registry = S.Data.ContentPackRegistry, validation = E.validateContentPack(pack); if (!validation.ok) return validation; if (registry.packs[pack.id]) return { ok: false, errors: ["Content Packは登録済みです: " + pack.id] }; registry.packs[pack.id] = clone(pack); registry.order.push(pack.id); var compiled = E.compileTriggerIndex(registry); if (!compiled.ok) { delete registry.packs[pack.id]; registry.order = registry.order.filter(function (id) { return id !== pack.id; }); E.compileTriggerIndex(registry); } return compiled; };

  E.SELECTOR_TYPES = Object.freeze(selectorTypes.slice()); E.CONDITION_TYPES = Object.freeze(conditionTypes.slice()); E.EFFECT_TYPES = Object.freeze(effectTypes.slice()); E.TRIGGERS = S.Config.EVENT_TRIGGERS; E.LIMITS = Object.freeze(clone(LIMITS)); E.ContentPackRegistry = S.Data.ContentPackRegistry; E.MAX_QUEUE = LIMITS.queue; E.MAX_HISTORY = LIMITS.history;
  E.escapeText = escapeText; E.findDefinition = findDefinition; E.addDiagnostic = addDiagnostic;
  E.addLog = function (state, text, type) { state.events.log.push({ text: String(text), type: type || "" }); while (state.events.log.length > 120) state.events.log.shift(); };
  E.addChronicle = function (state, text) { state.chronicle.push({ date: dateLabel(state), text: String(text) }); };
  E.playerCastles = function (state) { return Object.keys(state.castles).map(function (id) { return state.castles[id]; }).filter(function (castle) { return castle.factionId === state.campaign.playerFactionId; }); };
  E.createDeterministicRng = function (seed) { var initial = Number.isInteger(seed) ? seed >>> 0 : S.Config.DEFAULT_EVENT_RNG_SEED >>> 0, current = initial, calls = 0; function random() { current = (Math.imul(1664525, current) + 1013904223) >>> 0; calls += 1; return current / 4294967296; } random.next = random; random.snapshot = function () { return { seed: initial, state: current, calls: calls }; }; return random; }; E.createRng = E.createDeterministicRng;
  E.resolveSelectors = function (state, definition, payload, injected) { return resolveSelectors(state, definition, clone(payload || {}), normalizeRandom(state, injected)); };
  E.evaluateConditions = function (state, conditions, instance) { return evaluateConditions(state, conditions, instance || null); };
  E.matches = function (state, definition, instance) { return evaluateConditions(state, conditionsOf(definition), instance || null).ok && !(definition.once && (state.events.triggeredIds.indexOf(definition.id) >= 0 || state.events.engine.onceKeys[definition.id])); };
  E.renderTemplateResult = function (state, instance, template, values) { var result = plainTemplate(state, instance, template, values); return { text: escapeText(result.text), diagnostics: result.diagnostics }; }; E.renderTemplate = function (state, instance, template, values) { return E.renderTemplateResult(state, instance, template, values).text; };
  E.choiceViews = function (state, instance) { return (instance.availableChoices || []).map(function (choice) { var available = choiceAvailability(state, instance, choice); return { id: choice.id, label: E.renderTemplate(state, instance, choice.label, {}), speakerTarget: choice.speakerTarget || null, enabled: available.enabled, disabledReason: available.enabled ? "" : E.renderTemplate(state, instance, choice.disabledReason || available.reason, {}), costs: (choice.costs || []).map(function (cost) { return (cost.resource === "gold" ? "金" : "兵糧") + cost.amount; }).join("・"), fallback: Boolean(choice.fallback) }; }); };
  E.renderEvent = function (state, instance) { var definition = findDefinition(instance.eventId); return definition ? { instanceId: instance.instanceId, kicker: E.renderTemplate(state, instance, definition.kicker || "EVENT", {}), title: E.renderTemplate(state, instance, definition.title || definition.message || definition.id, {}), body: E.renderTemplate(state, instance, definition.body || definition.message || "", {}), choices: E.choiceViews(state, instance), targets: clone(instance.targets) } : null; };
  E.apply = function (state, definition, injected) { return processDefinition(state, Object.assign({ _packId: definition._packId || "core_season_events" }, definition), {}, normalizeRandom(state, injected)); };
  E.emit = function (state, trigger, payload, options) { if (typeof options === "function") options = { random: options }; options = options || {}; payload = clone(payload || {}); var compiled = E.compileTriggerIndex(), messages = [], errors = [], applied = [], skipped = [], instances = [], random = normalizeRandom(state, options.random || options.rng), createdCount = 0; if (!compiled.ok) { compiled.errors.forEach(function (error) { addDiagnostic(state, "registry_invalid", error, null); }); return { ok: true, stateChanges: { appliedEventIds: [] }, messages: [], errors: [] }; } if (triggerValues.indexOf(trigger) < 0) return { ok: false, stateChanges: {}, messages: [], errors: ["未定義のイベントtriggerです: " + trigger] }; (compiled.triggerIndex[trigger] || []).some(function (definition) { if (state.events.engine.enabledPackIds.indexOf(definition._packId) < 0) return false; if (createdCount >= LIMITS.eventsPerEmit) { addDiagnostic(state, "emit_limit", "1回のemitで作成できるイベント上限20件に達しました", null); return true; } var beforeId = state.events.engine.nextInstanceId, result = processDefinition(state, definition, payload, random); if (state.events.engine.nextInstanceId > beforeId) createdCount += 1; if (!result.ok) errors = errors.concat(result.errors || []); else if (result.skipped) skipped.push(definition.id); else { applied.push(definition.id); if (result.instance) instances.push(result.instance.instanceId); messages = messages.concat(result.messages || []); } return false; }); var engine = state.events.engine; engine.emissionCount += 1; engine.lastTrigger = trigger; engine.emissions.push({ sequence: engine.emissionCount, trigger: trigger, turn: state.campaign.turn, eventIds: applied.slice(), instanceIds: instances.slice() }); while (engine.emissions.length > 100) engine.emissions.shift(); return { ok: errors.length === 0, stateChanges: { trigger: trigger, payload: payload, appliedEventIds: applied, skippedEventIds: skipped, instanceIds: instances, activeEvent: clone(engine.activeEvent) }, messages: messages, errors: errors }; };
  E.resolveChoice = function (state, instanceId, choiceId) { var active = state.events.engine.activeEvent; if (!active || active.instanceId !== instanceId) { if (state.events.engine.history.some(function (entry) { return entry.instanceId === instanceId; })) return { ok: false, errors: ["このイベント選択は既に実行されています"] }; return { ok: false, errors: ["選択対象のactive eventがありません"] }; } return resolveTransaction(state, active, choiceId, false, {}); };
  E.resolveAIChoice = function (state, instanceId, options) { var engine = state.events.engine, active = engine.activeEvent && engine.activeEvent.instanceId === instanceId ? engine.activeEvent : null, queued = engine.queue.find(function (item) { return item.instanceId === instanceId; }), instance = active || queued; if (!instance) return { ok: false, errors: ["AIイベントinstanceがありません"] }; if (factionForInstance(state, instance) === state.campaign.playerFactionId && !(options && options.force)) return { ok: false, errors: ["プレイヤーイベントはAI解決できません"] }; var choice = chooseAI(state, instance, options || {}); if (!choice) return { ok: false, errors: ["AIが選べるイベント選択肢がありません"] }; if (queued) engine.queue = engine.queue.filter(function (item) { return item.instanceId !== instanceId; }); return resolveTransaction(state, instance, choice.id, !active, { ai: true, random: options && (options.random || options.rng) }); };
  E.resolveAIEvents = function (state, options) { var resolved = [], guard = 0, active; while ((active = state.events.engine.activeEvent) && factionForInstance(state, active) !== state.campaign.playerFactionId && guard < LIMITS.eventsPerEmit) { var result = E.resolveAIChoice(state, active.instanceId, options || {}); if (!result.ok) return result; resolved.push(result.stateChanges); guard += 1; } return { ok: true, stateChanges: { resolved: resolved }, errors: [], messages: [] }; };
  E.queueEvent = function (state, eventId, payload, options) { options = options || {}; return queueById(state, eventId, clone(payload || {}), normalizeRandom(state, options.random || options.rng), options.chainDepth || 1); };
  E.getActiveEvent = function (state) { return state.events.engine.activeEvent ? clone(state.events.engine.activeEvent) : null; }; E.hasBlockingEvent = function (state) { return Boolean(state && state.events && state.events.engine && state.events.engine.activeEvent); }; E.getPendingInteraction = function (state) { return state.events.engine.pendingInteraction ? clone(state.events.engine.pendingInteraction) : null; };
  E.completeInteraction = function (state, type) { var interaction = state.events.engine.pendingInteraction; if (!interaction || interaction.type !== type) return { ok: false, errors: ["完了対象のイベントinteractionがありません"] }; state.events.engine.pendingInteraction = null; return { ok: true, stateChanges: { type: type }, messages: [], errors: [] }; };
  E.enablePack = function (state, packId, enabled) { if (!S.Data.ContentPackRegistry.packs[packId]) return { ok: false, errors: ["Content Packが存在しません"] }; var list = state.events.engine.enabledPackIds; if (enabled && list.indexOf(packId) < 0) list.push(packId); if (!enabled) state.events.engine.enabledPackIds = list.filter(function (id) { return id !== packId; }); return { ok: true, stateChanges: { enabledPackIds: state.events.engine.enabledPackIds.slice() }, errors: [], messages: [] }; };
  E.clearQueue = function (state) { state.events.engine.queue.forEach(function (item) { cancelInstance(state, item, "debug_queue_clear", "デバッグ操作でキューを消去しました"); }); state.events.engine.queue = []; return { ok: true, stateChanges: {}, errors: [], messages: [] }; };
  E.reconcileInstances = function (state) { var engine = state.events.engine, cancelled = []; engine.enabledPackIds = (engine.enabledPackIds || []).filter(function (packId) { if (S.Data.ContentPackRegistry.packs[packId]) return true; addDiagnostic(state, "content_pack_missing", "Content Packが見つかりません: " + packId, null); return false; }); if (engine.activeEvent && !findDefinition(engine.activeEvent.eventId)) { cancelled.push(engine.activeEvent.instanceId); cancelInstance(state, engine.activeEvent, "event_definition_missing", "イベント定義が見つからないため取り消しました"); engine.activeEvent = null; } engine.queue = (engine.queue || []).filter(function (instance) { if (findDefinition(instance.eventId)) return true; cancelled.push(instance.instanceId); cancelInstance(state, instance, "event_definition_missing", "イベント定義が見つからないため取り消しました"); return false; }); activateNext(state); return { ok: true, stateChanges: { cancelledInstanceIds: cancelled, activeEvent: clone(engine.activeEvent) }, errors: [], messages: [] }; };
  E.runSeasonEvents = function (state, random) { return E.emit(state, S.Config.EVENT_TRIGGERS.SEASON_START, { season: state.campaign.season, year: state.campaign.year }, { random: random }); }; E.runSeasonEvent = E.runSeasonEvents; E.consumeDefenseNotifications = function (state) { var items = state.events.defenseNotifications.slice(); state.events.defenseNotifications = []; return items; };
  E.compileTriggerIndex();
})(window.Sengoku);
