(function (T) {
  "use strict";
  var H={els:{},flashTimer:null};
  function clearRoute(u){if(T.Movement&&T.Movement.clearRoute)T.Movement.clearRoute(u);else{u.routePoints=[];u.routeIndex=0;u.finalFacing=null;}}
  H.init=function(){
    ["battleStatus","timeStatus","unitEmpty","unitDetails","detailOfficer","detailType","detailRole","detailSpeed","detailRange","detailReload","detailTroops","detailMorale","detailStatus","detailOrder","detailCharge","orderHint","moveBtn","attackBtn","chargeBtn","retreatBtn","waitBtn","resultPanel","resultJson","floatingMessage"].forEach(function(id){H.els[id]=document.getElementById(id);});
    document.querySelectorAll(".speed-btn").forEach(function(b){b.addEventListener("click",function(){if(T.state&&T.state.facingPrompt){H.flash("先に移動後の向きを選んでください");return;}H.setSpeed(Number(b.dataset.speed));});});
    H.els.moveBtn.addEventListener("click",function(){H.beginOrder("move");});H.els.attackBtn.addEventListener("click",function(){H.beginOrder("attack");});H.els.chargeBtn.addEventListener("click",function(){H.beginOrder("charge");});
    H.els.retreatBtn.addEventListener("click",function(){var u=T.state.units[T.state.selectedUnitId];if(!u||u.status!=="active"||T.state.facingPrompt)return;clearRoute(u);u.orderType="move";var f=T.FIELD||{height:800,margin:40};u.targetPos={x:u.position.x,y:f.height-f.margin};u.targetUnitId=null;u.chargeActive=false;u.chargeDistance=0;H.setOrderMode(null);H.setSpeed(1);});
    H.els.waitBtn.addEventListener("click",function(){var u=T.state.units[T.state.selectedUnitId];if(!u||u.status!=="active"||T.state.facingPrompt)return;clearRoute(u);u.orderType="wait";u.targetPos=null;u.targetUnitId=null;u.chargeActive=false;u.chargeDistance=0;H.setOrderMode(null);H.refresh();});
  };
  H.setSpeed=function(v){if(!T.clock)return;T.clock.setSpeed(v);document.querySelectorAll(".speed-btn").forEach(function(b){b.classList.toggle("active",Number(b.dataset.speed)===v);});H.els.timeStatus.textContent=v===0?"停止":v===1?"通常":"3倍速";};
  H.beginOrder=function(mode){var u=T.state.units[T.state.selectedUnitId];if(!u||u.status!=="active"||T.state.facingPrompt)return;if(mode==="charge"&&!T.Combat.canCharge(u)){H.flash("騎馬・侍のみ / 再使用待ち");return;}H.setSpeed(0);T.state.orderMode=mode;H.setOrderMode(mode);};
  H.showHint=function(text){if(H.els.orderHint)H.els.orderHint.textContent=text;};
  H.setOrderMode=function(mode){document.querySelectorAll(".order-btn").forEach(function(b){b.classList.remove("selected");});if(mode==="move"){H.els.moveBtn.classList.add("selected");H.showHint("従来操作: 移動先をタップ。新操作: 部隊を直接ドラッグして経路を描けます。");}else if(mode==="attack"){H.els.attackBtn.classList.add("selected");H.showHint("攻撃する敵部隊をタップしてください。");}else if(mode==="charge"){H.els.chargeBtn.classList.add("selected");H.showHint("突撃対象を選択。距離70以上で突撃ボーナス。");}else H.showHint("部隊を指で押したまま経路をなぞる → 指を離す → 移動後の向きを8方向から選択。従来の命令ボタンも使えます。");};
  H.refresh=function(){
    if(!T.state)return;var u=T.state.units[T.state.selectedUnitId];H.els.battleStatus.textContent=T.state.status==="running"?"会戦中 / Tick "+T.state.tick:(T.state.winner==="player"?"勝利":T.state.winner==="draw"?"引き分け":"敗北");if(!u){H.els.unitEmpty.hidden=false;H.els.unitDetails.hidden=true;return;}H.els.unitEmpty.hidden=true;H.els.unitDetails.hidden=false;var type=T.UnitTypes[u.unitType];H.els.detailOfficer.textContent=u.officerName;H.els.detailType.textContent=type.name;H.els.detailRole.textContent=type.role||"-";H.els.detailSpeed.textContent=type.speed.toFixed?type.speed.toFixed(0):type.speed;H.els.detailRange.textContent=type.range>0?type.range+" / 自動射撃":"近接";H.els.detailReload.textContent=type.range>0?(u.reloadRemaining>0?(u.reloadRemaining/10).toFixed(1)+"秒":"射撃可能"):"-";H.els.detailTroops.textContent=u.troops+" / "+u.maxTroops;H.els.detailMorale.textContent=Math.round(u.morale);H.els.detailStatus.textContent=u.status==="active"?"戦闘可能":u.status==="routed"?"敗走中":"壊滅";H.els.detailOrder.textContent=u.orderType==="route"?"経路移動 ("+Math.max(0,(u.routePoints||[]).length-u.routeIndex)+"点)":u.orderType;H.els.detailCharge.textContent=!type.canCharge?"不可":u.chargeCooldown>0?"再使用まで "+(u.chargeCooldown/10).toFixed(1)+"秒":u.chargeActive?"突撃中 / 助走 "+Math.round(u.chargeDistance):"使用可能";
    var enabled=u.side==="player"&&u.status==="active"&&T.state.status==="running"&&!T.state.facingPrompt;[H.els.moveBtn,H.els.attackBtn,H.els.retreatBtn,H.els.waitBtn].forEach(function(b){b.disabled=!enabled;});H.els.chargeBtn.disabled=!enabled||!T.Combat.canCharge(u);
  };
  H.flash=function(text){clearTimeout(H.flashTimer);H.els.floatingMessage.textContent=text;H.els.floatingMessage.classList.add("show");H.flashTimer=setTimeout(function(){H.els.floatingMessage.classList.remove("show");},850);};
  H.showResult=function(result){H.els.resultPanel.hidden=false;H.els.resultJson.textContent=JSON.stringify(result,null,2);};
  T.HUD=H;
})(window.Tactical = window.Tactical || {});
