(function (S) {
  "use strict";
  var U = S.UI;
  function name(state, id) { return state.factions[id] ? state.factions[id].name : id; }
  function treatyRemaining(state, relation) { return Number.isInteger(relation.expiresTurn) ? Math.max(0, relation.expiresTurn - state.campaign.turn) + "季" : "—"; }
  function vassalLabel(state, factionId) {
    var overlord = S.Systems.Diplomacy.overlordOf(state, factionId); if (overlord) return "従属 → " + name(state, overlord);
    var subjects = Object.keys(state.diplomacy.vassalage).filter(function (id) { return state.diplomacy.vassalage[id].overlordFactionId === factionId; });
    return subjects.length ? "宗主（" + subjects.map(function (id) { return name(state, id); }).join("・") + "）" : "独立";
  }
  U.showDiplomacy = function () {
    var state = S.State.current, playerId = state.campaign.playerFactionId, pending = state.diplomacy.proposals.filter(function (item) { return item.status === "pending" && item.targetFactionId === playerId; });
    var list = Object.keys(state.factions).filter(function (id) { return id !== playerId; }).map(function (id) {
      var relation = S.Systems.Diplomacy.relation(state, playerId, id), power = Math.round(S.Systems.Diplomacy.power(state, id));
      return "<button class=\"choice diplomacy-row\" data-diplomacy-target=\"" + U.escape(id) + "\"><strong>" + U.escape(name(state, id)) + " — " + U.escape(S.Systems.Diplomacy.label(relation.status)) + "</strong><small>関係" + relation.score + " / 信頼" + relation.trust + " / 遺恨" + relation.grievance + " / 評判" + state.diplomacy.reputation[id] + " / 疲弊" + state.diplomacy.warExhaustion[id] + " / 国力" + power + " / 残り" + treatyRemaining(state, relation) + " / " + U.escape(vassalLabel(state, id)) + "</small></button>";
    }).join("");
    U.openModal("<p class=\"kicker\">FACTION DIPLOMACY</p><h2>外交</h2><p>自勢力：" + U.escape(name(state, playerId)) + "　評判" + state.diplomacy.reputation[playerId] + " / 戦争疲弊" + state.diplomacy.warExhaustion[playerId] + " / " + U.escape(vassalLabel(state, playerId)) + "</p><div class=\"choices\">" + list + "</div><div class=\"modal-actions\">" + (pending.length ? "<button class=\"button danger\" data-open-proposals>AI提案 " + pending.length + "件</button>" : "") + "<button class=\"button secondary\" data-open-diplomacy-history>外交履歴</button><button class=\"button primary\" data-close-modal>閉じる</button></div>");
  };
  U.showDiplomacyDetail = function (targetId) {
    var state = S.State.current, playerId = state.campaign.playerFactionId, target = state.factions[targetId], relation = S.Systems.Diplomacy.relation(state, playerId, targetId);
    if (!target || !relation) { U.notify("外交対象が見つかりません", "error"); return; }
    var messengers = Object.keys(state.officers).map(function (id) { return state.officers[id]; }).filter(function (officer) { return officer.factionId === playerId && officer.status === "active"; }).sort(function (a, b) { return b.stats.politics - a.stats.politics; });
    var sourceCastles = S.Systems.Diplomacy.castlesFor(state, targetId), targetCastles = S.Systems.Diplomacy.castlesFor(state, playerId), availability = S.Systems.Diplomacy.actionAvailability(state, playerId, targetId), availabilityById = {};
    availability.forEach(function (item) { availabilityById[item.id] = item; });
    function action(id, label) { var item = availabilityById[id] || { enabled: true, reason: "実行可能" }; return "<button class=\"button secondary\" data-diplomacy-action=\"" + id + "\" data-diplomacy-faction=\"" + U.escape(targetId) + "\"" + (item.enabled ? "" : " disabled") + " title=\"" + U.escape(item.reason) + "\">" + U.escape(label) + "<small>" + U.escape(item.reason) + "</small></button>"; }
    var playerSubject = state.diplomacy.vassalage[playerId], targetSubject = state.diplomacy.vassalage[targetId], prisoner = state.prisoners.find(function (id) { return state.officers[id].captorFactionId === playerId && state.officers[id].factionId === targetId; });
    U.openModal("<p class=\"kicker\">DIPLOMACY DETAIL</p><h2>" + U.escape(target.name) + "</h2>" +
      "<div class=\"diplomacy-stats\"><div><span>状態</span><strong>" + U.escape(S.Systems.Diplomacy.label(relation.status)) + "</strong></div><div><span>score</span><strong>" + relation.score + "</strong></div><div><span>trust</span><strong>" + relation.trust + "</strong></div><div><span>grievance</span><strong>" + relation.grievance + "</strong></div><div><span>評判</span><strong>" + state.diplomacy.reputation[targetId] + "</strong></div><div><span>疲弊</span><strong>" + state.diplomacy.warExhaustion[targetId] + "</strong></div><div><span>国力</span><strong>" + Math.round(S.Systems.Diplomacy.power(state, targetId)) + "</strong></div><div><span>条約残り</span><strong>" + treatyRemaining(state, relation) + "</strong></div></div>" +
      "<p>" + U.escape(vassalLabel(state, targetId)) + "</p><label class=\"field\"><span>使者</span><select id=\"diplomacyMessenger\">" + messengers.map(function (officer) { return "<option value=\"" + U.escape(officer.id) + "\">" + U.escape(officer.name) + "（政治" + officer.stats.politics + "）</option>"; }).join("") + "</select></label>" +
      "<div class=\"diplomacy-actions\">" + action("improve", "関係改善") + action("declare_war", "宣戦") + action("peace", "和平") + action("ceasefire", "停戦") + action("non_aggression", "不戦条約") + action("alliance", "同盟") + action("extend", "条約延長") + action("break_treaty", "条約破棄") + action("aid", "物資援助") + action("reinforcement", "援軍要請") + action("prisoner_exchange", "捕虜交換") + (prisoner ? action("release_prisoner", "捕虜を一方解放") : "") + action("surrender", "降伏勧告") + action("vassalage", "従属提案") + (targetSubject && targetSubject.overlordFactionId === playerId ? action("release_vassal", "従属解除") : "") + (playerSubject && playerSubject.overlordFactionId === targetId ? action("independence", "独立") : "") + "</div>" +
      "<details class=\"diplomacy-options\"><summary>援助・援軍の指定</summary><label class=\"field\"><span>援助（金 / 兵糧）</span><input id=\"diplomacyAidGold\" type=\"number\" min=\"0\" value=\"10\"><input id=\"diplomacyAidFood\" type=\"number\" min=\"0\" value=\"10\"></label><label class=\"field\"><span>援軍元（相手）</span><select id=\"diplomacyReinforceSource\">" + sourceCastles.map(function (castle) { return "<option value=\"" + U.escape(castle.id) + "\">" + U.escape(castle.name) + "（兵" + castle.troops + "）</option>"; }).join("") + "</select></label><label class=\"field\"><span>援軍先（自勢力）</span><select id=\"diplomacyReinforceTarget\">" + targetCastles.map(function (castle) { return "<option value=\"" + U.escape(castle.id) + "\">" + U.escape(castle.name) + "</option>"; }).join("") + "</select></label><label class=\"field\"><span>援軍数</span><input id=\"diplomacyReinforceTroops\" type=\"number\" min=\"1\" value=\"10\"></label></details>" +
      "<div class=\"modal-actions\"><button class=\"button secondary\" data-open-diplomacy>一覧へ</button><button class=\"button primary\" data-close-modal>閉じる</button></div>");
  };
  U.showDiplomacyHistory = function () {
    var entries = S.State.current.diplomacy.history.slice().reverse();
    U.openModal("<p class=\"kicker\">DIPLOMACY HISTORY</p><h2>外交履歴</h2>" + (entries.length ? entries.map(function (entry) { return "<div class=\"record\"><strong>第" + entry.turn + "季 — " + U.escape(S.Systems.Diplomacy.proposalLabel(entry.type)) + "</strong><p>" + U.escape(entry.text) + "</p></div>"; }).join("") : "<p>外交履歴はありません。</p>") + "<div class=\"modal-actions\"><button class=\"button secondary\" data-open-diplomacy>外交へ</button><button class=\"button primary\" data-close-modal>閉じる</button></div>");
  };
  U.showPendingProposals = function () {
    var state = S.State.current, playerId = state.campaign.playerFactionId, proposals = state.diplomacy.proposals.filter(function (item) { return item.status === "pending" && item.targetFactionId === playerId; });
    U.openModal("<p class=\"kicker\">AI PROPOSALS</p><h2>外交提案</h2>" + (proposals.length ? proposals.map(function (proposal) { return "<div class=\"record\"><strong>" + U.escape(name(state, proposal.actorFactionId)) + " — " + U.escape(S.Systems.Diplomacy.proposalLabel(proposal.type)) + "</strong><p>期限：第" + proposal.expiresTurn + "季</p><div class=\"modal-actions\"><button class=\"button secondary\" data-respond-proposal=\"reject\" data-proposal-id=\"" + U.escape(proposal.id) + "\">拒否</button><button class=\"button primary\" data-respond-proposal=\"accept\" data-proposal-id=\"" + U.escape(proposal.id) + "\">受諾</button></div></div>"; }).join("") : "<p>保留中の提案はありません。</p>") + "<div class=\"modal-actions\"><button class=\"button secondary\" data-open-diplomacy>外交へ</button><button class=\"button primary\" data-close-modal>閉じる</button></div>");
  };
})(window.Sengoku);
